### ISSUE TITLE
Extract Koala cell value results in error 

### ISSUE THREAD

**Issue by dennyglee** [databricks/koalas#100]
Scenario:
```
# Create Small Sample Dataset
dates = pd.date_range('20130101', periods=6)
pdf = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
kdf = spark.from_pandas(pdf)
```

When running this via Pandas, this works as expected:
```
pdf['D'][0]

Out[107]: 0.3420981969020352
```

But with Koalas, get the following error:
```
kdf['D'][0]

Out[106]: <repr(<pyspark.sql.column.Column at 0x7fcdeb84e710>) failed: pyspark.sql.utils.AnalysisException: "Can't extract value from D#6026: need struct type but got double;">
```

**Comment by rxin** [comment]
We don't yet support positional value I think. It's somewhat tricky to do this, especially given a large N.

**Comment by thunterdb** [comment]
@dennyglee you can take the head for now. There was some code to implement positional index, but it can cause serious performance issues. Use `.head()` or `.loc` instead for now.

**Comment by dennyglee** [comment]
Got it - will do for now!  thanks!

**Comment by rxin** [comment]
Closing since I'm not sure if there is a good way to do this.
