### ISSUE TITLE
Limitation section in our official documentation

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#1014]
- Expensive operations In general
- Reserved column names (`__...__`)
- Disallow duplicated column names
- Default index Overview (?)
- ...

**Comment by HyukjinKwon** [comment]
cc @ueshin, @thunterdb, @rxin, WDYT about this? and do you guys have some items to document in your mind?

**Comment by rxin** [comment]
Looks good. We can always get started with a smaller set and expand over time.

**Comment by HyukjinKwon** [comment]
Cool, let me get this done as are for now.

**Comment by HyukjinKwon** [comment]
I reworded to "Best Practices" and opened a PR at https://github.com/databricks/koalas/pull/1041
