### ISSUE TITLE
.head() is slow on koalas but really fast for spark dataframe

### ISSUE THREAD

**Issue by koshy1123** [databricks/koalas#1028]
I have a partitioned parquet table (117M rows, ~1000 partitions) that is stored on S3 with the Hive metastore pointing to a table name, say, `table_foo`. Let's say it's partitioned by columns, `p1`, `p2`

I read the table as a koalas dataframe as:
```
kdf = ks.read_table('table_foo')
```

When I try a `.head()`, it _seems_ like it's scanning the WHOLE table instead of just looking at one partition and returning the first 5 rows. It runs in the order of 5+ minutes easily without cache. This seems counter to this section [here](https://koalas.readthedocs.io/en/latest/getting_started/10min.html#Viewing-Data)
> When asked for the head of a dataframe, Spark will just take the requested number of rows from a partition.

I tried to query just the partitions too to see if it speeds it up, but it was still as slow. This makes me think the partitions are actually not being respected in the koalas dataframe when using filters like below. Is that accurate? 
```
kdf[(kdf['p1']=='hello') & (kdf['p2']=='world')].head()
```

If I read the table as a spark dataframe, it seems to work as expected:
```
sdf = spark.read.table('table_foo')
```
The `.head()` on this is very fast. Similarly, I can run something like:
```
sdf.filter("p1 = 'hello' and p2 = 'world'").head(20)
```
and that is also really fast.

Any clues as to what's going on or if my approach is incorrect?

**Comment by HyukjinKwon** [comment]
I think it's because of https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type

You might have to use different default index type, can you try `distributed` type?

Such limitations might have to be more exposed to users .. that will be handled at https://github.com/databricks/koalas/issues/1014

**Comment by koshy1123** [comment]
Sweet - that was way faster! Thanks for the pointer. I'll close this one for now.

**Comment by ueshin** [comment]
If you have columns to be used as index, you can also use `index_col` argument for `ks.read_table` which uses the given columns as index and avoid attaching the default index.

**Comment by matthewgson** [comment]
I'm having the same issue described above, but setting different default index type ```distributed``` or ```distributed-sequence``` did not solve the problem. I have 213 million row data (10gb parquet) I took me 3 min on my local computer to run ```.head()```

However, when I export it into spark dataframe, ```.show()``` is running very fast. I'm wondering what is causing this problem...

**Comment by HyukjinKwon** [comment]
Can you show your full codes? There should be virtually no differences if we use `distributed`.

**Comment by matthewgson** [comment]
```
import databricks.koalas as ks
ks.set_option('compute.default_index_type', 'distributed-sequence')
df = ks.read_parquet('~/datasets/data.parquet')
df.head()
```
I also tried with 
```
ks.set_option('compute.default_index_type', 'distributed')
```
Above takes a long time, by the way,
```
sdf = df.to_spark()
sdf.show()
```
Above spark is very fast. I checked with ```.show(100)``` and so forth.
Am I missing something?

**Comment by HyukjinKwon** [comment]
Ah, that's probably because of the CSV schema inference which requires to scan whole data once. You can currently work around via manually specifying the schema e.g.: `ks.read_csv("...", names="column1 string, column2 int")`.
