### ISSUE TITLE
Cannot import databricks.koalas

### ISSUE THREAD

**Issue by Yagrini** [databricks/koalas#1031]
I'm using python3.5, after installing koalas using pip i can't import it.
I get the error  **_ImportError: cannot import name 'pandas_udf'_**
Do I need to install Koalas in all worker nodes?

**Comment by HyukjinKwon** [comment]
Seems like your PySpsrk version is too low. What's your PySpark version?

**Comment by HyukjinKwon** [comment]
Closing this due to no feedback from the reporter.
