### ISSUE TITLE
koalas.Series.mode() not returning sorted values

### ISSUE THREAD

**Issue by SanRioJack** [databricks/koalas#1047]
Koalas.Series.mode is not returning values in sorted order 
Pandas Version: 0.25.3
Koalas Version: 0.21.0

`pdf = pd.read_csv('/test/test.csv', index_col=0)`
`kdf = ks.from_pandas(pdf)`

Pandas Series mode function returns values in sorted order

`pdf.Numeric_float_col.mode().head()`
`0    58.351226`
`1    98.002419`
`2    98.023862`
`3    99.022165`
`4    99.039145`
`dtype: float64`

Whereas performing same operation using Koalas Series doesn't return sorted values as mentioned in the documentation
`kdf.Numeric_float_col.mode().head()`
`0     449.726629`
`1     149.175250`
`2     599.080985`
`3    1799.689583`
`4    1999.392477`
`Name: Numeric_float_col, dtype: float64`

**Comment by ueshin** [comment]
Repost here too:
ah, we might need to sort the result values since the doc says it returns values in sorted order. here, also https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mode.html Otherwise we should remove "in sorted order" from the doc.
cc @HyukjinKwon

**Comment by ueshin** [comment]
Basically Koalas doesn't guarantee the row order without a special reason, though.
What do you think about this case? @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Ah, thanks @ueshin. I missed that comment. @itholic can you make a PR to remove that sentence in the doc for now?
