### ISSUE TITLE
DataFrame.dropna(axis=1)

### ISSUE THREAD

**Issue by iabdrashitov** [databricks/koalas#1053]
Does anybody work on adding axis=1 support to the dropna method?

**Comment by itholic** [comment]
i can take it if you want to use it.
or you want to work on this and make the PR??

**Comment by iabdrashitov** [comment]
I can work on it

**Comment by itholic** [comment]
@iabdrashitov Cool. let's go ahead! 😸

**Comment by HyukjinKwon** [comment]
Please go ahead.

**Comment by ueshin** [comment]
I'll take this.
