### ISSUE TITLE
why corr returns pandas dataframe?

### ISSUE THREAD

**Issue by harupy** [databricks/koalas#1063]
This is not an issue, but just out of curiosity. Why does `corr` return pandas dataframe instead of koalas dataframe?

https://github.com/databricks/koalas/blob/723aefcad70f86dc34b55dbd65bd0968381cd750/databricks/koalas/ml.py#L34-L60

**Comment by HyukjinKwon** [comment]
I think we should fix

**Comment by harupy** [comment]
@HyukjinKwon 
Got it. I'll open a PR for this.

**Comment by harupy** [comment]
Resolved via #1069
