### ISSUE TITLE
how convert a dataframe with null values to csv?

### ISSUE THREAD

**Issue by MammadTavakoli** [databricks/koalas#1090]
When i use to_csv in koalas for converting a Data-frame to CSV, the null values fill with ` \"\"` , but i want null values be null. The code is:

`df.to_csv(path='test', num_files=1)`
How can set koalas to don't do this for null values?

when I canverto it to pandas and save the pandas dataframe evry thing is ok:
```
pdf =df.to_pandas()
pdf.to_csv('t.csv')
```

**Comment by itholic** [comment]
Thanks for reporting issue for Koalas :D

if maybe it possible, could you show me how `df` looks like for reproducing your case??

In my case,

```python
>>> df = DataFrame({'a': ['hello world', None, 'good bye']})
>>> df
             a
0  hello world
1         None
2     good bye
>>>
>>> df.to_csv(path='test_csv', num_files=1)
```

above example make csv file look like below, and i couldn't see the `\"\"` string.

```
a
hello world
""
good bye
```

thank you :)

**Comment by MammadTavakoli** [comment]
I see my empty cells. I use this:
K = df.iloc[[0]]['col1'].to_string()
For I in k:
        Print(ord(i))
The result is:
48
32
32
32
32
32

**Comment by HyukjinKwon** [comment]
Koalas' `to_csv` also supports to take PySpark's CSV options (see https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/DataFrameWriter.scala#L777-L814).

Can you try `nullValue` option or `emptyValue`? e.g., `to_csv(..., nullValue="...")`

**Comment by MammadTavakoli** [comment]
The value of cell is `space`, the ord of that is 32.
but i dont know how replace that with null.

**Comment by HyukjinKwon** [comment]
Can you try `to_csv(..., nullValue=" ")`?

**Comment by MammadTavakoli** [comment]
the problem is with space. when a cell value is `space `after save the as csv file, the space fill with `\"\"`.

```
d = {'col1': ['a b ', '2'], 'col2': [' ', '4']}
kdf = ks.DataFrame(data=d, columns=['col1', 'col2'])
kdf.to_csv('t')
```
