### ISSUE TITLE
Change pyspark version to 2.4 for python3.5 in travisCI.

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#1098]
In our official doc `Getting started`, says that we support pyspark 2.4+.

<img width="960" alt="스크린샷 2019-12-03 오후 1 45 25" src="https://user-images.githubusercontent.com/44108233/70021928-b1987f00-15d5-11ea-823a-334e4a9cf70b.png">

but our travisCI is using pyspark 2.3 for python3.5, so that some tests are failing.

<img width="996" alt="스크린샷 2019-12-03 오후 2 06 35" src="https://user-images.githubusercontent.com/44108233/70022039-2075d800-15d6-11ea-8b34-e88fe98020e7.png">

i think should we change this to pyspark2.4+ ??

(or fix `Getting started` ?)

**Comment by HyukjinKwon** [comment]
Let's do this later when Spark 3.0 is released.

**Comment by itholic** [comment]
@HyukjinKwon Now Spark 3.0 is released. Should we revisit ? or just leave it as it is for now?

**Comment by itholic** [comment]
Let me just close this since we don't use travis anymore.
