### ISSUE TITLE
Why do we keep tuple type for list elements in internal index_names?

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#1103]
Hello. Recent I found that there are two cases in `index_names`  element.

One, `index_names` element is None when names parameter is not setting.
```
midx = ks.DataFrame({'a': ['a', 'b']}, index=[['a', 'b'], ['x', 'y'], [1, 2]]).index
print(midx._internal.index_names)
[None, None, None] 
```

Second, `index_names` element is single element in tuple like (name, ) when setting `names` parameter or using `set_index`.
```
midx = ks.DataFrame({'a': ['a', 'b'], 'b':[1, 2], 'c':[4, 5]}).set_index(['a', 'b']).index
print(midx._internal.index_names)
 [('a',), ('b',)] 
```

I wonder know why do we keep tuple type for list elements? Can we remove the tuple and keep elements value directly like `['a', 'b']` instead of `[('a',), ('b',)]`?

**Comment by ueshin** [comment]
Now that index names support tuple names and it's for the consistent access between a scalar name and a tuple name.
The same thing is in `column_index`. Now that we support multi-index columns and `column_index` stores its name as tuple.
