### ISSUE TITLE
Re-enable PyArrow 0.15 support back

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#1109]
We should enable https://github.com/databricks/koalas/pull/1108 back once we have enough documentation and error messages.

**Comment by Hoeze** [comment]
Hi, I'm using other libraries like e.g. TileDB that depend on PyArrow 0.15.
When will there be a Koalas release with PyArrow v0.15 allowed?

**Comment by MrPowers** [comment]
[PyArrow 0.16.0 was recently released](https://pypi.org/project/pyarrow/0.16.0/), so it'd be nice to get that version supported too.

Thanks for the great work on this library!

**Comment by HyukjinKwon** [comment]
Thanks, @MrPowers. I think we will add both 0.15 and 0.16 support very soon!
