### ISSUE TITLE
Policy for None in Index looks like different from pandas.

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#1122]
in pandas.
```python
>>> pidx = pd.Index([1, 2, None, 4, 5])
>>> pidx
Index([1, 2, None, 4, 5], dtype='object')
```

koalas.
```python
>>> kidx = ks.Index([1, 2, None, 4, 5])
>>> kidx
Float64Index([1.0, 2.0, nan, 4.0, 5.0], dtype='float64')
```
is it intended? or should be fixed?

**Comment by HyukjinKwon** [comment]
pandas uses `NaN` (Not a Number) in numeric columns to represent missing values by default (and `NaT` for missing values in time type).

So, if there's missing value in numeric column, pandas changes the data type to float automatically. This might not be not ideal as pointed out by a pandas author (https://www.youtube.com/watch?v=_-gJtO0XR48&feature=youtu.be)

I am not sure if we really should follow this syntax yet, which is considered as "unexpected" behaviour.

**Comment by HyukjinKwon** [comment]
cc @ueshin, @rxin, @thunterdb FYI

**Comment by ueshin** [comment]
Related discussion at #263.

**Comment by itholic** [comment]
Yeah, seems like it's duplicated to #263.

Let me close this for now.
