### ISSUE TITLE
Merging Schema Spark -> Pandas DF

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#114]
I wrote out a single CSV file using Spark, and am trying to just read in that file directly (not the metadata) using Pandas.

However, I'm getting this "TypeError: field Transport DtTm: Can not merge type <class 'pyspark.sql.types.DoubleType'> and <class 'pyspark.sql.types.StringType'>".

Please see screenshot.
<img width="1525" alt="Screen Shot 2019-04-19 at 10 46 34 PM" src="https://user-images.githubusercontent.com/6416014/56453297-53908300-62f5-11e9-9491-4b762ab87217.png">

**Comment by rxin** [comment]
Can you upload the CSV file?

**Comment by thunterdb** [comment]
@brookewenig looking at the screenshot it may be an issue with types inferred by pandas in databricks, not a koalas issue

**Comment by rxin** [comment]
Closing this in favor of https://github.com/databricks/koalas/issues/167 since it has a repo.
