### ISSUE TITLE
implement numeric_only parameter for functions

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#1148]
There are many functions need `numeric_only` parameter to deter whether to keep object data. Can we find some ways implementing this function?

**Comment by HyukjinKwon** [comment]
I am not sure how to. I currently think the only way is just to implement each by if-else.

**Comment by itholic** [comment]
Seems like we made a decision for handling the `numeric_only` parameter in https://github.com/databricks/koalas/pull/1343.

Please feel free to leave the comment.
