### ISSUE TITLE
Support pandas>=1.0.0

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#1194]
~~As pandas 1.0.0 will be released soon, we need prepare for it.~~

As pandas 1.0.0 has released, we need support it.

so I have created some to-do list below.

- [x] update the list of APIs that are newly added .
- [x] update the list of APIs that are deprecated.
- [x] update the list of APIs that are removed.
- [x] update the name of APIs that are renamed.
- [x] list up & update the implementation of existing Koalas APIs that have incompatible with pandas>=1.0.0.
- [x] update `requirements-dev.txt` for pandas>=1.0.0
- [x] update `.travis.yml` for pandas>=1.0.0
- [x] update GitHub Actions for pandas>=1.0.0

**Comment by itholic** [comment]
cc @ueshin @HyukjinKwon 

If those lists look fine, let me take this work.

**Comment by itholic** [comment]
Please let me know if there are more things should be considered for supporting pandas 1.0.0., i'll add to list.

**Comment by HyukjinKwon** [comment]
Yeah, please go ahead.

**Comment by ueshin** [comment]
Btw, will we drop or keep `pandas<1.0`?
Dropping the older versions might be easy, but I don't think we should drop them until most of pandas users move to `pandas>=1.0`.
@itholic Could you roughly think about the design and estimate how more efforts we will need if we keep them?

**Comment by itholic** [comment]
I have roughly estimate how more efforts we will need if we keep `pandas < 1.0.0` until most of users moved to `pandas >= 1.0.0`.

For now, i think we can handle most of them with proper warning or error message for each pandas version user.

and i think it can be categorized in some ways. (of course might we need more consideration for more detail cases)

### 1. newly added elements in pandas 1.0.0
- i think we can just simply add them to support `pandas < 1.0.0` and `>= 1.0.0` both. (of course, for pandas <1.0.0 users it would be better to print the appropriate error message like "this property (or method) is supported since `pandas >= 1.0.0`")
### 2. removed elements in pandas 1.0.0
- i think maybe we can show `deprecated warning` properly (and since we already haven't considered implementation for those deprecated elements, we don't need to worry too much about this)
### 3. renamed elements
<img width="330" alt="스크린샷 2020-01-19 오후 2 27 30" src="https://user-images.githubusercontent.com/44108233/72675467-d97d6c80-3ac7-11ea-9e5b-b08334253240.png">

- this part is a little considerable, IMO, I think maybe we can support both versions right now like below.
```python
# pandas < 1.0.0, the existing implementation
def drop(self, labels, level=None):
    ...

# pandas >= 1.0.0, we just wrapping existing implementation with renamed parameter
def drop(self, codes, level=None):
    ...
    return drop(labels=codes, level=None)
```
 
since i have very roughly considered, it might more consideration is needed to properly support both versions.

**Comment by HyukjinKwon** [comment]
For "removed elements in pandas 1.0.0", I think we can just remove in Koalas too because they should be removed in Koalas anyway, and Koalas is still premature and we're trying to move fast at this moment. WDYT @ueshin? I don't mind keeping them as deprecation warnings either if you feel so.

**Comment by HyukjinKwon** [comment]
"renamed elements", this one too. I think we can just rename. It's very easy to workaround.

**Comment by itholic** [comment]
> "renamed elements", this one too. I think we can just rename. It's very easy to workaround.

then are we just raise Exception for below case?

```python
kmidx.drop(labels='koalas')  # TypeError: drop() got an unexpected keyword argument 'labels'
```

**Comment by HyukjinKwon** [comment]
Yes, I think it's fine to break this case - it can be very easily worked around `kmidx.drop('koalas')`

**Comment by itholic** [comment]
@HyukjinKwon 

Ah, i got it. 

Hmm.. If that policy is finally decided, then i think there won't be so much trouble for supporting both versions of `pandas < 1.0.0` and `pandas >= 1.0.0`

**Comment by ueshin** [comment]
Sorry for the delay.
IMO as below:

- newly added elements
  - we can just adding such elements.
- removed elements
  - If we already implemented, I'd prefer to keep it and show the deprecation message.
  - If it's in the missing list, I'd prefer to keep it but move it to deprecation list.
- renamed elements
  - If it's a simple case like the example above, we can just rename it to the new one.
  - Otherwise, let's discuss case-by-case.

One more thing I noticed in #1197 is there are some behavior changes.
I think we should also change the behavior based on the installed pandas version.

**Comment by itholic** [comment]
@ueshin Thanks for giving the opinion 👍 


Okay, then finally we can handle the elements for pandas 1.0.0 as below.

### 1. Newly added elements
- Just adding

### 2. Removed elements
- Keeping with deprecation message

### 3. Renamed elements
- Just Renaming for simple case, otherwise, discuss case-by-case


I'll clean up tomorrow at #1197 with following those rules.

**Comment by itholic** [comment]
Closing.

**Comment by itholic** [comment]
Closing since related PRs are merged.
