### ISSUE TITLE
Using nested dicts leaks pyspark.sql.Row abstraction

### ISSUE THREAD

**Issue by chunyang** [databricks/koalas#1200]
Please consider the example below. Starting with an initial pandas DataFrame, a round trip through Spark DataFrame will preserve the nested dict fields, but a round trip through koalas DataFrame will expose `pyspark.sql.Row` objects.

```python
import databricks.koalas as ks
import pandas as pd
import pyspark

pdf = pd.DataFrame({"A": [{"B": "C"}, {"D": "C"}]})

# Spark DataFrame preserves nested dict structure
spark = pyspark.sql.SparkSession.builder.master("local[*,1]").getOrCreate()
sdf = spark.createDataFrame(pdf)
sdf.show()
# +--------+
# |       A|
# +--------+
# |[B -> C]|
# |[D -> C]|
# +--------+
sdf.toPandas()
#             A
# 0  {'B': 'C'}
# 1  {'D': 'C'}
sdf.toPandas().iloc[0, 0]
# {'B': 'C'}
sdf
# DataFrame[A: map<string,string>]

# Koalas DataFrame converts nested dict structure to nested pyspark.sql.Row
kdf = ks.DataFrame(pdf)
kdf
#            A                                                                    
# 0  (C, None)
# 1  (None, C)
kdf.to_pandas()
#            A
# 0  (C, None)
# 1  (None, C)
kdf.to_pandas().iloc[0, 0]
# Row(B='C', D=None)
kdf._internal.spark_df
# DataFrame[A: struct<B:string,D:string>]
```

This seems to be due to different code paths for schema inference in Spark vs Koalas?
Spark: https://github.com/apache/spark/blob/v3.0.0-preview2/python/pyspark/sql/session.py#L787
Koalas: https://github.com/databricks/koalas/blob/v0.25.0/databricks/koalas/typedef.py#L170

koalas version: 0.25.0
pandas version: 0.25.3
pyspark version: 3.0.0.dev0

**Comment by ueshin** [comment]
Firstly, Koalas doesn't support nested types yet, and I'm not sure it will or not. If you want to handle nested types, you should just use PySpark.

Then ..

Yeah, actually the type inference is different from Spark's and we rely on Arrow so far, and Arrow doesn't support map type inference or conversion yet. I'm not sure whether it's correct to infer this case as map type, though.

As for returning `Row` object when `to_pandas()`, we should enable arrow execution within Koalas. I'll submit a PR.

**Comment by itholic** [comment]
Let me close this since it's duplicated to https://github.com/databricks/koalas/issues/420.
