### ISSUE TITLE
Update index_names of _InternalFrame when Index name changed

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#1210]
When doing something with `_InternalFrame`,

sometimes i feel a little confusing when such like below case.

```python
>>> idx = ks.Index([1, 2, 3])
>>> idx
Int64Index([1, 2, 3], dtype='int64')
>>> idx.name = 'koalas'
>>> idx
Int64Index([1, 2, 3], dtype='int64', name='koalas')
>>> idx.name
'koalas'
```
it is okay when i just use `idx` itself with new name 'koalas' like above,

but the problem is occurred when i want to work with `_InternalFrame`,

since the internal `index_names` has not changed like the below.
(to be honest, the `index_map` and other internal factors also have same behavior, but let's try to talk about `index_names` for now)

```python
>>> idx
Int64Index([1, 2, 3], dtype='int64', name='koalas')
>>> idx._internal.index_names
[None]  # i expect this should be [('koalas',)]
```

and it's also the reason for several bugs like #1206 ,

so i think it might be better we check about this behavior that we update internal information also (or keep the existing behavior) when related factors are changed.

**Comment by ueshin** [comment]
Yup, as I mentioned before (https://github.com/databricks/koalas/pull/1120#discussion_r357477773), `Index.rename` (or `@names.setter`) should be fixed.
I submitted the PR #1214.
