### ISSUE TITLE
ks.read_csv() - compression parameter ( *.csv.gz )

### ISSUE THREAD

**Issue by patryk-oleniuk** [databricks/koalas#1226]
I'm missing the CSV compression behavior from pandas:
```python
pd.read_csv('dataset.csv.gz', compression='gzip')
# is same as 
# (pandas is recognizing the compression automatically by the file extension)
pd.read_csv('dataset.csv.gz')
```
We can use one of the Spark `codec` implementations explained here:
https://stackoverflow.com/questions/40163996/how-to-save-a-dataframe-as-compressed-gzipped-csv

**Comment by HyukjinKwon** [comment]
What does `ks.read_csv` currently returns? Spark can detects the compression codec from the extension as well. Seems like a bug in Koalas if it doesn't work.

**Comment by patryk-oleniuk** [comment]
```python
ks.read_csv('my_data.csv.gz').to_pandas().info()
```
just returns an empty dataframe ..
```bash
<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Empty DataFrame
```

**Comment by HyukjinKwon** [comment]
thanks for confirmation!
