### ISSUE TITLE
Pandas accessor support

### ISSUE THREAD

**Issue by achapkowski** [databricks/koalas#1285]
Can you extend this api like pandas accessor pattern and custom types?

**Comment by HyukjinKwon** [comment]
@achapkowski can you elaborate it a bit more with examples written in pandas?

**Comment by achapkowski** [comment]
Sure please see: https://pandas.pydata.org/pandas-docs/stable/development/extending.html

**Comment by itholic** [comment]
I think this issue was resolved in #1617 .
