### ISSUE TITLE
Can't writeStream back to kafka

### ISSUE THREAD

**Issue by DaveOuds** [databricks/koalas#1297]
Hi all!
I'm consuming data from kafka, which I want to parse using koalas and afterwards produce it back to kafka. 
However, whenever I try to write a stream it wont work. Depending on the output mode of the stream I get one of two errors:

- Update/Append:
py4j.protocol.Py4JJavaError: An error occurred while calling o90.start.
: org.apache.spark.sql.AnalysisException: Expression(s): monotonically_increasing_id() is not supported with streaming DataFrames/Datasets;

- Complete:
py4j.protocol.Py4JJavaError: An error occurred while calling o90.start.
: org.apache.spark.sql.AnalysisException: Complete output mode not supported when there are no streaming aggregations on streaming DataFrames/Datasets
This is what my code looks like:
```python
import os
import databricks.koalas as ks

from pyspark.sql import SparkSession
from parse import parseData
from analyze import analyze


if __name__ == "__main__":
    bootstrapServers = os.environ.get("KAFKA_BOOTSTRAP_HOST", "127.0.0.1") + ":" + \
                       os.environ.get("KAFKA_BOOTSTRAP_PORT", "9092")

    # Create Spark Session 
    spark = SparkSession \
        .builder \
        .appName("PythonStructuredKafkaWordCount") \
        .getOrCreate()

    spark.sparkContext.setLogLevel("ERROR")

    # Consume data from Kafka of topic ra-ingest
    sdf = spark \
        .readStream \
        .format("kafka") \
        .option("kafka.bootstrap.servers", bootstrapServers) \
        .option("subscribe", "input-topic") \
        .option("failOnDataLoss", "false") \
        .option("truncate", "false") \
        .load() \
        .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)")

    # Convert S(park)DF to K(oalas)DF
    kdf = ks.DataFrame(sdf)

    # Convert K(oalas)DF back to S(park)DF
    new_sdf = kdf.to_spark()
  
    # Produce the data to kafka on topic ra-result
    query = new_sdf \
        .selectExpr("to_json(struct(*)) AS value") \
        .writeStream \
        .outputMode("complete") \
        .format("kafka") \
        .option("kafka.bootstrap.servers", bootstrapServers) \
        .option("topic", "output-topic") \
        .option("checkpointLocation", "/tmp/checkpoint") \
        .start()

    query.awaitTermination()
```

Am I doing something wrong or is Koalas not compatible with Spark Structured Streaming?

Best,

Dave

**Comment by ueshin** [comment]
Hi @DaveOuds, thanks for trying to use Koalas!
Unfortunately, Koalas doesn't support Structured Streaming so far.

**Comment by DaveOuds** [comment]
Hey @ueshin,
Noted, thanks for the quick feedback!
