### ISSUE TITLE
DataFrame.apply(func, axis=1) returns Series with unmatched index

### ISSUE THREAD

**Issue by patryk-oleniuk** [databricks/koalas#1307]
Env: koalas 0.27.0, Databricks DBR 6.2.

Consider the following code for pandas:
```python
df = pd.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5, 100.0, 101.0, 102.0],
              "car_id": ['A','A','A','B','B', 'C', 'C', 'C'], 
              "battery_charge": [100, 90, 80,100,90, 50, 60, 70]
              })

df2 = df.groupby("car_id").sum()

def calc_somthing(row) -> float:
  # doing some job per row
  return row['battery_charge']/(row['timestamp'] +1)

print(df2.apply(calc_somthing, axis=1))
```
That prints a series with the proper index: 
```bash
car_id
A    108.000000
B    126.666667
C      0.592105
dtype: float64
```
But if we do the same for koalas, we get a wrong index (and also wrong name, BTW):
```bash
0    126.666664
1    108.000000
2      0.592105
Name: 0, dtype: float32
```
That causes a lot of problems when merging that index with a new df, e.g. 
```python
df2["newcol"] = df2.apply(calc_somthing, axis=1)
``` 
The workaround is to always reset_index before apply.

**Comment by HyukjinKwon** [comment]
The problem here is that we can't tell what's the index given the type hints. So the index is being lost currently. Yes, `reset_index` is a nice workaround.

We should find a proper way to specify index type in the type hint... Let me at least document it for now.

**Comment by patryk-oleniuk** [comment]
Hmm, not sure why couldn't we just get the same index as the originating df?
Especially for `df.apply(func, axis=1)` that returns single type value per row.

**Comment by HyukjinKwon** [comment]
It's because the output index can be different from the original DataFrame:

```python
>>> import pandas as pd
>>> pd.DataFrame({'a': [1,2,3]}).apply(lambda _: pd.Series([1,2,3], index=["a", "b", "c"]))
   a
a  1
b  2
c  3
```

We can't detect the index type before the function execution. That's why it can return index type properly when the type hints are not specified (hence the type is inferred after executing the function once).

**Comment by HyukjinKwon** [comment]
Do you actually have any good idea to specify the index type? One possibility is we leverage https://docs.python.org/3/library/typing.html#typing.NamedTuple and have a reserved name to specify index type. I was thinking about supporting this but there would be no way for Python 3.5 to use because this is new from. Python 3.6

**Comment by patryk-oleniuk** [comment]
Eh, I feel like it's tricky, every solution I can think of is just so nasty and not convenient.. 

But anyway, I actually don't understand.. for `kdf.apply()` that is:
1. Row-based - `axis=1`
2. Apply function returns a single value (NOT `ks.Series` or `ks.DataFrame`)
We can just take the same index from the row that is processed, right? 
And then we can just make index parameter as not supported for that operation. 

I believe 90% of the applications of row-based apply are actually returning single value, I never in my life returned multiple values from row-based apply.. But that's just me.

Let me know if it makes sense.

**Comment by vkrot-exos** [comment]
Is there currently a clean way to add a dataframe column based on udf accepting rows (axis=1)
I also tried 
```
def func(row) -> int: return row['a'] 

df['col'] = df.apply(func, axis=1)
```
But it does not work with distributed index. Any suggestions how to implement without hopping back to spark and using `withColumn`? This to_spark/to_koalas() method bloat the code

Most likely there are other ways to do that, but quick search didn't reveal anything

**Comment by HyukjinKwon** [comment]
I think you should probably use [`pandas_wraps`](https://github.com/databricks/koalas/blob/d5e7a4ef6b9729290745948271ca9d3a0a3c4b32/databricks/koalas/typedef.py#L298-L382) for now; however, yes I think we should have a more elegant way.

**Comment by vkrot-exos** [comment]
@HyukjinKwon , yes, it works, thanks for lightning-fast reply!
