### ISSUE TITLE
Databricks runtime not supported

### ISSUE THREAD

**Issue by sorenmc** [databricks/koalas#1312]
I am currently trying to migrate a function utilizing pandas to koalas. I am using a databricks notebook to do this, but i receive an error when i try to import koalas, that seems like it is related to pandas. 

I run Databricks runtime 5.5 LTS (includes Apache Spark 2.4.3, Scala 2.11), and have tried to install koalas 3 different ways on the cluster including pip, dbutils and the inbuilt cluster package manager.
I have also tried playing around with different pandas and koalas versions to see if that would fix the issue.

```
dbutils.library.installPyPI("koalas")
dbutils.library.restartPython()
import databricks.koalas as ks
```

returns the traceback:

> ImportError: No module named 'pandas.core.dtypes'
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <command-3721303037916941> in <module>()
>       3 # import pandas.core.dtypes.common
>       4 print(pd.core)
> ----> 5 import databricks.koalas as ks
>       6 
>       7 raw_sa = os.getenv('RAW_STORAGEACCOUNT')
> 
> /usr/local/lib/python3.5/dist-packages/databricks/koalas/__init__.py in <module>()
>      36 assert_pyspark_version()
>      37 
> ---> 38 from databricks.koalas.namespace import *
>      39 from databricks.koalas.frame import DataFrame
>      40 from databricks.koalas.indexes import Index, MultiIndex
> 
> /usr/local/lib/python3.5/dist-packages/databricks/koalas/namespace.py in <module>()
>      32 from databricks import koalas as ks  # For running doctests and reference resolution in PyCharm.
>      33 from databricks.koalas.utils import default_session
> ---> 34 from databricks.koalas.frame import DataFrame, _reduce_spark_multi
>      35 from databricks.koalas.typedef import Col, pandas_wraps
>      36 from databricks.koalas.series import Series, _col
> 
> /usr/local/lib/python3.5/dist-packages/databricks/koalas/frame.py in <module>()
>      26 import pandas as pd
>      27 from pandas.api.types import is_list_like, is_dict_like
> ---> 28 from pandas.core.dtypes.inference import is_sequence
>      29 from pyspark import sql as spark
>      30 from pyspark.sql import functions as F, Column
> 
> ImportError: No module named 'pandas.core.dtypes'

**Comment by sorenmc** [comment]
Issue was caused by another package that had installed pandas==0.19 which is incompatible with koalas.

**Comment by itholic** [comment]
@sorenmc thanks for trying to report issue :)
