### ISSUE TITLE
Return type consistency in docs

### ISSUE THREAD

**Issue by sorenmc** [databricks/koalas#1332]
It is currently not transparent what the return type of a kolas dataframe / series is.

Take for example
[DataFrame.max()](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.max.html)

> Returns
maxscalar for a Series, and a Series for a DataFrame.

Returned type i receive is a pandas.Series

[Series.value_counts()](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.Series.value_counts.html)

> Returns
counts Series

Returned type i receive is a databricks.koalas.series.Series

I would like to suggest that it is made clear in the docs across all functions what the return type is in all cases

In both these cases it is unclear what type of series is returned

**Comment by HyukjinKwon** [comment]
I think we should match it to Koalas Series.

**Comment by sorenmc** [comment]
kdf.nunique still returns a pandas series

**Comment by HyukjinKwon** [comment]
Thanks for letting me know. Will fix soon
