### ISSUE TITLE
[Question] read_spark_io partition_col, numPartition values and head

### ISSUE THREAD

**Issue by Harshitg** [databricks/koalas#1341]
Code:
```
from pyspark import SparkContext, SparkConf, SQLContext

appName = "PySpark SQL Server Example - via JDBC"
master = "local[*]"
conf = SparkConf() \
    .setAppName(appName) \
    .setMaster(master) \
    .set("spark.driver.extraClassPath","c:/program files/sqljdbc/enu/mssql-jdbc-8.2.1.jre8.jar")\
    .set('spark.executor.memory', '4g') \
    .set("spark.sql.execution.arrow.enabled", True)

sc = SparkContext.getOrCreate(conf=conf)
sqlContext = SQLContext(sc)
spark = sqlContext.sparkSession

hostname = "LAPTOP"
database = "DB"
port = "1433"
table = "report_mart"
user = "google"
password  = "google"

query="SELECT TOP (500000) * FROM report_mart"

import databricks.koalas as ks
ks.set_option('compute.default_index_type', 'distributed')

conn = f"conn string;"
dataframe = ks.read_spark_io(query = query, format='JDBC',url = conn, index_col='date', partition_cols = 'date', numPartitions=10)
dataframe.head(1000)
```
Two questions here:
1. Even after specifying numPartitions and partition_cols, the explain function shows numPartitions as 1. Is there something amiss here?
`Relation[created_on#0,changed_on#1,id#2,instu_id#3,ecl_model_name#4,product_group#5,productgroup_desc#6,product_code#7,category#8,currency_code#9,counterparty_id#10,maturity_date#11,al_position#12,outstanding#13,outstanding_LCY#14,flag_revolving#15,limit_amount#16,notional_amount#17,deliquency_days#18,billing_account#19,start_date#20,facility#21,frr#22,account_status#23,... 50 more fields] JDBCRelation((SELECT TOP (500000) * FROM report_mart) SPARK_GEN_SUBQ_0) [numPartitions=1]`

2. dataframe.head(1000) takes close to a minute to print results. I am using Sypder, should i try another IDE? Some more information when checking spark jobs, when executing head command, toPandas() gets called (refer image below);
![image](https://user-images.githubusercontent.com/1675591/76539890-64b32700-64a7-11ea-98ae-cecc0aabf385.png)

**Comment by HyukjinKwon** [comment]
@Harshitg are you able to get multiple partitions when you use PySpark alone?

**Comment by Harshitg** [comment]
It would be seem, PySpark also shows numPartitions = 1.  Also any reason, why toPandas is getting executed here:
`
toPandas at C:\Users\XXXX\AppData\Roaming\Python\Python37\site-packages\databricks\koalas\internal.py:799`



```
jdbcDF = spark.read.format("jdbc") \
    .option("url", f"jdbc:sqlserver://xXXXxx;databaseName={database}") \
    .option("dbtable", table) \
    .option("user", user) \
    .option("password", password) \
    .option('driver', 'com.microsoft.sqlserver.jdbc.SQLServerDriver')\
    .option("numPartitions", 10)\
    .load()

```
```
== Parsed Logical Plan ==
Relation[created_on#901,changed_on#902,id#903,instu_id#904,ecl_model_name#905,product_group#906,productgroup_desc#907,product_code#908,category#909,currency_code#910,counterparty_id#911,maturity_date#912,al_position#913,outstanding#914,outstanding_LCY#915,flag_revolving#916,limit_amount#917,notional_amount#918,deliquency_days#919,billing_account#920,start_date#921,facility#922,frr#923,account_status#924,... 50 more fields] JDBCRelation(report_mart) [numPartitions=1]
```
