### ISSUE TITLE
minmax scaler not wotking with koalas dataframe

### ISSUE THREAD

**Issue by akashkumar398** [databricks/koalas#1353]
the below code resulting in error with koalas data frame but working fine with pandas data-frame 
# Scale the training feature

df = ks.DataFrame(df)
scaler = MinMaxScaler(feature_range=(0, 1)).fit(df)
train_scaled = scaler.transform(df)

ValueError: cannot copy sequence with size 1375219 to array axis with dimension 323

**Comment by HyukjinKwon** [comment]
`MinMaxScaler` seems from sklearn. The data does not live in client side so it will be impossible to use Koalas DataFrame with sklearn at this moment. The support is not in the plan currently.
