### ISSUE TITLE
Documentation: read_spark_io examples

### ISSUE THREAD

**Issue by Harshitg** [databricks/koalas#1372]
Read_spark_io currently has to_spark_io examples in the document. If by design, please close this.

`https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.read_spark_io.html#databricks.koalas.read_spark_io`

**Comment by HyukjinKwon** [comment]
Ah, thanks for checking the example. Yeah, it's just to show roundtrip between `to_spark_io` and `read_spark_io` :-)
