### ISSUE TITLE
to_delta and to_parquet are dropping the index

### ISSUE THREAD

**Issue by Hoeze** [databricks/koalas#1376]
Hi, I don't know if I made a mistake but `ks.DataFrame.to_delta` and `ks.read_delta` are dropping my index columns:
![grafik](https://user-images.githubusercontent.com/1200058/77863412-7e33cd00-7222-11ea-8980-304631d4fa18.png)

Is there a way to keep the index with the dataset?
Also, does this index actually give a performance boost compared to default Spark joins when I merge two large (terabyte range) datasets?

**Comment by HyukjinKwon** [comment]
Can you try to specify the index columns via `ks.read_detla(index_col=["configName", "start", "emd"])`?

**Comment by Hoeze** [comment]
Yes I tried, the columns are just missing.
