### ISSUE TITLE
Column assignment doesn't support type list

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#1403]
In Pandas, I can assign a column of type list (code works below with df). But in Koalas, I get `TypeError: Column assignment doesn't support type list`. Could this please be supported?

```
import pandas as pd
import databricks.koalas as ks

d = {'col1': [1], 'col2': [2]}
df = pd.DataFrame(data=d)
ks_df = ks.DataFrame(df)

df['Masked_Verbatim'] = ["hello"]
```

**Comment by vision360deg** [comment]
@brookewenig @HyukjinKwon, folks I have a question: shouldn't this also be supported when using `kdf.assign(Masked_Verbatim=["hello"])`
