### ISSUE TITLE
str.split(expand = True)

### ISSUE THREAD

**Issue by mks2192** [databricks/koalas#1421]
in dataframe string split into multiple columns is not available. what is alternative to that

**Comment by itholic** [comment]
Would you mind if you show me a little bit of your code examples?

I'm not sure what you exactly want to, but maybe the below way will work for you??

```python
>>> kdf = ks.DataFrame({'col1': ['A_1', 'A_2', 'A_3', 'A_4', 'A_5']})
>>> kdf
  col1
0  A_1
1  A_2
2  A_3
3  A_4
4  A_5

>>> kdf.map_in_pandas(lambda pdf: pdf.col1.str.split('_').str[0].to_frame()).col1
0    A
1    A
2    A
3    A
4    A
Name: col1, dtype: object
>>> kdf.map_in_pandas(lambda pdf: pdf.col1.str.split('_').str[1].to_frame()).col1
0    1
1    2
2    3
3    4
4    5
Name: col1, dtype: object
```

**Comment by mks2192** [comment]
Thanks. It was super helpful.

I believe its possible to use most of the pandas function using map_in_pandas ?

More specifically I was looking for this 

`Temp = kdf.map_in_pandas(lambda pdf:pdf.col1.str.split("_", expand = True))`

`Temp.columns  = ['S1', 'S2']`

```
Temp.head()

        S1     S2
0	A	1
1	A	2
3	A	4
2	A	3
4	A	5
```

**Comment by itholic** [comment]
@mks2192 

> I believe its possible to use most of the pandas function using map_in_pandas ?

It doesn't support for aggregation-like methods which needs operation through the whole dataset.

In this case, It's possible to use `map_in_pandas` because the `str.split` is applied to row by row.

It's really happy that It helped you :D

**Comment by ueshin** [comment]
I submitted a PR to support `expand` parameter with a restriction that `n` parameter must be a positive integer and the number of columns follows `n`.
Could you take a look at the PR #1432? Thanks!
