### ISSUE TITLE
Series.astype() does not not respect "truthyness" as in pandas

### ISSUE THREAD

**Issue by Callum027** [databricks/koalas#1430]
As you can see in the code below, I'm trying to convert a `str` to a `bool` below, as part of a quick way to see if a string is not `None`, empty or only consisting of whitespace. Since Koalas seems to hook directly into Spark's `Column.cast` and Java does not have the concept of "truthy" and "falsey" as in Python, the conversion fails and `None` is inserted instead.

This is a very tricky issue and might be very difficult to solve, so I'm not necessarily expecting a fix, but a note relating to the limitations of `Series.astype` in the documentation is probably necessary.

```python
import pandas as pd
import databricks.koalas as ks

print("koalas version: {}\n".format(ks.__version__))

data = ["hi", "hi ", " ", " \t", "", None]
pds = pd.Series(data)
kss = ks.Series(data)

print("pds:\n{}\n".format(pds.astype(bool)))
print("kss:\n{}\n".format(kss.astype(bool)))

print("pds (stripped):\n{}\n".format(pds.str.strip().astype(bool)))
print("kss (stripped):\n{}".format(kss.str.strip().astype(bool)))
```

Output:
```
koalas version: 0.31.0

pds:
0     True
1     True
2     True
3     True
4    False
5    False
dtype: bool

kss:
0    None
1    None
2    None
3    None
4    None
5    None
Name: 0, dtype: object

pds (stripped):
0     True
1     True
2    False
3    False
4    False
5    False
dtype: bool

kss (stripped):
0    None
1    None
2    None
3    None
4    None
5    None
Name: 0, dtype: object
```

**Comment by ueshin** [comment]
Thanks for the report!
That's a good point, and I guess we should follow pandas' behavior.
I'll be working on this.
