### ISSUE TITLE
kdf.head(10) vs df.limit(10).toPandas()

### ISSUE THREAD

**Issue by Lukas012** [databricks/koalas#1433]
I've got a PySpark DataFrame df.
`df = ...`
When I invoke:
`df.limit(10).toPandas()`
I get the result very quick.

When I invoke:
`kdf = df.to_koalas()`
`kdf.head(10)`

The results takes a very long time (if I even get it). Furthermore disk is filled until job get crashed due to "No space left on device".

Why? From my point of view both commands should do the same.

Environment:
- JupyterHub
- Spark 2.4.5
- Delta Lake

**Comment by HyukjinKwon** [comment]
The biggest difference between them are, Koalas assume the size of the data is large. Very large and does not fit in single note. So, it does distribute data, shuffle, and etc even for small datasets.
Can you share your full codes?

**Comment by Lukas012** [comment]
Of course:

```python
PARTITION_SIZE = 1000
os.environ["PYSPARK_PYTHON"] = "/opt/conda/envs/Umsatzdatenkategorisierung/bin/python"

spark = SparkSession \
    .builder \
    .master("spark://...:7077) \
    .config("spark.driver.memory", "4g") \
    .config("spark.logConf", True) \
    .config("spark.cores.max", "8") \
    .config("spark.executor.cores", "2") \
    .config("spark.executor.memory", "10g") \
    .config("spark.sql.execution.arrow.enabled", "true") \
    .config("spark.sql.execution.arrow.fallback.enabled", "true") \
    .appName("Koalas Test") \
    .getOrCreate()
# Apache Spark 2.4.x has a known issue (SPARK-25003) that requires explicit activation
# of the extension and cloning of the session. This will unnecessary in Apache Spark 3.x.
if spark.sparkContext.version < "3.":
    spark.sparkContext._jvm.io.delta.sql.DeltaSparkSessionExtension() \
        .apply(spark._jsparkSession.extensions())
    spark = SparkSession(spark.sparkContext, spark._jsparkSession.cloneSession())

sc = spark.sparkContext
sc.setLogLevel("WARN")
df = spark.read.format("delta").load("/mytestdata/raw5") # ~ 20 Columns, some are numbers, some are 4 - 5 words.
df = df.where(df.partition <= 300)
rowcount = df.count()
print("RowCount: " + str(rowcount)) # 20623197
# df = df.repartition(10000) # number of partitions don't seem to have an impact on the error, tried it with 100, 1000 and 10000
print("Num Partitions: " + str(df.rdd.getNumPartitions())) # 162
dfk = df.to_koalas()
dfk.head(10)
```
Spark History UI:
![grafik](https://user-images.githubusercontent.com/2796837/79760114-e193b500-831f-11ea-926a-1fd85dece2a9.png)

**Comment by ueshin** [comment]
Could you try to set default index to "distributed"?
I guess the default index might be the cause. Could you take a look at https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type and https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#specify-the-index-column-in-conversion-from-spark-dataframe-to-koalas-dataframe?

**Comment by Lukas012** [comment]
Thanks a lot @ueshin! That was it!
