### ISSUE TITLE
Image storage

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#1443]
![Screen Shot 2020-04-23 at 5 26 21 PM](https://user-images.githubusercontent.com/6477701/80076779-9f6cac80-8587-11ea-8c92-07d7b992733b.png)

![Screen Shot 2020-04-23 at 5 27 38 PM](https://user-images.githubusercontent.com/6477701/80076898-c2975c00-8587-11ea-9b2c-69c9729e9294.png)

![Screen Shot 2020-04-23 at 5 26 37 PM](https://user-images.githubusercontent.com/6477701/80076790-a1cf0680-8587-11ea-8b08-8dc694071ba0.png)

![Screen Shot 2020-04-23 at 5 26 41 PM](https://user-images.githubusercontent.com/6477701/80076795-a3003380-8587-11ea-8b73-186e4047f8c0.png)

![Screen Shot 2020-04-23 at 6 02 26 PM](https://user-images.githubusercontent.com/6477701/80080469-a518c100-858c-11ea-8a6c-fff469dd00a6.png)

![Screen Shot 2020-04-23 at 6 02 35 PM](https://user-images.githubusercontent.com/6477701/80080472-a6e28480-858c-11ea-9840-76452f73bacb.png)

PPTX: https://drive.google.com/open?id=19ruC0CuMQv70Slt-Spe8KgnF-Ot18dOr
Keynote: https://drive.google.com/open?id=1DNW-k0zR1P8KX9XMQ6QY6-7y3yY4mbsJ

**Comment by HyukjinKwon** [comment]
![Screen Shot 2020-06-18 at 9 51 45 AM](https://user-images.githubusercontent.com/6477701/84965259-63019b00-b149-11ea-8537-ab9a9e35802e.png)

**Comment by HyukjinKwon** [comment]
![Screen Shot 2020-06-18 at 10 03 12 AM](https://user-images.githubusercontent.com/6477701/84965839-f5566e80-b14a-11ea-84ed-9fcda6e69bcf.png)

**Comment by HyukjinKwon** [comment]
![Screen Shot 2020-06-18 at 10 11 48 AM](https://user-images.githubusercontent.com/6477701/84966301-2aaf8c00-b14c-11ea-9889-c13f0212edb7.png)

**Comment by itholic** [comment]
Cool
