### ISSUE TITLE
Is there something wrong with concat when axis=1?

### ISSUE THREAD

**Issue by Tom-Deng** [databricks/koalas#1450]
![image](https://user-images.githubusercontent.com/17919002/80329598-6d07cb80-8875-11ea-9208-a3b571dd292a.png)

tmp3.shape is expected to be (195638, 32)

dtype info
![image](https://user-images.githubusercontent.com/17919002/80329737-d1c32600-8875-11ea-99d7-3fd3c6db21c5.png)

**Comment by HyukjinKwon** [comment]
@Tom-Deng, do you mind showing the results of `concat(tmp_list[0].head(10), tmp_list[1].head(10))`? It will be helpful to show `tmp_list[0].head(10)` and `tmp_list[1].head(10)`.

**Comment by Tom-Deng** [comment]
tmp_list[0].head(10)
![image](https://user-images.githubusercontent.com/17919002/80332754-5023c600-887e-11ea-812b-e47f81bf3a8e.png)
tmp_list[1].head(10)
![image](https://user-images.githubusercontent.com/17919002/80332829-924d0780-887e-11ea-98e4-cc3e5530e6a5.png)


 csv file
[csv_file.zip](https://github.com/databricks/koalas/files/4537406/csv_file.zip)

**Comment by HyukjinKwon** [comment]
Can you show your full codes? It produces the same results in my side:

```python
import databricks.koalas as ks
tmp0 = ks.read_csv("tmp_list_0.csv")
tmp1 = ks.read_csv("tmp_list_1.csv")
ks.concat([tmp0, tmp1], axis=1).shape
```
```
(43018, 32)
```

```python
import pandas as pd
tmp0 = pd.read_csv("tmp_list_0.csv")
tmp1 = pd.read_csv("tmp_list_1.csv")
pd.concat([tmp0, tmp1], axis=1).shape
```
```
(43018, 32)
```

**Comment by Tom-Deng** [comment]
reference:  https://github.com/szilard/benchm-ml

The wrong place:
![image](https://user-images.githubusercontent.com/17919002/80336098-dc3aeb00-8888-11ea-83b8-b643c76edc2f.png)

full code
[github.tar.gz](https://github.com/databricks/koalas/files/4537609/github.tar.gz)

version info
![image](https://user-images.githubusercontent.com/17919002/80336287-76029800-8889-11ea-9c65-62012153cbbf.png)

**Comment by HyukjinKwon** [comment]
@Tom-Deng, can you post a copy-and-paste-able codes? It's a bit difficult for me to guess and write the codes to reproduce your case.

**Comment by Tom-Deng** [comment]
Code and used data are in compressed package "github.tar.gz" with last comment.

**Comment by ueshin** [comment]
I found out the reason. It's because you created the `d1` by `d1 = d1a.append(d1b)` which will contain duplicated index values.
So far Koalas uses join on index columns to implement `concat(..., axis=1)`, so if there are duplicated values, it will produce more rows than the original row number.

Could you use `d1 = d1a.append(d1b, ignore_index=True)` as a workaround?

**Comment by Tom-Deng** [comment]
> I found out the reason. It's because you created the `d1` by `d1 = d1a.append(d1b)` which will contain duplicated index values.
> So far Koalas uses join on index columns to implement `concat(..., axis=1)`, so if there are duplicated values, it will produce more rows than the original row number.
> 
> Could you use `d1 = d1a.append(d1b, ignore_index=True)` as a workaround?

This modification is valid.
