### ISSUE TITLE
Python Kernel with remote Spark cluster

### ISSUE THREAD

**Issue by user919lx** [databricks/koalas#1451]
I have a JupyterHub on a server,and my Spark clustes are on other servers. They comunicate with Jupyterhub by sparkmagic and livy.

It works fine in PySpark Kernel by sparkmagic as I install koalas in PySpark environment.

But I can't make koalas work in JupyterHub origin Python kernel, error info:`ImportError: Unable to import pyspark - consider doing a pip install with [spark] extra to install pyspark with pip `. 

Jupyterhub isn't on Spark cluster servers, so how to make Python Kernel work with koalas?
I really want to show dataframe in a pretty style, which can be done in Python kernel but can't in PySpark Kernel.

**Comment by HyukjinKwon** [comment]
Are you able to install PySpark? Koalas is dependent on PySpark, and it's required.

**Comment by user919lx** [comment]
I install pyspark on jupyterhub,but I can't query hive table because jupyterhub's server isn't spark cluster

**Comment by HyukjinKwon** [comment]
I am not aware of how sparkmagic and JupyterHub work. If that's just codes being sent from jupyterhub to the spark cluster, you might have to install Koalas in the cluster.

**Comment by user919lx** [comment]
This is the architecture of sparkmagic.sparkmagic wrap api request to livy,it send code through livy to spark cluster,and recive results.
![architecture](https://github.com/jupyter-incubator/sparkmagic/raw/master/screenshots/diagram.png)

I have installed koalas in spark cluster, and it's work well in pyspark kernel by sparkmagic.

My problem is that  I want to run koalas in python3 kernel (for displaying a pretty dataframe).It run code on jupyter server, which is not a spark cluster. so when I try to run codes about spark,like querying hive table , there will be an error.Because the system can't execute spark code.

**Comment by HyukjinKwon** [comment]
In the codes, can you run `from pyspark.sql import SparkSession` and get the Spark session by `SparkSesion.builder.getOrCreate()`?

I assume you use Livy as a Yarn cluster mode(?). If you run Livy as a client mode, Livy should be able to import both PySpark and Koalas in the node where Livy is installed.

**Comment by HyukjinKwon** [comment]
I am leaving this closed due to no feedback.
