### ISSUE TITLE
Add Spark JDBC read 

### ISSUE THREAD

**Issue by sebastianvermaas** [databricks/koalas#1456]
For enterprise use, I'd like to poll the extension of read methods to JDBC, given that drivers are available in the Spark Context. 

**Current Solutions**
```python
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

import databricks.koalas as ks

jdbc_options = dict()
jdbc_options["driver"] = "<my-driver>"

# JDBC
df = ks.DataFrame(
    spark.read.format("jdbc").options(**jdbc_options).option("dbtable", "<sql>").load()
)

# Snowflake
sf_options = dict()
df = ks.DataFrame(
    spark.read.format("net.snowflake.spark.snowflake")
    .options(**sf_options)
    .option("dbtable", "<sql>")
    .load()
)
```

**New Solution**
```python 
import databricks.koalas as ks

df = ks.read_jdbc(dbtable="<sql>", driver="<my-driver>", **options)

```

**Comment by ueshin** [comment]
I guess you can use `ks.read_sql_table()` (https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.read_sql_table.html).
Or `ks.read_spark_io()` for the general purpose (https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.read_spark_io.html).

**Comment by sebastianvermaas** [comment]
Never noticed the read_sql_table, thank you!

**Comment by vaibhavsingh007** [comment]
Hi, how do we specify the jdbc driver in ks.read_sql_table()?

**Comment by HyukjinKwon** [comment]
e.g)

```python
df = ks.read_spark_io(format=SNOWFLAKE_SOURCE_NAME, query="query", **sfOptions)
```

**Comment by vaibhavsingh007** [comment]
Thanks @HyukjinKwon I did check that doc before though it doesn't say how to pass the driver. Should I just create a separate Spark session with driver config (spark.jars) and Koalas will detect that Spark session automatically instead of creating its own?

**Comment by vaibhavsingh007** [comment]
Yes, that seems to work. I was able to create ks dataframe using OP's method above: 

```
df = ks.DataFrame(
    spark.read.format("net.snowflake.spark.snowflake")
    .options(**sf_options)
    .option("dbtable", "<sql>")
    .load()
)
```
