### ISSUE TITLE
ImportError: No module named 'numpy.testing.nosetester'

### ISSUE THREAD

**Issue by hanman2016** [databricks/koalas#1458]
I got this error after installing koalas library on my cluster.
I tried importing numpy library then this encountered.
Please help to sort it out

**Comment by hanman2016** [comment]
At cluster level error after installing coalas on cluster.
Below error thrown in driver log. command not able to execute.

ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/databricks/python/lib/python3.5/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

**Comment by HyukjinKwon** [comment]
Are you able to import numpy, e.g. `from numpy.testing.nosetester import import_nose`? Seems this is not a Koalas issue definitely.
