### ISSUE TITLE
Adding DataFrame.values?

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#146]
There has been discussion to add `DataFrame.values`, which in pandas returns a `numpy` array. I am of the opinion that we should not add this API, but other, more recent substitutes, for the following reasons:

This property is a low-level API that is meant to directly provide a view of the content of the dataframe, in the form of a numpy array. The expectation from the user and the developer (ex: pandas-profiling, seaborn) is that the result will be a numpy or numpy-like object. Spark does not provide low-level, high-performance APIs for representing arrays, so it would force the materialization of the data.

This behaviour is both unexpected from users, and not recommended by pandas itself, which has a warning in the documentation. Instead, I recommend we add the following APIs, which in practice also force a collect:
 - `to_numpy()`
 - `to_pandas()` (already implemented)
These functions have clear meaning that they convert data, and that they will return arrays of data or pandas dataframes. This is more clear to me than adding the naked `.values` property.

**Comment by thunterdb** [comment]
@garawalid what are your thoughts? I think that `to_numpy()` will be what you want.

**Comment by garawalid** [comment]
@thunterdb  I totally agree with you! `to_numpy` is better and gives an idea that result will be numpy array.

**Comment by rxin** [comment]
I agree -- to_numpy is better!
