### ISSUE TITLE
read_csv appear ：TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by mao-ouyang** [databricks/koalas#1464]
When will index_col be equal to Flase?
This problem is caused by index _col equal to False. At present, the judgment that increasing index_col is not equal to False temporarily solves the problem.
![image](https://user-images.githubusercontent.com/46299753/81151188-52d79700-8fb3-11ea-92e1-4ae02a0b2116.png)
![image](https://user-images.githubusercontent.com/46299753/81151419-8e726100-8fb3-11ea-90c6-4314f453d3f9.png)

Normal after modification：
![image](https://user-images.githubusercontent.com/46299753/81151843-f628ac00-8fb3-11ea-8963-a56bab904c03.png)
![image](https://user-images.githubusercontent.com/46299753/81152244-5a4b7000-8fb4-11ea-8fd8-1dfe5f0ffead.png)

**Comment by HyukjinKwon** [comment]
`index_col` should be either a string or a list of strings. it won't be a bool. I think we can make a fix to show a better error message with `ValueError`, though.

**Comment by mao-ouyang** [comment]
If the data index_col is empty, the user will have this problem by using the parameter index_col = False

**Comment by HyukjinKwon** [comment]
If you want `index_col` to be empty, you can specify `None` instead. We can fix it to throw a better error message, I guess.
