### ISSUE TITLE
get_dummies uses the prefix parameter whose type is dict return KeyError

### ISSUE THREAD

**Issue by Tom-Deng** [databricks/koalas#1469]
Use get_dummies demo with prefix  and columns
![image](https://user-images.githubusercontent.com/17919002/81365829-c5638680-911b-11ea-8896-cdfb8f3cc68d.png)
pandas result like this:
![image](https://user-images.githubusercontent.com/17919002/81365863-e1672800-911b-11ea-901d-9ab3467ce93b.png)

**Comment by HyukjinKwon** [comment]
cc @itholic can you take a look when you're available?

**Comment by itholic** [comment]
@HyukjinKwon Sure, leave it to me. I'll take it.

**Comment by itholic** [comment]
This is because It didn't consider about `dict` as a `prefix` type.

I just created a PR to fix this.
