### ISSUE TITLE
Cannot use Databricks `display ()` with koalas DataFrame

### ISSUE THREAD

**Issue by dennyglee** [databricks/koalas#150]
Currently using `koalas==0.1.0` and cannot use the `display()` command.

```
# Use `read_csv` to read the CSV file
kdf = koalas.read_csv(dbfs_path)

# Use Pandas `.head` syntax
display(kdf.head())
```

results in the error message:
```
Exception: Cannot call display(<class 'databricks.koalas.frame.DataFrame'>)`.
```

The current workaround for this issue is to convert the `koalas` DataFrame to a `pandas` DataFrame and then `display()` will work.

**Comment by rodneyjoyce** [comment]
Yes, I have the same issue- the example in the blob post does not work when copied and pasted:  

display(ks.get_dummies(data))

Result:  Exception: Cannot call display(<class 'databricks.koalas.frame.DataFrame'>)

**Comment by sadikovi** [comment]
Should be resolved now.

**Comment by HyukjinKwon** [comment]
Seems still not working.

**Comment by HyukjinKwon** [comment]
Actually, @dennyglee, I tested against the current upstream:

```python
In [9]: display(kdf.head())
Empty DataFrame
Columns: [a, b, c]
Index: []
```

Seems fine.

**Comment by dennyglee** [comment]
For `koalas==0.3.0` when using the Databricks `display()`, I get the following:

```
# Use `read_csv` to read the CSV file
kdf = ks.read_csv(dbfs_path)

# Use Pandas `.head` syntax
display(kdf.head())
```

with the output being:
```
Exception: Cannot call display(<class 'databricks.koalas.frame.DataFrame'>)
```

Note, I can run:
```
kdf.head()

-- 
Out[4]: 
   ID     crim    zn  indus  chas  ...  tax  ptratio   black  lstat  medv
0   1  0.00632  18.0   2.31     0  ...  296     15.3  396.90   4.98  24.0
1   2  0.02731   0.0   7.07     0  ...  242     17.8  396.90   9.14  21.6
2   4  0.03237   0.0   2.18     0  ...  222     18.7  394.63   2.94  33.4
3   5  0.06905   0.0   2.18     0  ...  222     18.7  396.90   5.33  36.2
4   7  0.08829  12.5   7.87     0  ...  311     15.2  395.60  12.43  22.9
```

**Comment by HyukjinKwon** [comment]
Yea, sorry, this happens. I just verified it.

**Comment by HyukjinKwon** [comment]
but I do think this is specific to `display()` method, not Koalas

**Comment by dennyglee** [comment]
In retrospect, that's fair as this really has to do with `display()` recognizing a `koalas` DataFrame in the same way it already recognizes a `spark` or `pandas` DataFrame.

**Comment by rxin** [comment]
We need to fix Databricks' display to take into account a Koalas DataFrame.

**Comment by HyukjinKwon** [comment]
Let me leave this one closed for now as it doesn;t looks an issue in Koalas but I will track this until it's fixed.

**Comment by joneschrisg** [comment]
With latest Databricks upstream, you don't need `display()`: just evaluating a koalas DataFrame should render a nice HTML representation.  But the explicit calls to `display()` should do something useful too.
