### ISSUE TITLE
Enforce type annotation in the code base

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#151]
Python can get very difficult to understand for large projects, and one of the main reasons for that is the lack of explicit & static typing. We can mitigate that with type annotations. I think we should update the existing code and enforce that in Koalas.

This is important to do before more contributors come to the project.

**Comment by HyukjinKwon** [comment]
Actually, we enforced that the given type hints are correct at least. Do we target to write all type hint against this issue? if so I think we should delay after 0.7.0 ....

**Comment by itholic** [comment]
I think we can close this since we added type annotation to almost all important API files such as `frame.py`, `series.py`, `indexes.py`, etc.

WDYT, @HyukjinKwon , @ueshin and @xinrong-databricks ??

**Comment by HyukjinKwon** [comment]
We already finished typing and plan to finish most of them in Q3. Let's open a JIRA in Apache Spark to document contributors to do the typing.

**Comment by HyukjinKwon** [comment]
Contribution guides are all done in PySpark documentation side too. Finally I am tentatively closing this.
