### ISSUE TITLE
Inline method docs, rather than using "derived_from"

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#152]
The problem is that the equivalent methods in pandas usually have a lot of arguments, and some of them don't make to support in Koalas or are temporarily not supported. Showing those in the examples are simply confusing to end users when they read the docs. We should just inline the docs. We can however create them using pandas docs as the baseline.

Here is an initial list:

```
frame.py-    def iteritems(self):
frame.py-    def to_html(self, buf=None, columns=None, col_space=None, header=True, index=True,
frame.py-    def isnull(self):
frame.py-    def notnull(self):
frame.py-    def toPandas(self):
frame.py-    def assign(self, **kwargs):
frame.py-    def dropna(self, axis=0, how='any', thresh=None, subset=None, inplace=False):
frame.py-    def drop(self, labels, axis=0, errors='raise'):
frame.py-    def get(self, key, default=None):
frame.py-    def pipe(self, func, *args, **kwargs):

series.py-    def rename(self, index=None, **kwargs):
series.py-    def reset_index(self, level=None, drop=False, name=None, inplace=False):
series.py-    def isnull(self):
series.py-    def notnull(self):
series.py-    def dropna(self, axis=0, inplace=False, **kwargs):
series.py-    def head(self, n=5):
series.py-    def value_counts(self, normalize=False, sort=True, ascending=False, bins=None, dropna=True):
```

**Comment by rxin** [comment]
cc @thunterdb what do you think about this one?

**Comment by thunterdb** [comment]
I totally agree, we should not need to use derived_from. Personnally, I would rather have (slightly misleading) doc from pandas for now rather than no doc at all.

This is a great starter task if someone wants to do it on their favorite functions.

**Comment by rxin** [comment]
A lot of them are probably blocked by https://github.com/databricks/koalas/issues/168

**Comment by abishekganesh72** [comment]
Hi let me know if I can be of any help to for this

**Comment by thunterdb** [comment]
@abishekganesh72 you are welcome to help. Here is an example, taking `Series.value_counts`:
It would be great to take the documentation from pandas:
https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/core/base.py#L1222
and copy the docstring into `series.py`:
https://github.com/databricks/koalas/blob/master/databricks/koalas/series.py#L321

Some changes will have to be made:
 - removing the argument that are not available yet (like `bins`) and making note in the doc that it is not supported yet
 - removing the example that uses `bins`
 - making sure that the tests in the docstring run

I suggest starting with one function to build confidence in the process. Later we can batch multiple functions at once.

**Comment by abishekganesh72** [comment]
Sounds good, let me take a crack at it.

**Comment by abishekganesh72** [comment]
@thunterdb  I am trying to push my code the repo but I am not authorized to do so I guess. Kindly let me know how am I supposed to push my changes to repo.

**Comment by rxin** [comment]
You will need to fork the repository first
https://help.github.com/articles/fork-a-repo

And then push to a branch in your fork.

And then create a pull request against this repository so we can review it.

**Comment by abishekganesh72** [comment]
Thanks for the info. Let me do it that way.

**Comment by shril** [comment]
@rxin @thunterdb I would like to take this up as well.

**Comment by rxin** [comment]
@shril please do. We need all the help we can get. Thanks!

**Comment by ezwiefel** [comment]
@rxin @thunterdb Hope you're still looking for help. I'm going to submit a PR for some of the `Series` functions (starting with `head`).

**Comment by abishekganesh72** [comment]
@ezwirfel, Thanks for the help but I am working on the methods in series.py.

**Comment by ezwiefel** [comment]
@abishekganesh72, Sounds good - thanks!

**Comment by HyukjinKwon** [comment]
Go ahead guys!

**Comment by nitlev** [comment]
Hey, I started working on Dataframe.pipe if that's okay. I'll have to change a bit the docstring as the one used in pandas won't make the tests pass, but I think I can get something working soon.

**Comment by rxin** [comment]
@nitlev please do. Thanks for working on it.
