### ISSUE TITLE
Apply Spark Column operations directly on a Series

### ISSUE THREAD

**Issue by Callum027** [databricks/koalas#1523]
On issue #1492, I noticed it was noted the following operation was possible on a column of a Koalas `DataFrame`:
```python
>>> import databricks.koalas as ks
>>> df = ks.DataFrame(["example"], columns=["column"])
>>> from pyspark.sql import functions as F
>>> df["column"] = F.trim(F.upper(F.col("column")))
>>> df
    column
0  EXAMPLE
```

By any chance, is there currently a way to apply Spark SQL/Column functions to a Koalas `Series`? I can imagine it looking something like so:
```python
>>> import databricks.koalas as ks
>>> import pyspark.sql.functions as F
>>> kss = ks.Series(["example"])
>>> kss.apply(F.trim(F.upper(kss.spark_column)))
0    EXAMPLE
Name: 0, dtype: object
```

**Comment by itholic** [comment]
Hi, @Callum027 . Thanks for the attention to the Koalas :)

Unfortunately, I think there is no way to apply Spark function to the `Series` directly for now.

we can brutally workaround using `to_frame()` like the below:
(I guess maybe you already know this way and might not be an exactly way what you want)

```python
>>> import databricks.koalas as ks
>>> import pyspark.sql.functions as F
>>> kss = ks.Series(["example"])
>>> kdf = kss.to_frame()
>>> kdf['0'] = F.trim(F.upper(F.col('0')))
>>> kdf['0']
0    EXAMPLE
Name: column, dtype: object
```

@HyukjinKwon , @ueshin Could you look at this when available if there is any other way maybe that I missed ??

**Comment by HyukjinKwon** [comment]
Maybe we should have a method called something like `spark_apply` in both DataFrame and Series ..

**Comment by Callum027** [comment]
So something like this?
```python
# DataFrame
kdf.spark_apply(F.trim(F.upper(F.col("column"))))
# Series
kss.spark_apply(F.trim(F.upper(kss.spark_column)))
```
I think that's a great idea, and would solve what I'm trying to do without having to convert the DataFrame (or worse, a Series...) to a Spark DataFrame.

**Comment by itholic** [comment]
Looks cool. or maybe like this?

```python
# DataFrame
kdf.spark_apply(F.upper).spark_apply(F.trim)
# Series
kdf["column"].spark_apply(F.upper).spark_apply(F.trim)
kss.spark_apply(F.upper).spark_apply(F.trim)
```

or

```python
def upper_trim(kss):
    return F.trim(F.upper(kss.spark_column))

kdf.spark_apply(upper_trim)
```

**Comment by Callum027** [comment]
If there would be no efficiency issues resulting from calling `spark_apply` (or really, `sdf.withColumn` or whatever it is behind the scenes) multiple times, then either (or both!) seem like a good format to go with!

**Comment by Callum027** [comment]
I think something like this would be great as well, if possible? Just throwing ideas out there.
```python
>>> kdf = ks.DataFrame({"col1": [["cat", "dog"]], "col2": [["cat", "rabbit"]]})
>>> kdf.spark_apply(F.array_union(kdf["col1"].spark_column, kdf["col2"].spark_column))
0    ["cat", "dog", "rabbit"]
Name: column, dtype: object
```

**Comment by HyukjinKwon** [comment]
I opened a PR. The idea is basically to collect everything related to Spark itself to `.spark` namespace. This specific issue could be worked done via:

```python
>>> import databricks.koalas as ks
>>> import pyspark.sql.functions as F
>>> kss = ks.Series(["example"])
>>> kss.spark.transform(lambda s: F.trim(F.upper(s)))
0    EXAMPLE
Name: 0, dtype: object
```

Given that the current APIs in Pandas such as `Series.transform`, `Series.apply`, `DataFrame.apply`, `DataFrame.transform`, etc, I named it `Series.spark.transform` and made the usage similar. Also, it shares the same limitation.

```python
>>> import databricks.koalas as ks
>>> import pyspark.sql.functions as F
>>> kss = ks.Series(["example"])
>>> kss.spark.transform(lambda s: F.trim(F.upper(s)))
0    EXAMPLE
Name: 0, dtype: object
```

**Comment by Callum027** [comment]
Does that include the limitation where the output has to be the same type as the input? I'm planning on using it to tokenize a string into a list of strings, so if there was a way to be able to use a function that produces a type that is different to the input, that would be really great.

**Comment by HyukjinKwon** [comment]
That one will have to be an API called `apply`. Let me take a look for that case as well.

**Comment by Callum027** [comment]
I saw #1535 and thought I should elaborate on what I was wanting to do.

Say I have a UDF called `tokenize`, that takes in a string and turns it into a list of token strings:
```python
import pyspark.sql.functions as F
import pyspark.sql.types as T
@F.udf(T.ArrayType(T.StringType()))
def tokenize(input_str):
    return list(set(input_str.split()))
```

So given an input like this:
```python
>>> import databricks.koalas as ks
>>> kss = ks.Series(["example example 1", "example string 2"])
>>> kss
0    example example 1
1    example string 2
Name: 0, dtype: object
```

I would want the following output:
```python
>>> kss.spark.apply(lambda s: tokenize(s))
0    ['example', '1']
1    ['example', 'string', '2']
Name: 0, dtype: object
```

This operation would change the type of the data, but since it does an operation on the values themselves without removing or adding anything, generating a new index shouldn't be required.

Would this be more realistic?

**Comment by HyukjinKwon** [comment]
Ah, ^ this case will work with `kser.transform`. What I meant of the length is the size of the whole series instead of each value.

**Comment by HyukjinKwon** [comment]
tada

```python
>>> kss.spark.transform(lambda s: tokenize(s))
0            [1, example]
1    [2, string, example]
Name: 0, dtype: object
```

**Comment by HyukjinKwon** [comment]
Let me leave it per https://github.com/databricks/koalas/pull/1530 then ..

**Comment by Callum027** [comment]
Thanks for getting this done so quickly, @HyukjinKwon ! I really appreciate the effort!
