### ISSUE TITLE
ks.sql not respecting pd.options.display.max_rows

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#1555]
When running ks.sql("SELECT * from {ks_df}"), I was expecting to get a truncated output based on pd.options.display.max_rows (set to 60). However, it displayed hundreds of records as output.

Can we adjust this to use pd.options.display.max_rows to limit the number of records displayed?

**Comment by ueshin** [comment]
You can use `ks.options.display.max_rows` instead of `pd...`.
```py
ks.options.display.max_rows = 60
```

**Comment by brookewenig** [comment]
Fascinating! I didn't realize the default was so different for pandas and koalas. 

ks.options.display.max_rows defaults to 1000, and pd.options.display.max_rows defaults to 60.
