### ISSUE TITLE
Bug import

### ISSUE THREAD

**Issue by GCPBigData** [databricks/koalas#1579]
https://colab.research.google.com/drive/1CmWY3mKhhlnLEy7G9yGAoIMORwrj3T9R?usp=sharing

import databricks.koalas as ks

ImportError                               Traceback (most recent call last)
<ipython-input-20-0376b7c81ae0> in <module>()
----> 1 import databricks.koalas as ks

6 frames
/content/spark-3.0.0-preview2-bin-hadoop3.2/python/pyspark/sql/utils.py in require_minimum_pyarrow_version()
    175     if LooseVersion(pyarrow.__version__) < LooseVersion(minimum_pyarrow_version):
    176         raise ImportError("PyArrow >= %s must be installed; however, "
--> 177                           "your version was %s." % (minimum_pyarrow_version, pyarrow.__version__))
    178     if os.environ.get("ARROW_PRE_0_15_IPC_FORMAT", "0") == "1":
    179         raise RuntimeError("Arrow legacy IPC format is not supported in PySpark, "

ImportError: PyArrow >= 0.15.1 must be installed; however, your version was 0.14.1.

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by HyukjinKwon** [comment]
Thanks, @GCPBigData. The error is actually from PySpark side so Koalas can't control it.
