### ISSUE TITLE
IllegalArgumentException when replacing strings in series

### ISSUE THREAD

**Issue by gclendenning** [databricks/koalas#1606]
First of all, koalas is awesome :)

I'm trying to extract substrings from a Series of text. However, these substrings aren't always present, resulting in "NaN" (the string not the float). I would like to convert these to np.nan or None so that I can use ks.fillna. However I get an IllegalArgumentException

> Py4JJavaError: An error occurred while calling o410.select.
: java.lang.IllegalArgumentException: requirement failed: All input types must be the same except nullable, containsNull, valueContainsNull flags. The input types found are
	StringType
	DoubleType

Here is a minimal example to reproduce the error:

```python
import databricks.koalas as ks

titles = ks.Series(['The Duck Goes Here', 'The Tower Commission Report', 'US royalties (USD)', 'UK royalties (GBP)'])
titles_parsed = titles.where(titles.str.endswith(')')).str.split().str.get(-1).str.strip('()')

# titles_parsed is
# 0    NaN
# 1    NaN
# 2    USD
# 3    GBP
# Name: 0, dtype: object

print(type(titles_parsed.loc[0])) # <class 'str'>

replaced = titles_parsed.replace('NaN', None)
print(replaced)

# This gives the error above
```
Do you have any suggestions on how I can work around this?

I've also attached the full stack trace below (please let me know if you need me to run any tests). I'm also using

Python version: 3.7.6
Koalas version: 1.0.0

[koalas_nan_replace_stack_trace.txt](https://github.com/databricks/koalas/files/4813707/koalas_nan_replace_stack_trace.txt)

**Comment by itholic** [comment]
Let me close this since it works well in latest Koalas.

```python
>>> replaced = titles_parsed.replace('NaN', None)
>>> print(replaced)
0    None
1    None
2     USD
3     GBP
dtype: object
```
