### ISSUE TITLE
What does  API coverage mentioned in the 1.0.0 version released reaches 75% actually mean？

### ISSUE THREAD

**Issue by chi2liu** [databricks/koalas#1611]
The API coverage mentioned in the 1.0.0 version released reaches 75%. 
What specific classes and methods does API coverage count here?
For example, the API coverage of DataFrame class includes only public methods and attributes, not private methods？

**Comment by HyukjinKwon** [comment]
Yup, private methods are not counted, of course. There are API lists in pandas at, for example, https://pandas.pydata.org/docs/reference/frame.html.

It means the API counts in DataFrame, Series and Index which are main APIs in pandas. Other factors are not counted for simplicity. For example, plotting has 90% coverage but it wasn't counted.

**Comment by chi2liu** [comment]
> Yup, private methods are not counted, of course. There are API lists in pandas at, for example, https://pandas.pydata.org/docs/reference/frame.html.
> 
> It means the API counts in DataFrame, Series and Index which are main APIs in pandas. Other factors are not counted for simplicity. For example, plotting has 90% coverage but it wasn't counted separately. Groupby and Rolling were not counted either where Koalas has a high coverage.

Thanks!
