### ISSUE TITLE
Series.droplevel

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#1615]
Implement `Series.droplevel`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.droplevel.html

**Comment by ueshin** [comment]
This will be able to be done at the same time as #1614.

**Comment by ueshin** [comment]
This might be able to be done at the same time as #1614.

**Comment by HyukjinKwon** [comment]
@itholic are you interested in this?

**Comment by itholic** [comment]
@HyukjinKwon Yup, I'm gonna take this one.
