### ISSUE TITLE
Koalas very slow compared to pandas

### ISSUE THREAD

**Issue by Lukas012** [databricks/koalas#1618]
Hello, 

we want to use koalas. We did some tests and compared it to pandas. However, koalas was in all cases significantly slower. We tried koalas in local[32]-Mode (but the results are similar in our distributed spark cluster):

Environment:
Koalas 1.0.1
PySpark 2.4.5 (similar results with PySpark 3.0.0)

Following Code:
```python
os.environ["PYSPARK_PYTHON"] = "/opt/conda/envs/MY_ENV/bin/python"
spark = SparkSession \
        .builder \
        .master("local[32]") \
        .config("spark.executor.memory", "20g") \
        .config("spark.driver.memory", "50g") \
        .config("spark.sql.execution.arrow.enabled", "true") \
        .config("spark.sql.execution.arrow.fallback.enabled", "true") \
        .config("spark.cores.max", "32") \
        .appName("MY_APP") \
        .getOrCreate()
ks.set_option('compute.default_index_type', 'distributed')
```

We made these performance comparision with koalas and pandas:
```python
NROWS = 1000000000
```
From now on we executed the code with
```python
import pandas as ks
#and
import databrick.koalas as ks
```

Performance:
```python
t = time()
data = ks.DataFrame(columns=['col'], data=np.random.randn(NROWS))
print(time()-t)
```
Pandas: 3,9 s
Koalas: 12,19 s

```python
t = time()
print(data['col'].sum())
print((time()-t))
```
Pandas: 0,87 s
Koalas: 3,7 s

```python
t = time()
print(data.describe())
print((time()-t))
```
Pandas: 8,13 s
Koalas: 8,1 s

```python
t = time()
x = len(data.loc[data['col'] == 1])
print(x)
print((time()-t))
```
Pandas: 0,43 s
Koalas: 2,3 s

Can you give us some hints, why koalas is so slow in our test with 100 Million Random Numbers?

**Comment by ueshin** [comment]
pandas can run much faster if the data fits within a single node, whereas Spark has an overhead of the distribution.
Could you try with larger dataset which doesn't fit within a single node? Koalas will still run with it.

**Comment by Lukas012** [comment]
We reconstructed the code above using plain Spark 3. There was no significant difference between koalas and Spark regarding the time. However spark / koalas needed much much much more CPU resources than plain pandas (x10 - 20 in my feeling). But since this is no koalas issue, this issue is closed. 

By adding more columns (strings and numbers) to the 100-million-row-dataframe and applying complexer transformations (string operations, group bys,...) koalas could outperform pandas.

**Comment by HyukjinKwon** [comment]
Thanks for your input, @Lukas012.
