### ISSUE TITLE
Plotly on koalas dataframes

### ISSUE THREAD

**Issue by jainayush007** [databricks/koalas#1626]
I can easily use plotly's interactive charts by below 2 lines of code:

import pandas as pd
pd.options.plotting.backend = "plotly"

However, unable to use Plotly with Koalas Dataframes. Is there a workaround or can there be an enhancement to include this feature?

**Comment by HyukjinKwon** [comment]
I don't think there is an easy workaround at this moment.

**Comment by jainayush007** [comment]
So, what is an alternative, of a visualization library which works both on pandas and koalas without needing much of code change? Visualization is an important component during EDA and Data Analysis and right now I feel this is a limitation for being able to move pandas codes to koalas.

**Comment by HyukjinKwon** [comment]
Currently the only alternative is to use matplotlib for now. I am happy to review and merge if somebody works on it in Koalas.

**Comment by jainayush007** [comment]
I am running this on a colab environment. Unfortunately getting an interactive plot from matplotlib on colab is not supported. So, I need to get back to pandas to be able to create interactive plots.

**Comment by DumbMachine** [comment]
I'd like to work on implementing the `matplotlib` features for `plotly`, if this is a required feature.

**Comment by jainayush007** [comment]
Thanks Ratin. Interactive visualization is the way to go in my opinion and
matplotlib has lot of limitations when it comes to that.

**Comment by ueshin** [comment]
@DumbMachine Please feel free to go ahead and submit a PR. Thanks for working on this!

**Comment by DumbMachine** [comment]
`Plotly` backend for `pandas` currently supports:
1. `line`
2. `scatter`
3. `area`
4. `bar`
5. `box`
6. `histogram`

So I will start by implementing these.

**Comment by DumbMachine** [comment]
Small update, Made some changes to get plotly up and working. Below is a small example. If this does it, then I will open the `PR`.
![image](https://user-images.githubusercontent.com/23381512/86916108-b52e4e80-c140-11ea-828a-15206814d6a0.png)
(sorry about the image size)

**Comment by jainayush007** [comment]
Great start! Pandas has a feature to enable a visualization library by
selection -

import pandas as pd
pd.options.plotting.backend = "plotly"

Would we be able to setup something similar for Koalas? This would also,
enable a pandas-like approach to visualization. I would think this would
keep the syntax closer and similar to pandas style of enabling and using
plotly.

**Comment by HyukjinKwon** [comment]
Koalas support such options - https://koalas.readthedocs.io/en/latest/user_guide/options.html. We could implement this in a similar way.

**Comment by ueshin** [comment]
Awesome work!

Yeah, shall we have a conf `ks.options.plotting.backend = "plotly"` and switch the behavior to follow the pandas' usage?
FYI: the file for options is https://github.com/databricks/koalas/blob/master/databricks/koalas/config.py

**Comment by DumbMachine** [comment]
Have opened a PR. The plotting works as expected. I have tested the 
1. `ks.options.plotting.backend = "plotly"`
2. `ks.options.plotting.backend = "pandas_bokeh"`

 options. Using the `options` strategy allows for compatibility with other libraries as well like `pandas_altair`.

**Comment by jainayush007** [comment]
Hi,
I am on Koalas 1.0.1. But unable to use the feature -
[image: image.png]

[image: image.png]

Thanks
Ayush Jain

**Comment by ueshin** [comment]
@jainayush007 This feature will be available in the next release.

**Comment by jainayush007** [comment]
Ah I see! Do we know when would the next release happen?

**Comment by ueshin** [comment]
The current target is 7/16 2020. https://koalas.readthedocs.io/en/latest/development/contributing.html#release-cadence

**Comment by jainayush007** [comment]
Hi,

I started using this. Seems like is a scale issue here. Here is an example -

This is the URL of the dataset - '
https://raw.githubusercontent.com/srivatsan88/YouTubeLI/master/dataset/coronavirus/corona_dataset_latest.csv
'

Koalas + Plotly -
[image: image.png]

Pandas + Plotly -
[image: image.png]

Thanks
Ayush Jain

**Comment by ueshin** [comment]
Hi, we can't see the images.
Could you upload the image somewhere we can see, and also could you elaborate what the issue is?

Btw, I guess opening a new issue would be better?

Thanks.

**Comment by jainayush007** [comment]
Sure, I just created issue  #1817
