### ISSUE TITLE
Binary operation got "AnalysisException" after doing kdf[key] = kdf[key] + 1

### ISSUE THREAD

**Issue by shengjh** [databricks/koalas#1633]
Hello, I'm new to koalas and trying to process spatial data based on Series or DataFrame. 

When i modify a colum in a DataFrame like code sample below, an `AnalysisException`  is raised.

**Code Sample**
```
from databricks.koalas import DataFrame

data = {"a": [1, 2, 3, 4]}
kdf = DataFrame(data)
kdf['a'] = kdf['a'] + 1
print(kdf['a'] + 1)
```

**Error Output**
```
pyspark.sql.utils.AnalysisException: syntax error in attribute name: `((a + 1) AS `a` + 1)`;
```

**Software versions**
```
python 3.7.6
koalas 1.0.0
pyspark 3.0.0
spark 3.0.0
```
Is it a BUG? Hope for some help.

**Comment by HyukjinKwon** [comment]
This is definitely a bug. Will take a look.
