### ISSUE TITLE
Cannot read parquet file from Pandas

### ISSUE THREAD

**Issue by lfdversluis** [databricks/koalas#1645]
I computed some data using pandas which I wrote to a file. The df looks like this https://i.imgur.com/pxCLrUh.png 
I wrote it to parquet using `plot_df.to_parquet("test.parquet", flavor='spark')`

Now when I read it in using spark, there is no issue, yet note there being one additional column which apparently pandas adds:
```
df = spark.read.parquet("test.parquet")
df.printSchema()
root
 |-- time: timestamp (nullable = true)
 |-- node: string (nullable = true)
 |-- power_usage: double (nullable = true)
 |-- temperature: double (nullable = true)
 |-- processes_running: double (nullable = true)
 |-- memory_used: double (nullable = true)
 |-- load1: double (nullable = true)
 |-- __index_level_0__: long (nullable = true)
```

Now if I run `kdf = df.to_koalas()` I get
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-29-4c46820eb041> in <module>
      1 df = spark.read.parquet("test.parquet")
      2 df.printSchema()
----> 3 kdf = df.to_koalas()

/var/scratch/lvs215/miniconda3/lib/python3.8/site-packages/databricks/koalas/frame.py in to_koalas(self, index_col)
   4449 
   4450             index_map = _get_index_map(self, index_col)
-> 4451             internal = InternalFrame(spark_frame=self, index_map=index_map)
   4452             return DataFrame(internal)
   4453 

/var/scratch/lvs215/miniconda3/lib/python3.8/site-packages/databricks/koalas/internal.py in __init__(self, spark_frame, index_map, column_labels, data_spark_columns, column_label_names)
    436 
    437         if index_map is None:
--> 438             assert not any(SPARK_INDEX_NAME_PATTERN.match(name) for name in spark_frame.columns), (
    439                 "Index columns should not appear in columns of the Spark DataFrame. Avoid "
    440                 "index column names [%s]." % SPARK_INDEX_NAME_PATTERN

AssertionError: Index columns should not appear in columns of the Spark DataFrame. Avoid index column names [re.compile('__index_level_[0-9]+__')].
```

The issue looks similar to https://github.com/xitongsys/parquet-go/issues/233

How to deal with this? Should I follow the suggestion in https://github.com/apache/arrow/issues/2244 and don't preserve the index?

**Comment by ueshin** [comment]
You can specify the index column:

```py
kdf = df.to_koalas(index_col='__index_level_0__')
```

or

```py
kdf = ks.read_parquet("test.parquet", index_col='__index_level_0__')
```

See also: https://koalas.readthedocs.io/en/latest/user_guide/pandas_pyspark.html#pyspark

**Comment by lfdversluis** [comment]
Forgot to comment.

Your suggestion indeed works. I think this is something that koalas (by design) cannot pickup upon automatically? It's not a big deal, but it in code it might appear a bit as a "magic" index name. On the other hand, the one that output the pandas dataframe could've exported it without that index as well, so that would be a counter argument.

Feel free to close this one if you'd like.

**Comment by ueshin** [comment]
Actually parquet files output by pandas have a metadata on which columns should be indices.
Do you want to work on picking up the metadata automatically?

**Comment by ueshin** [comment]
For the case when you do `spark.read.parquet("test.parquet").to_koalas()`, we can't pick up automatically since Spark DataFrame doesn't have such metadata.
