### ISSUE TITLE
Tutorial notebook isn't loading right now

### ISSUE THREAD

**Issue by boatcoder** [databricks/koalas#1653]
Says to check for logs, but that window/panel is blank.

Really interested in kicking the tires....

I've tried it twice and gave the first one 30 minutes (because I was in a meeting) and it never got initialized.

**Comment by ueshin** [comment]
Do you mean [this one](https://mybinder.org/v2/gh/databricks/koalas/master?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb)?
It actually seems working in my end.
