### ISSUE TITLE
How to create a DataFrame with column name case-sensitive 

### ISSUE THREAD

**Issue by shengjh** [databricks/koalas#1657]
Hello, I find it is not easy to create a case-sensitive columns  DataFrame.
```py
data = {'a':[1,2], 'A': [2,3]}
kdf = ks.DataFrame(data)
...
pyspark.sql.utils.AnalysisException: Reference 'a' is ambiguous, could be: a, a.;
```
I googled this error and i should to set pyspark option `spark.sql.caseSensitive=true`.
So I tried `ks.set_option`, but it failed by `_check_option`.
Is there any way to set pyspark option? Or how to create a case-sensitive DataFrame?

**Comment by HyukjinKwon** [comment]
Case sensitivity is not properly supported yet. There's a Spark configuration to enable `spark.sql.caseSensitive` but this is strongly discouraged for many reasons.

I think we should document that case sensitivity is not recommended, and users could turn on  `spark.sql.caseSensitive` if they should use on their own risk.
https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#do-not-use-duplicated-column-names

**Comment by HyukjinKwon** [comment]
@shengjh are you interested in submitting a PR to document this in https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#do-not-use-duplicated-column-names?

**Comment by shengjh** [comment]
Yes, glad to do this.
