### ISSUE TITLE
Add pyspark-stubs for more precise typing checks

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#166]
The `pyspark-stubs` provides better typing checks around Spark dataframes. This task has 2 parts:
 - adding this package when doing the linting (it is only available through pip)
 - fixing any warning that it may generate when adding the proper type information to `DataFrame._sdf`. That should be a good check that the static linter works as expected.

See this line:
https://github.com/databricks/koalas/blob/master/databricks/koalas/frame.py#L63

**Comment by thunterdb** [comment]
Also, we should update the dev instructions so that developpers know how to run typing.

**Comment by zero323** [comment]
@thunterdb FYI Since today [it is](https://anaconda.org/conda-forge/pyspark-stubs) also published to Conda Forge.

**Comment by itholic** [comment]
I think the static analysis now we're doing with `dev/reformat` and 'dev/lint-python', including `mypy`, `flake8`, `pycodestyle` and `sphinx` is enough.

Let me close this, but please feel free to leave a comment.
