### ISSUE TITLE
Throw an AnalysisException when displaying the results returned by the koalas series operation with numpy 

### ISSUE THREAD

**Issue by Tom-Deng** [databricks/koalas#1664]
According to https://www.kaggle.com/c/ashrae-energy-prediction/overview，I want to finish the data analysis with koalas. When I operate series with numpy，the returned result can not only be displayed but also calculated.

![image](https://user-images.githubusercontent.com/17919002/87913166-31aa2100-caa1-11ea-8108-d594c3e54f46.png)

full code：
[input_less.tar.gz](https://github.com/databricks/koalas/files/4946271/input_less.tar.gz)

Software versions
python 3.6.9
koalas 1.0.1
pyspark 3.0.0
spark 3.0.0

**Comment by ueshin** [comment]
This error must be fixed in Koalas 1.1.0. Could you try it with 1.1.0 again? Thanks!

**Comment by Tom-Deng** [comment]
> This error must be fixed in Koalas 1.1.0. Could you try it with 1.1.0 again? Thanks!

Good job. This problem has been fixed in Koalas 1.1.0
![image](https://user-images.githubusercontent.com/17919002/88005190-5c48b800-cb3b-11ea-8c1b-c0b6a088e5ce.png)
