### ISSUE TITLE
Throw an PythonException  when displaying the results returned by the koalas dataframe operation with iloc

### ISSUE THREAD

**Issue by Tom-Deng** [databricks/koalas#1665]
According to https://www.kaggle.com/c/ashrae-energy-prediction/overview，I want to finish the data analysis with koalas. When I operate dataframe with iloc，the returned result can not only be displayed but also calculated.

![image](https://user-images.githubusercontent.com/17919002/87917546-bac45680-caa7-11ea-956c-2e84bac266c0.png)

full code：
[input_less_dataframe.tar.gz](https://github.com/databricks/koalas/files/4946508/input_less_dataframe.tar.gz)

Software versions
python 3.6.9
koalas 1.0.1
pyspark 3.0.0
spark 3.0.0

**Comment by HyukjinKwon** [comment]
Can you show the full exception message?

**Comment by Tom-Deng** [comment]
> Can you show the full exception message?

All the error messages in the attachment.


---------------------------------------------------------------------------
PythonException                           Traceback (most recent call last)
~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/frame.py in __repr__(self)
  10222             return self._to_internal_pandas().to_string()
  10223 
> 10224         pdf = self._get_or_create_repr_pandas_cache(max_display_count)
  10225         pdf_length = len(pdf)
  10226         pdf = pdf.iloc[:max_display_count]

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/frame.py in _get_or_create_repr_pandas_cache(self, n)
  10214     def _get_or_create_repr_pandas_cache(self, n):
  10215         if not hasattr(self, "_repr_pandas_cache") or n not in self._repr_pandas_cache:
> 10216             self._repr_pandas_cache = {n: self.head(n + 1)._to_internal_pandas()}
  10217         return self._repr_pandas_cache[n]
  10218 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/frame.py in _to_internal_pandas(self)
  10210         This method is for internal use only.
  10211         """
> 10212         return self._internal.to_pandas_frame
  10213 
  10214     def _get_or_create_repr_pandas_cache(self, n):

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/utils.py in wrapped_lazy_property(self)
    463     def wrapped_lazy_property(self):
    464         if not hasattr(self, attr_name):
--> 465             setattr(self, attr_name, fn(self))
    466         return getattr(self, attr_name)
    467 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/internal.py in to_pandas_frame(self)
    739         """ Return as pandas DataFrame. """
    740         sdf = self.to_internal_spark_frame
--> 741         pdf = sdf.toPandas()
    742         if len(pdf) == 0 and len(sdf.schema) > 0:
    743             pdf = pdf.astype(

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/pandas/conversion.py in toPandas(self)
    136 
    137         # Below is toPandas without Arrow optimization.
--> 138         pdf = pd.DataFrame.from_records(self.collect(), columns=self.columns)
    139         column_counter = Counter(self.columns)
    140 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/dataframe.py in collect(self)
    594         """
    595         with SCCallSiteSync(self._sc) as css:
--> 596             sock_info = self._jdf.collectToPython()
    597         return list(_load_from_socket(sock_info, BatchedSerializer(PickleSerializer())))
    598 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    135                 # Hide where the exception came from that shows a non-Pythonic
    136                 # JVM exception message.
--> 137                 raise_from(converted)
    138             else:
    139                 raise

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/utils.py in raise_from(e)

PythonException: 
  An exception was thrown from Python worker in the executor. The below is the Python worker stacktrace.
Traceback (most recent call last):
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 605, in main
    process()
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 597, in process
    serializer.dump_stream(out_iter, outfile)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 255, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 88, in dump_stream
    for batch in iterator:
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 248, in init_stream_yield_batches
    for series in iterator:
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 450, in mapper
    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 450, in <genexpr>
    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 110, in <lambda>
    verify_result_type(f(*a)), len(a[0])), arrow_return_type)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/util.py", line 107, in wrapper
    return f(*args, **kwargs)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/internal.py", line 618, in offset
    current_partition_offset = sums[id.iloc[0]]
KeyError: 21
---------------------------------------------------------------------------
PythonException                           Traceback (most recent call last)
~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/frame.py in _repr_html_(self)
  10245             return self._to_internal_pandas().to_html(notebook=True, bold_rows=bold_rows)
  10246 
> 10247         pdf = self._get_or_create_repr_pandas_cache(max_display_count)
  10248         pdf_length = len(pdf)
  10249         pdf = pdf.iloc[:max_display_count]

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/frame.py in _get_or_create_repr_pandas_cache(self, n)
  10214     def _get_or_create_repr_pandas_cache(self, n):
  10215         if not hasattr(self, "_repr_pandas_cache") or n not in self._repr_pandas_cache:
> 10216             self._repr_pandas_cache = {n: self.head(n + 1)._to_internal_pandas()}
  10217         return self._repr_pandas_cache[n]
  10218 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/frame.py in _to_internal_pandas(self)
  10210         This method is for internal use only.
  10211         """
> 10212         return self._internal.to_pandas_frame
  10213 
  10214     def _get_or_create_repr_pandas_cache(self, n):

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/utils.py in wrapped_lazy_property(self)
    463     def wrapped_lazy_property(self):
    464         if not hasattr(self, attr_name):
--> 465             setattr(self, attr_name, fn(self))
    466         return getattr(self, attr_name)
    467 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/internal.py in to_pandas_frame(self)
    739         """ Return as pandas DataFrame. """
    740         sdf = self.to_internal_spark_frame
--> 741         pdf = sdf.toPandas()
    742         if len(pdf) == 0 and len(sdf.schema) > 0:
    743             pdf = pdf.astype(

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/pandas/conversion.py in toPandas(self)
    136 
    137         # Below is toPandas without Arrow optimization.
--> 138         pdf = pd.DataFrame.from_records(self.collect(), columns=self.columns)
    139         column_counter = Counter(self.columns)
    140 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/dataframe.py in collect(self)
    594         """
    595         with SCCallSiteSync(self._sc) as css:
--> 596             sock_info = self._jdf.collectToPython()
    597         return list(_load_from_socket(sock_info, BatchedSerializer(PickleSerializer())))
    598 

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    135                 # Hide where the exception came from that shows a non-Pythonic
    136                 # JVM exception message.
--> 137                 raise_from(converted)
    138             else:
    139                 raise

~/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/sql/utils.py in raise_from(e)

PythonException: 
  An exception was thrown from Python worker in the executor. The below is the Python worker stacktrace.
Traceback (most recent call last):
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 605, in main
    process()
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 597, in process
    serializer.dump_stream(out_iter, outfile)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 255, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 88, in dump_stream
    for batch in iterator:
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 248, in init_stream_yield_batches
    for series in iterator:
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 450, in mapper
    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 450, in <genexpr>
    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 110, in <lambda>
    verify_result_type(f(*a)), len(a[0])), arrow_return_type)
  File "/home/dengxinhuan/package/spark-3.0.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/util.py", line 107, in wrapper
    return f(*args, **kwargs)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/databricks/koalas/internal.py", line 618, in offset
    current_partition_offset = sums[id.iloc[0]]
KeyError: 20
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 60299)
Traceback (most recent call last):
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/accumulators.py", line 268, in handle
    poll(accum_updates)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/accumulators.py", line 241, in poll
    if func():
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/accumulators.py", line 245, in accum_updates
    num_updates = read_int(self.rfile)
  File "/home/dengxinhuan/miniconda3/envs/blackhole_qatest0507/lib/python3.6/site-packages/pyspark/serializers.py", line 595, in read_int
    raise EOFError
EOFError
----------------------------------------

**Comment by HyukjinKwon** [comment]
Looks like this is the same issue with https://github.com/databricks/koalas/pull/1641. Does the same issue happens when you use a different default index type?

**Comment by Tom-Deng** [comment]
> Looks like this is the same issue with #1641. Does the same issue happens when you use a different default index type?

I don't quite understand what you mean. What is a different default index type?

**Comment by HyukjinKwon** [comment]
Please take a look at https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type

**Comment by Tom-Deng** [comment]
> https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type

When I set compute.default_index_type to distributed-sequence， this problem no longer recurs.
![image](https://user-images.githubusercontent.com/17919002/89390127-e0ed2600-d738-11ea-94b3-c0953391e0e5.png)
![image](https://user-images.githubusercontent.com/17919002/89390144-e77b9d80-d738-11ea-8bca-949d8227d50f.png)

**Comment by HyukjinKwon** [comment]
Thanks @Tom-Deng for confirming this.
