### ISSUE TITLE
df.to_parquet doesn't create partitions

### ISSUE THREAD

**Issue by FredericJames** [databricks/koalas#1666]
My environment: Databrick platform: runtime 7.0 ML
Koalas: 1.0.1

I'm trying to write parquets from a koalas dataframe to S3 with partitions. The partitions are not created (I tried with a single or multiple partition cols).
If I'm using the pyspark API, the partitions are created.

code:
no partition created
df.to_parquet(path='s3://{bucket}/{Path_to_data}, mode='overwrite', compression='gzip', partition_cols=['year','month','day'])

Partition created
df.to_spark().write.mode('overwrite').partitionBy('year', 'month', 'day').parquet('s3://{bucket}/{Path_to_data}')

I would like to have the possibilities to use the partitions in koalas in the same way I'm doing it in spark.

**Comment by ueshin** [comment]
Seems like it's a bug.
Could you use `DataFrame.spark.to_spark_io` as a workaround?

```py
df.spark.to_spark_io(path='s3://{bucket}/{Path_to_data}, format='parquet', mode='overwrite', compression='gzip', partition_cols=['year','month','day'])
```

I'll work on fixing this.

**Comment by ueshin** [comment]
I submitted a PR #1667.

**Comment by FredericJames** [comment]
Thank you. I'll wait the fix. It's mainly for my data scientist and I 'd like to keep it simple for them.
I'll use the pyspark api until then.
