### ISSUE TITLE
Nullable string/object columns not supported

### ISSUE THREAD

**Issue by kokes** [databricks/koalas#167]
When trying to load a pandas DataFrame with a nullable string column, I always get 

```
TypeError: field header: Can not merge type <class 'pyspark.sql.types.StringType'> and <class 'pyspark.sql.types.DoubleType'>
```

It can be reproduced in two different ways. We can create an in-memory Series and load it:

```
import numpy as np
import pandas as pd
import databricks.koalas as ks

ks.from_pandas(pd.Series(['foo', np.nan, 'bar']))
```

Or we can populate a CSV file with at least one NULL:

```
header
value
N/A
nothing above
```

And then try to read it:

```
import pandas as pd
import databricks.koalas as ks

ks.from_pandas(pd.read_csv('foo.csv'))
```

Either way, koalas things that the `np.nan` signifies a float, but it's actually a NULL for an object column.

**Comment by thunterdb** [comment]
This is the same issue as #114 , it seems. Thanks for the way to reproduce it @kokes .
