### ISSUE TITLE
Remove the upper bounds for numpy and matplotlib.

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#1670]
So far pandas sets upper bounds for `numpy` and `matplotlib`.
Let's see how pandas handles the upper bounds.
https://github.com/pandas-dev/pandas/blob/master/requirements-dev.txt

**Comment by ueshin** [comment]
The upper bounds will be removed in pandas 1.2. https://github.com/pandas-dev/pandas/pull/35780

**Comment by ueshin** [comment]
I'd close this as they were removed at #1845 and #1839.

**Comment by HyukjinKwon** [comment]
Nice!
