### ISSUE TITLE
toPandas at /home/hadoop/conda/lib/python3.7/site-packages/databricks/koalas/internal.py:743 job gets stucked

### ISSUE THREAD

**Issue by polocorona** [databricks/koalas#1676]
I'm trying to preview a small ks.Series generated after this:

```
target_users_test = target_users.iloc[:100]
test_series = target_users_test['userid'].apply(lambda x: get_user_conversions_feature_nunique(x, 'isp'))
```

This is a test with 100 items. And still, the toPandas job simply doesn't finish up when I execute `test_series`.

This is my koalas configuration:

```
from pyspark.sql import SparkSession
builder = SparkSession.builder.appName("Koalas")
builder = builder.config("spark.sql.execution.arrow.enabled", "true")
builder.getOrCreate()

import databricks.koalas as ks
ks.set_option("compute.default_index_type", "distributed") 
```

`ARROW_PRE_0_15_IPC_FORMAT` is set to 1 in the spark-env file.

Any help?

**Comment by itholic** [comment]
Could you show me a full code or schema of `target_users` and `get_user_conversions_feature_nunique` if available ?

**Comment by itholic** [comment]
Let me close this for now since reporter has no response for a long time.

Please feel free to open again if you want to still fix this, @polocorona !
