### ISSUE TITLE
Unable to install koalas on lubuntu--segmentation fault

### ISSUE THREAD

**Issue by harnalashok** [databricks/koalas#1679]
On ubuntu, I have no problem in installing koalas and invoking the library as:

`import` databricks.koalas as ks

But, on lubuntu (version 18, 64bit), lightweight brother of ubuntu, conda installation is successful. But when I open ipython and call koalas as above, ipython breaks and I get a message of 'Segmentation fault'. I have tried to install koalas through pip also but to no avail.  I have tried this installation process on three different Virtual Machines (of lubuntu 64bit) but same result appears each time.

**Comment by ueshin** [comment]
Could you share the error detail or the screen shot which shows the whole error message?
Also, what if `import pandas` or `pyarrow` or `pyspark`?

**Comment by harnalashok** [comment]
I am attaching three screen shots. Segmentation fault occurs when I call pyarrow. The first screen shot is the successful installation of koalas. IInd screenshot is regarding segmentation fault in ipython and IIIRd when I call pyarrow in pyspark.  Thanks.

![2020-08-01-161836_1024x768_scrot](https://user-images.githubusercontent.com/47495816/89100327-d3236200-d413-11ea-834f-55040ff3c10f.png)
![2020-08-01-162054_1024x768_scrot](https://user-images.githubusercontent.com/47495816/89100330-da4a7000-d413-11ea-8c40-019d509649be.png)



![2020-08-01-161137_1024x768_scrot](https://user-images.githubusercontent.com/47495816/89100293-93f51100-d413-11ea-9944-60f2c3c0a69c.png)

**Comment by ueshin** [comment]
Could you try with the higher version of pyarrow, like `0.14.1` if the underlying Spark `<3.0` or `0.15` or higher if Spark `>=3.0` ?

**Comment by harnalashok** [comment]
This time I created a virtual environment for koalas as mentioned in the installation. pyarrow version installed was 1.0.0. Other software installed are:

Downloading and Extracting Packages
readline-8.0         | 281 KB    |  
libutf8proc-2.5.0    | 85 KB     |  
pyparsing-2.4.7      | 60 KB     |  
libgcc-ng-9.3.0      | 8.2 MB    |  
gflags-2.2.2         | 114 KB    |  
libev-4.33           | 105 KB    |  
cycler-0.10.0        | 9 KB      |  
_libgcc_mutex-0.1    | 3 KB      |  
libblas-3.8.0        | 11 KB     |  
libwebp-base-1.1.0   | 845 KB    |  
boost-cpp-1.72.0     | 16.3 MB   |  
libstdcxx-ng-9.3.0   | 4.5 MB    |  
grpc-cpp-1.30.2      | 3.2 MB    |  
pillow-7.2.0         | 676 KB    |  
matplotlib-base-3.3. | 6.7 MB    |  
icu-67.1             | 12.9 MB   |  
openssl-1.1.1g       | 2.1 MB    |  
libgfortran-ng-7.5.0 | 1.7 MB    |  
libopenblas-0.3.10   | 7.8 MB    |  
abseil-cpp-20200225. | 915 KB    |  
bzip2-1.0.8          | 396 KB    |  
libssh2-1.9.0        | 225 KB    |  
pytz-2020.1          | 227 KB    |  
tornado-6.0.4        | 642 KB    |  
lcms2-2.11           | 431 KB    |  
arrow-cpp-1.0.0      | 20.6 MB   |  
libffi-3.2.1         | 47 KB     |  
parquet-cpp-1.5.1    | 3 KB      |  
thrift-cpp-0.13.0    | 18.6 MB   |  
libevent-2.1.10      | 1.3 MB    |  
six-1.15.0           | 14 KB     |  
pandas-1.1.0         | 10.8 MB   |  
setuptools-49.2.0    | 949 KB    |  
lz4-c-1.9.2          | 226 KB    |  
pip-20.2             | 1.1 MB    |  
**pyarrow-1.0.0        | 3.0 MB    |**  
python-3.8.5         | 71.0 MB   |  
xz-5.2.5             | 343 KB    |  
matplotlib-3.3.0     | 6 KB      |  
libgomp-9.3.0        | 820 KB    |  
tk-8.6.10            | 3.2 MB    |  
libcblas-3.8.0       | 11 KB     |  
freetype-2.10.2      | 905 KB    |  
libcurl-7.71.1       | 312 KB    |  
snappy-1.1.8         | 32 KB     |  
libedit-3.1.20191231 | 122 KB    |  
libpng-1.6.37        | 308 KB    |  
re2-2020.08.01       | 226 KB    |  
libtiff-4.1.0        | 668 KB    |  
kiwisolver-1.2.0     | 87 KB     |  
ncurses-6.2          | 993 KB    |  
glog-0.4.0           | 104 KB    |  
python-dateutil-2.8. | 220 KB    |  
libnghttp2-1.41.0    | 709 KB    |  
python_abi-3.8       | 4 KB      |  
curl-7.71.1          | 139 KB    |  
zlib-1.2.11          | 105 KB    |  
_openmp_mutex-4.5    | 435 KB    |  
ca-certificates-2020 | 145 KB    |  
zstd-1.4.5           | 712 KB    |  
olefile-0.46         | 31 KB     |  
c-ares-1.16.1        | 108 KB    |  
krb5-1.17.1          | 1.5 MB    |  
brotli-1.0.7         | 386 KB    |  
libprotobuf-3.12.3   | 2.3 MB    |  
liblapack-3.8.0      | 11 KB     |  
certifi-2020.6.20    | 151 KB    |  
numpy-1.19.1         | 5.3 MB    |  
sqlite-3.32.3        | 1.4 MB    |  
aws-sdk-cpp-1.7.164  | 1.8 MB    |  
jpeg-9d              | 266 KB    |  
ld_impl_linux-64-2.3 | 612 KB    |  
wheel-0.34.2         | 24 KB     |  
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

But exactly the same segmentation fault persists. As soon as I call pyarrow library, pyspark (or rather ipython) breaks with  a Segmentation fault (Core dumped) message as before.

**Comment by HyukjinKwon** [comment]
Looks like an issue in PyArrow. It might be best to report in their repo.

**Comment by harnalashok** [comment]
The problem is solved at this [link](https://issues.apache.org/jira/browse/ARROW-9655?filter=-2).

**Comment by itholic** [comment]
Thanks for the sharing, @harnalashok
