### ISSUE TITLE
Warnings while running Koalas operations in python environment

### ISSUE THREAD

**Issue by nitishsinghal29** [databricks/koalas#1687]
I gave it a try using koalas for my Data Science project and implemented couple of usecases using koalas api. When I try running these logic in my python environment, it gives couple of warnings, as below:
```
20/07/30 01:39:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
20/07/30 01:39:24 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
```

But when I run the same logic on my spark cluster it works fine without any warnings which is expected. 
I am wondering is it something that I need to take care of setting some options while running in Spark vs pure Python environment, so that I can avoid the above warnings.

Any help would be appreciated.

**Comment by HyukjinKwon** [comment]
```
20/07/30 01:39:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
```
this is from Hadoop.

```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
20/07/30 01:39:24 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
```

these are from Spark. I think these warnings go away when you run it in a cluster as you said. In local, I think you can just ignore in general.

```
20/07/30 01:39:24 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
```

this warnings can be removed when you change default index in Koalas, see also https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type
