### ISSUE TITLE
How to automatically generate the rst format files same with docs'

### ISSUE THREAD

**Issue by Tom-Deng** [databricks/koalas#1706]
In the source code，the rst format files like this：
![image](https://user-images.githubusercontent.com/17919002/89893192-7d686a00-dc0a-11ea-95b8-fdb971576b12.png)
But generate locally like this：
![image](https://user-images.githubusercontent.com/17919002/89893383-cf10f480-dc0a-11ea-9777-e6224ab42481.png)
How to automatically generate the rst format files same with docs'？

**Comment by ueshin** [comment]
I'm not quite sure what you want.
The docs in the reference folder are not automatically generated but manually managed.

**Comment by itholic** [comment]
Hi, @Tom-Deng .
In my case, my local document list are not really different from the origin one.

![스크린샷 2020-08-12 오전 7 31 55](https://user-images.githubusercontent.com/44108233/89955425-f0ef9300-dc6d-11ea-857f-f92133e261c3.png)

Could you try `../../dev/lint-python` which includes `sphinx-build` for Koalas rather than `sphinx-apidoc -o reference` manually ??

**Comment by Tom-Deng** [comment]
> I'm not quite sure what you want.
> The docs in the reference folder are not automatically generated but manually managed.

In other words，the files in the rst format under the reference folder are all manually written, not generated by the sphinx-apidoc tool?

**Comment by Tom-Deng** [comment]
> Hi, @Tom-Deng .
> In my case, my local document list are not really different from the origin one.
> 
> ![스크린샷 2020-08-12 오전 7 31 55](https://user-images.githubusercontent.com/44108233/89955425-f0ef9300-dc6d-11ea-857f-f92133e261c3.png)
> 
> Though not pretty sure if this solution can help you, could you try `../../dev/lint-python` which includes `sphinx-build` for Koalas rather than `sphinx-apidoc -o reference` ??

Thank you very much. I tried to execute it, but I can see that the rst file under the refrence folder is not generated, but the existing rst file is used directly to generate the document. How did you solve this problem like 'no module named databricks.koalas.mlflow.PythonModelWrapper'.
![image](https://user-images.githubusercontent.com/17919002/90116018-7a46b880-dd87-11ea-8f0d-c876f9037572.png)

**Comment by HyukjinKwon** [comment]
Looks like it's because `matplotlib` wasn't installed probably. Can you upgrade `matplotlib` in your local, and try again?

**Comment by HyukjinKwon** [comment]
I am leaving this close per no more feedback from the author.
