### ISSUE TITLE
Upgrading to pyarrow >= 0.13

### ISSUE THREAD

**Issue by wesm** [databricks/koalas#171]
Could you let us know what might be stopping you from using the latest version of Apache Arrow? `pip install pyarrow` works through Python 3.7 as of 0.13.0 so the comment in your README about this is only accurate if the version number is constrained to an older version. The latest version has significantly better performance and memory use in some areas that impact Spark-Arrow users (e.g. http://arrow.apache.org/blog/2019/02/05/python-string-memory-0.12/)

**Comment by rxin** [comment]
We should definitely upgrade.

cc @thunterdb @ueshin any reason we used a old version?

**Comment by rxin** [comment]
@wesm do you want to submit a pull request? :)

**Comment by wesm** [comment]
Doubtful, but just want to make sure that we don't leave the Spark community behind in some way. My team is working on setting up nightly wheels in case that makes testing against Arrow master easier for you

**Comment by thunterdb** [comment]
Thanks @wesm for leaning in. The choice was made because the last release of Spark had issues with recent versions of arrow, see this thread for all the versions tested:
https://github.com/databricks/koalas/issues/26

We will probably have to wait for the next release of Spark (2.4.1 I presume).

**Comment by jiahut** [comment]
with `pyhton 3.7`, I only install with `pip install koalas --no-deps`  then  `pip install pyarrow pyspark`  manually

**Comment by itholic** [comment]
Now we're supporting latest PyArrow. Closing.
