### ISSUE TITLE
Docs Update: pivot_table does not have columns concatenated by “_”

### ISSUE THREAD

**Issue by nitishsinghal29** [databricks/koalas#1710]
As per the docs for pivot_table (v_1.1.0): https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.pivot_table.html#databricks.koalas.DataFrame.pivot_table

I was trying to get the pivoted dataframe with final columns concatenated by “\_” as the docs says in `aggfunc` parameter documentation. But the final dataframe has the multilevel columns instead of concatenated by “_”. 

This is the example:
```
>> df = ks.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]},
                  columns=['A', 'B', 'C', 'D', 'E'])
>> df
     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9
```
Output after pivot:
```
table = df.pivot_table(index=['C'], columns="A", values=['D', 'E'],
                        aggfunc={'D': 'mean', 'E': 'sum'})
table.sort_index() 
         D             E
A      bar       foo bar foo
C
large  5.5  2.000000  15   9
small  5.5  2.333333  17  13
```
I think updated documentation aligned with the implementation would help!!

What I was interested in the final columns concatenated by “\_” in the pivoted dataframe, not sure if it's still supported ?? I have to manually do it after getting the pivot dataframe for now.

**Comment by ueshin** [comment]
Thanks for the report! I submitted a PR to remove the outdated description (#1711).
Unfortunately, the behavior that the final columns are concatenated by “_” in the pivoted dataframe is not supported now.
