### ISSUE TITLE
Koalas read_json cannot read json when Pandas can

### ISSUE THREAD

**Issue by ericbugin** [databricks/koalas#1724]
```
import requests
full_url_with_date = 'https://demo.matomo.org/index.php?module=API&method=Live.getLastVisitsDetails&format=json&period=day&filter_limit=99&date=2020-08-02&idSite=62'

matomo_pull = requests.get(full_url_with_date).content

import pandas as pd
pdf = pd.read_json(matomo_pull)

from databricks import koalas as ks
ks.read_json(matomo_pull)
```

**Comment by ueshin** [comment]
The first parameter `path` must be the file path in Koalas ([databricks.koalas.read_json](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.read_json.html)).
You can use pandas and covert it to Koalas.

```py
ks.from_pandas(pd.read_json(matomo_pull))
```

**Comment by ericbugin** [comment]
Im aware of the roundabout way. I am more interested in not being reliant on Pandas when working on Spark.

**Comment by HyukjinKwon** [comment]
Currently we don't have a plan to support http scheme. We could alternatively parse the url inside the Koalas and falls back & leverages pandas to create a Koalas DataFrame.

My only concern is that, http scheme isn't really for large dataset in general. It won't really be able to load it in a distributed manner and if the file is big, it will just throw an out of memory exception.

**Comment by itholic** [comment]
@HyukjinKwon ,Can we close this since supporting `http` scheme in distributed manner doesn't enough makes sense??

**Comment by itholic** [comment]
it's duplicated with https://github.com/databricks/koalas/issues/1219.
