### ISSUE TITLE
Key order not maintained on merge

### ISSUE THREAD

**Issue by thehomebrewnerd** [databricks/koalas#1726]
If I am reading the[ ks.merge docs](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.merge.html#databricks.koalas.DataFrame.merge) correctly, if I perform an inner merge, the order of the left keys should be maintained:

```
inner: use intersection of keys from both frames, similar to a SQL inner join;
preserve the order of the left keys.
```

However, this seems to not be the case: 

```
left = ks.DataFrame({'id':range(4), 'left_vals': ['left']*4})
right = ks.DataFrame({'id':range(10), 'right_vals': ['right']*10})

merge_df = left.merge(right, how="inner", on="id")
print(merge_df)

   id left_vals right_vals
0   2      left      right
1   0      left      right
2   1      left      right
3   3      left      right
```

The `id` column order does not match the original sequential order in the left dataframe. Am I doing something wrong, or are the docs incorrect?

**Comment by HyukjinKwon** [comment]
I think we should fix the doc. the order is not guaranteed in general.
