### ISSUE TITLE
Koalas doesn't work with spatial dataframes

### ISSUE THREAD

**Issue by applecool** [databricks/koalas#1729]
Hi,

I work with spatial dataframes which are created using the geopandas library. As the spatial dataframes contain geometries, they can get pretty massive. It would be awesome if Koalas can support Spatial DF's. Is there any plan to support geopandas - something like  `ks.from_geopandas(spdf)` in the future roadmap?

**Comment by itholic** [comment]
Looks interesting.
Let me investigate if there is any issue applying it to Koalas.
Thanks for the suggestion, @applecool :)

**Comment by HyukjinKwon** [comment]
Let's don't add this support for now. `geopandas` itself is also a thirdparty library. We could think about leaving it as a thridparty unless there's a big needs for that.
