### ISSUE TITLE
Are there performance benchmarks?

### ISSUE THREAD

**Issue by georghildebrand** [databricks/koalas#173]
Hi all, nice project and congrats how far you got already!
I wonder if there already are performance benchmarks comparing to default pyspark etc. ?

**Comment by HyukjinKwon** [comment]
Performance-wise, for its current status, it should be virtually same to PySpark because the execution is delegated. Also, I personally think it's premature to discuss about it.

**Comment by rxin** [comment]
Yes - it should be the same as PySpark if you are using the DataFrame API in PySpark. I'm going to close this.

As we improve the project, we might make specific operations more performant, but that will be future work :)
