### ISSUE TITLE
Comparison to DASK

### ISSUE THREAD

**Issue by georghildebrand** [databricks/koalas#174]
I saw that you orient already quite a bit on how DASKs works. Are you already considering building support for DASK as well? I currently see it very often used especially for research driven parallel python workloads - so that would be a major benefit...

**Comment by HyukjinKwon** [comment]
Actually there is already a short comparison - https://github.com/databricks/koalas#how-is-koalas-different-from-dask

**Comment by georghildebrand** [comment]
thx, will check that out

**Comment by georghildebrand** [comment]
@HyukjinKwon i think the comparison is not satisfying. i am actively using both spark and dask. I think it would be worth thinking about bridging both dask and spark.

**Comment by rxin** [comment]
Can you say more about what you have in mind in bridging both dask and Spark? Might not be part of the scope of this project but certainly is something we can consider.

**Comment by georghildebrand** [comment]
Eg currently i use spark to do some data preprocessing / data extraction --> store to s3 --> pick up with dask and do ML stuff as its very dynamic and nice for that (eg. the cinterface to some of the libs). 

With a common api i would expect something like --> sdf = spark.createDataFrame(df) --> sdf.to_dask --> keep on working with dask --> 


```
import dask_ml.joblib

from sklearn.externals.joblib import parallel_backend

with parallel_backend('dask'):
    # Your normal scikit-learn code here
```


Currently one has do some workaround like: https://gist.github.com/mrocklin/83401a7030f9dde483de37c6592a291f

**Comment by rxin** [comment]
Can you just use the Pandas UDF feature in Spark?

**Comment by icexelloss** [comment]
re @rxin:
A lot of the use case we've seen is parallelized parameter search, in which case groupby apply + Pandas UDF doesn't help as each task need the entire dataset. When people use Spark for this, they just do
 
```
sc.parallelize(grid_to_search).map(lambda param: train_and_eval(param))
```

@georghildebrand I am curious do you have some ML example that is much easier to do with Dask than Spark?

**Comment by rxin** [comment]
@icexelloss  So what you really want is some ability to broadcast data, which already exists in Spark right?

**Comment by icexelloss** [comment]
Yeah for the param search example I give, it already works. Just wanted to point out parallel_backend('dask') is similar to sc.parallelize instead of Pandas UDF. Nothing really needs to be add to Spark to support that.

**Comment by rxin** [comment]
I'm going to close this for now since it's unclear what the action items are.
