### ISSUE TITLE
Creating MultiIndex via Index class.

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#1758]
pandas can create MultiIndex via Index class as shown below.

```python
>>> pidx = pd.Index([(1, 'a'), (2, 'b'), (3, 'c')])
>>> pidx
MultiIndex([(1, 'a'),
            (2, 'b'),
            (3, 'c')],
           )

>>> type(pidx)
<class 'pandas.core.indexes.multi.MultiIndex'>
```

Koalas also seems can do, but the type is still `Index`, not `MultiIndex`

```python
>>> kidx = ks.Index([(1, 'a'), (2, 'b'), (3, 'c')])
>>> kidx
MultiIndex([(1, 'a'),
            (2, 'b'),
            (3, 'c')],
           )

>>> type(kidx) # this must be <class 'databricks.koalas.indexes.MultiIndex'>
<class 'databricks.koalas.indexes.Index'>
```

**Comment by itholic** [comment]
Seems pandas use `__new__` when they create various kind of Index via single class. https://github.com/pandas-dev/pandas/blob/v1.1.2/pandas/core/indexes/base.py#L289-L430

Maybe we should follow this to support various of Index type with single class ??

**Comment by ueshin** [comment]
Cool. Do you want to work on it?

**Comment by itholic** [comment]
@ueshin Sure, seems interesting :)
