### ISSUE TITLE
DataFrame.apply moves all data to single executor

### ISSUE THREAD

**Issue by jimfulton** [databricks/koalas#1769]
When trying to use apply with Spark 2.4, I get "20/09/14 06:45:37 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation." and all computation in the apply is done on a single node.

That's bad. :) It's especially bad because many (most?) Koalas users use Jupyter and can't see that this is happening because stderr is hidden. :(

Here's a sample session:

```
bash-3.2$ python3.6 -m venv venv
bash-3.2$ . venv/bin/activate
(venv) bash-3.2$ pip install -U pip
...
Successfully installed pip-20.2.3
(venv) bash-3.2$ pip install --progress-bar off pyspark==2.4.5
...
Successfully installed py4j-0.10.7 pyspark-2.4.5
(venv) bash-3.2$ pip install --progress-bar off koalas
///
Successfully installed cycler-0.10.0 kiwisolver-1.2.0 koalas-1.2.0 matplotlib-3.2.2 numpy-1.18.5 pandas-1.0.5 pyarrow-1.0.1 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0
(venv) bash-3.2$ python
///
>>> import pyspark.sql
>>> spark = (pyspark.sql.SparkSession.builder
            .master("local[*]")
            .enableHiveSupport()
            .getOrCreate()
            )
>>> import databricks.koalas as ks
>>> df = ks.range(9)
>>> df.apply((lambda r: 1), 1)
20/09/14 06:45:37 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
dtype: int64
>>> 
```

Am I doing something wrong?

**Comment by jimfulton** [comment]
Oh, this is occurring with Spark 3.0.1 as well.

```
bash-3.2$ python3.6 -m venv venv3
bash-3.2$ . venv3/bin/activate
(venv3) bash-3.2$ pip install -U pip
...
Successfully installed pip-20.2.3
(venv3) bash-3.2$ pip install --progress-bar off pyspark
...
Successfully installed py4j-0.10.9 pyspark-3.0.1
(venv3) bash-3.2$ pip install --progress-bar off koalas
...
Successfully installed cycler-0.10.0 kiwisolver-1.2.0 koalas-1.2.0 matplotlib-3.2.2 numpy-1.18.5 pandas-1.0.5 pyarrow-1.0.1 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0
(venv3) bash-3.2$ python
...
>>> import pyspark.sql
>>> spark = (pyspark.sql.SparkSession.builder
            .master("local[*]")
            .enableHiveSupport()
            .getOrCreate()
            )
...
>>> import databricks.koalas as ks
>>> df = ks.range(9)
>>> df.apply((lambda r: 1), 1)
20/09/14 07:07:24 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
dtype: int64
>>> 
```

**Comment by HyukjinKwon** [comment]
This is because the default index is being used. Please also see https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type and https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#specify-the-index-column-in-conversion-from-spark-dataframe-to-koalas-dataframe

**Comment by jimfulton** [comment]
Thanks.  So doing:

`ks.set_option('compute.default_index_type', 'distributed')`

In the toy example I gave above avoids the "No Partition Defined for Window operation! " warning.

When I try to use this with a table read from Hive:

```
import databricks.koalas as ks
ks.set_option('compute.default_index_type', 'distributed')
df = spark.sql("select * from mytable")
df.count()
```

I get:

`java.lang.AssertionError: assertion failed: No plan for HiveTableRelation`

Note that I haven't even created a Koalas data frame.

In another session, I did:

```
import databricks.koalas as ks
df = spark.sql("select * from mytable")
ks.set_option('compute.default_index_type', 'distributed')
df.count()
kf = ks.DataFrame(df)
len(kf)
kf.apply((lambda r: 1), 1)
df2 = spark.sql("select * from mytable")
df2.count()
```

IOW, doing `ks.set_option('compute.default_index_type', 'distributed')` before reading from Hive with PySpark caused hive errors.

This makes setting this option very awkward.

BTW, I notice that in https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type,
the examples do `ks.reset_option('compute.default_index_type')` after creating a DataFrame.  Why is that? Is it related to the error above?

**Comment by ueshin** [comment]
You have to initialized Spark first if you use a Spark session with non-default settings; otherwise Koalas tries to initialize it with default settings.

For the document, it's just to make sure the options don't affect other examples. I don't think it's related to the error.

**Comment by jimfulton** [comment]
I did initialize spark first as shown in the first example. I just didn't show it for brevity.

**Comment by ueshin** [comment]
I see, but I'm afraid I don't see any issues so far:

```py
$ python
Python 3.8.3 (default, May 19 2020, 13:54:14)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyspark
>>> spark = (pyspark.sql.SparkSession.builder.master("local[*]").enableHiveSupport().getOrCreate())

... omit messages

>>> import databricks.koalas as ks
>>> ks.set_option('compute.default_index_type', 'distributed')
>>> spark.sql("select * from src").count()

... omit messages

0

>>> pyspark.__version__
'3.0.1'
>>> ks.__version__
'1.2.0'
```

```py
>>> spark.sql("select * from src").explain(True)
== Parsed Logical Plan ==
'Project [*]
+- 'UnresolvedRelation [src]

== Analyzed Logical Plan ==
key: int, value: string
Project [key#15, value#16]
+- SubqueryAlias spark_catalog.default.src
   +- HiveTableRelation `default`.`src`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [key#15, value#16], Statistics(sizeInBytes=8.0 EiB)

== Optimized Logical Plan ==
HiveTableRelation `default`.`src`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [key#15, value#16], Statistics(sizeInBytes=8.0 EiB)

== Physical Plan ==
Scan hive default.src [key#15, value#16], HiveTableRelation `default`.`src`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, [key#15, value#16], Statistics(sizeInBytes=8.0 EiB)
```

**Comment by jimfulton** [comment]
I was using Spark non-local 2.4.4. I'll try with local Hive and with Spark 3.

**Comment by jimfulton** [comment]
I verified that I don't get an error with local spark. 🤷

**Comment by jimfulton** [comment]
Some parting suggestions, fwiw:

- Having the default sequence type be 'sequence' is a foot gun, especially since many (most) users won't be able to see the window warnings, because Jupyter.
- `compute.ops_on_diff_frames`  is a foot gun.  Is it possible to get this right? I'm skeptical. I still don't understand how I would, at least assuming a non-sequence index.
- AFAICT, `apply` on axis 1 would be a lot more useful if the output sequence preserved the input dataframe's index.  Then you could use `merge` to combine the results. (Maybe you could even assign the result, not sure.)

Thanks for the pointer on indexes!
