### ISSUE TITLE
cluster mode adding py files

### ISSUE THREAD

**Issue by anaveenan** [databricks/koalas#178]
I want to work in cluster mode. But it can't be installed directly in the cluster. How can I pass this in my spark-submit script ?

Can you please add instruction to help with this.

**Comment by HyukjinKwon** [comment]
I think this is rather a Spark's general issue. See, for instance, https://issues.apache.org/jira/browse/SPARK-13587

Currently,

1. Install it via pip in all nodes
2. Try to zip the source codes by yourself and ship it via py-files.
3. I remember somebody wrote a blog about packing it with PEX that already works in PySpark. See https://medium.com/criteo-labs/packaging-code-with-pex-a-pyspark-example-9057f9f144f3

I don't think there is anything we can do within this library but in Apache Spark.

**Comment by HyukjinKwon** [comment]
I am leaving this closed. I would suggest to interact with Spark mailing list.
