### ISSUE TITLE
`fillna()` `inplace` unexpected behaviour

### ISSUE THREAD

**Issue by amin-nejad** [databricks/koalas#1807]
When using `inplace=True` with `fillna()` on a `Series` that does not have any `na`s to fill, the entire `DataFrame` to which the `Series` belongs is replaced by the `Series`. Let me demonstrate with an example:

## Koalas example
```python
import databricks.koalas as ks

data = ks.DataFrame({'a':[1, 2, None], 'b':[1, 2, 3]})

# Expected behaviour
data['a'].fillna('Missing', inplace=True)
print(data)
#          a  b
# 0      1.0  1
# 1      2.0  2
# 2  Missing  3

# Unexpected behaviour
data['b'].fillna('Missing', inplace=True)
print(data)
#    b
# 0  1
# 1  2
# 2  3
```

As you can see, `data` has been replaced with `data['b']`. This is does not happen with `pandas` as shown below. Again this only happens with `inplace=True`.

## Pandas example
```python
import pandas as pd

data = pd.DataFrame({'a':[1, 2, None], 'b':[1, 2, 3]})

# Expected behaviour
data['a'].fillna('Missing', inplace=True)
print(data)
#          a  b
# 0        1  1
# 1        2  2
# 2  Missing  3

# Expected behaviour
data['b'].fillna('Missing', inplace=True)
print(data)
#          a  b
# 0        1  1
# 1        2  2
# 2  Missing  3
```

There also appears to be a separate issue of `koalas` converting the integers in `df.a` to floating point numbers which `pandas` doesn't do. However I'm not sure about this. Is this expected? Thanks

Ubuntu 18.04
python 3.7.6
koalas==1.2.0
pandas==1.0.5

**Comment by ueshin** [comment]
Thanks for the report! I'll handle it.

**Comment by ueshin** [comment]
As for the data type, pandas DataFrame after `fillna` contains float values (`1.0`, `2.0`) and a string value (`Missing`) in the same column, but Spark doesn't allow to have different data type values in a column, so does Koalas, which contains string values as Spark type coercion rule.

**Comment by amin-nejad** [comment]
Thanks @ueshin!
