### ISSUE TITLE
Plotly charts not same as pandas

### ISSUE THREAD

**Issue by jainayush007** [databricks/koalas#1817]
Hi,

Seems like is a scale issue on koalas plots using plotly. It doesn't show all dates while pandas plot does!

This is the URL of the dataset - 'https://raw.githubusercontent.com/srivatsan88/YouTubeLI/master/dataset/coronavirus/corona_dataset_latest.csv'

Here is an example -

Koalas + Plotly -
![image](https://user-images.githubusercontent.com/31528721/95000083-6119f580-05db-11eb-9fcf-05c0fc663394.png)

Pandas + Plotly -
![image](https://user-images.githubusercontent.com/31528721/95000112-8e66a380-05db-11eb-9e60-2c6f719ee747.png)

@DumbMachine

**Comment by ueshin** [comment]
cc @DumbMachine Could you take a look at this when you have time?

**Comment by mihirrane** [comment]
I tried to perform read_csv() similar to pandas but I got this result
![image](https://user-images.githubusercontent.com/21999153/95927679-0fb0f980-0d85-11eb-91da-b9e03621dfab.png)

Py4JJavaError: An error occurred while calling o3673.csv.
: java.io.IOException: No FileSystem for scheme:

I would like to work on resolving this issue if it's okay. 
Thanks!

**Comment by mihirrane** [comment]
I just saw the issue #1219 and I think that answers my question

**Comment by itholic** [comment]
yeah, seems like it's duplicated to https://github.com/databricks/koalas/issues/1219.

Let me close this.
