### ISSUE TITLE
Increase upper numpy version bound?

### ISSUE THREAD

**Issue by sid-kap** [databricks/koalas#1837]
In https://github.com/databricks/koalas/pull/1734, it looks like the numpy upper bound was lowered to `<1.19.0`. Is there something in koalas that is incompatible with 1.19.x? If not, can it be increased to `<1.20.0`?

cc @ueshin

**Comment by itholic** [comment]
Thanks for the report, @sid-kap . :)

Let me check if the tests works well on numpy `1.19.x`.

**Comment by sid-kap** [comment]
Thank you!
