### ISSUE TITLE
pip install koalas not working

### ISSUE THREAD

**Issue by shril** [databricks/koalas#191]
I am trying to install koalas on my Ubuntu 18.04.2 LTS.
Default Python3 is Python 3.6.7. 
I am getting the following error.

`
Could not find a version that satisfies the requirement koalas (from versions: )
No matching distribution found for koalas
`

**Comment by thunterdb** [comment]
Hello @shril are you sure that you are running pip3? The package is not published for python2. Can you try with the `--verbose` flag and report the complete log?

**Comment by shril** [comment]
Hi @thunterdb,
I was trying to install it in the Windows 10 environment. There is some version mismatch issue with Apache Arrow.
Now I have shifted to Ubuntu 18 and things are working.
