### ISSUE TITLE
Weird behavior with Series.map

### ISSUE THREAD

**Issue by jpoletti** [databricks/koalas#1925]
I have an issue with the following piece of code:

```python
def lang_func(x):`
    try:
        if "abc" in x:     
            return "lang_1"                   
        elif "xyz" in x                        
            return "lang_2"                  
    except TypeError:                                  
        return np.nan

df["language"] = df["domain"].map(lang_func)
```                 
Up until this point the code runs without warnings, but if I add `print_df` to see the results, I get [this Py4j error](https://pastebin.com/ZNaDCcWD). I get similar errors when trying to see the resulting dataframe with `df` (I'm using jupyter lab) and when trying to use `df["language"].to_pandas()`

Thanks in advance.

**Comment by HyukjinKwon** [comment]
@jpoletti, can you show your data and full codes to reproduce?

**Comment by jpoletti** [comment]
Hi, @HyukjinKwon, after a lot of reading i found what seems to be the problem, together with the solution:
https://stackoverflow.com/questions/62109276/errorjava-lang-unsupportedoperationexception-for-pyspark-pandas-udf-documenta
Looks like  an issue with Arrow, PySpark and Java 11, that can be solved by adding 2 lines in `spark-defaults.conf`.

**Comment by HyukjinKwon** [comment]
Thanks @jpoletti
