### ISSUE TITLE
How to Insert data to SQL

### ISSUE THREAD

**Issue by shakirshakeelzargar** [databricks/koalas#1973]
I want to insert data into SQL using koalas dataframe, but i dont see to_sql method available. Is there any way to insert the data into database?

**Comment by HyukjinKwon** [comment]
You can use [DataFrame.to_spark_io](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.to_spark_io.html#databricks.koalas.DataFrame.to_spark_io) to insert. I think it might be better to show more examples there.
