### ISSUE TITLE
Support for DateTime Index in Koalas

### ISSUE THREAD

**Issue by shril** [databricks/koalas#1976]
Discussion in this PR #1968.
cc: @itholic, @HyukjinKwon

**Comment by ueshin** [comment]
FYI: We started working on it #2025.

**Comment by ueshin** [comment]
The PR was merged.
@shril Do you want to add the method you need in `DatetimeIndex`?

**Comment by itholic** [comment]
Close this since we have `DatatimeIndex` now.

Please feel free to submit a PR to add the method for `DatetimeIndex` anytime :-)
