### ISSUE TITLE
Type inference not consistent with pandas

### ISSUE THREAD

**Issue by dbanda** [databricks/koalas#1981]
The behavior of creating a dataframe with mixed types is different in Koalas from that in Pandas.  Pandas correctly infers that the type of a column with mixed types should be `object`.  

Example:

```
>>> a = pd.DataFrame({'col1': [1, 'a'], 'col2': [3, 4]})
>>> a.dtypes
col1    object
col2     int64
dtype: object
>>> b = ks.DataFrame({'col1': [1, 'a'], 'col2': [3, 4]}) # throws error
```

This behavior isn't clear from the documentation as https://koalas.readthedocs.io/en/latest/user_guide/types.html implies that the Pandas object type is fully supported.

There are many real-world unclean datasets where types are mixed. It would be nice if Koalas could support them in a Pandas like way.

**Comment by itholic** [comment]
Thanks for the interest to Koalas, @dbanda.
Koalas doesn't support mixed type since its internal Spark DataFrame doesn't support mixed type, neither.
Hope we can support mixed type in the near future, but let me just mention this limitations to our documents for now.
