### ISSUE TITLE
Supporting nullable data types for float data, Float32 and Float64

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#2009]
pandas experimentally starts to support [nullable data types for float data](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#experimental-nullable-data-types-for-float-data), Float32 and Float64 from pandas 1.2.

The difference from the existing float32 and float64 as below.

```python
# the default NumPy float64 dtype
In [11]: s1 = pd.Series([1.5, None])

In [12]: s1
Out[12]: 
0    1.5
1    NaN
Length: 2, dtype: float64

In [13]: s1 > 1
Out[13]: 
0     True
1    False
Length: 2, dtype: bool
```

```python
# the new nullable float64 dtype
In [14]: s2 = pd.Series([1.5, None], dtype="Float64")

In [15]: s2
Out[15]: 
0     1.5
1    <NA>
Length: 2, dtype: Float64

In [16]: s2 > 1
Out[16]: 
0    True
1    <NA>
Length: 2, dtype: boolean
```

**Comment by ueshin** [comment]
I'm investigating them as well as `Int64`, `Int32`, etc. or `boolean`, `string` types.
