### ISSUE TITLE
iterating through groups in a for loop

### ISSUE THREAD

**Issue by chogg** [databricks/koalas#2014]
I would like to iterate through groups in a dataframe. This is possible in pandas, but when I port this to koalas, I get an error.

```
import databricks.koalas as ks
import pandas as pd

pdf = pd.DataFrame({'x':range(3), 'y':['a','b','b'], 'z':['a','b','b']})

# Create a Koalas DataFrame from pandas DataFrame
df = ks.from_pandas(pdf)

for a in df.groupby('x'):
    print(a)

```

Here is the error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-35-d4164d1f71e0> in <module>
----> 1 for a in df.groupby('x'):
      2     print(a)

/opt/conda/lib/python3.7/site-packages/databricks/koalas/groupby.py in __getitem__(self, item)
   2630         if self._as_index and is_name_like_value(item):
   2631             return SeriesGroupBy(
-> 2632                 self._kdf._kser_for(item if is_name_like_tuple(item) else (item,)),
   2633                 self._groupkeys,
   2634                 dropna=self._dropna,

/opt/conda/lib/python3.7/site-packages/databricks/koalas/frame.py in _kser_for(self, label)
    721         Name: id, dtype: int64
    722         """
--> 723         return self._ksers[label]
    724 
    725     def _apply_series_op(self, op, should_resolve: bool = False):

KeyError: (0,)
```

Is this kind of group iteration possible in koalas? The koalas documentation kind of implies it is possible - https://koalas.readthedocs.io/en/latest/reference/groupby.html

I don't know why the name of the group key is getting turned into 0. groupby('x').count() does seem to work.

**Comment by chogg** [comment]
Is this related: https://github.com/databricks/koalas/issues/1770

**Comment by ueshin** [comment]
@chogg Unfortunately, Koalas doesn't support group iterations so far.

**Comment by chogg** [comment]
Thanks for letting me know.

**Comment by chogg** [comment]
@ueshin Do you have any idea of when this might be supported? Does it take a lot of work to implement?

**Comment by itholic** [comment]
Thanks for the interest in Koalas, @chogg .

Unfortunately there is no clear development plan right now.

Because Koalas deals with large amounts of data, implementing `__iter__` can potentially be fairly dangerous.

You can also find the related discussion in the past from [here](https://github.com/databricks/koalas/issues/319) and [here](https://github.com/databricks/koalas/issues/1003).

**Comment by itholic** [comment]
Let me close this, since we don't want to have this feature for now since it's too dangerous as mentioned in https://github.com/databricks/koalas/issues/2014#issuecomment-765056672.

**Comment by DavidCamposDSB** [comment]
Hello! What's the actual status for this? Still not being in consideration?
