### ISSUE TITLE
Pandas doesn't require matplotlib, koalas shouldn't either. 

### ISSUE THREAD

**Issue by jimfulton** [databricks/koalas#2023]
Pandas will use `matplotlib` if it's available, but `matplotlib` isn't a dependency if Pandas.

We're deploying batch-processing applications for use in data pipelines, which will never try to plot anything and don't need `matplotlib`.

We are required to scan our deployments with Veracode, and Veracode raises many issues with `matplotlib` and `matplotlib`'s dependencies.

We can work around this by replacing `databricks.koalas.plot.KoalasPlotAccessor` with a `unittest.mock.MagicMock`, but that's evil. :)

Koalas shouldn't require `matplotlib`.

**Comment by HyukjinKwon** [comment]
Yeah, I think we can keep it as an optional dependency

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/koalas/pull/2029

**Comment by jimfulton** [comment]
Thanks!

**Comment by jimfulton** [comment]
I don't want to seem ungrateful, but when might this be released? :)

**Comment by HyukjinKwon** [comment]
:-). likely next week or a week after the next week. Just realised that https://koalas.readthedocs.io/en/latest/development/contributing.html#release-guide is outdated. Let me update it soon. thanks for the head up
