### ISSUE TITLE
pip installed failed on EMR

### ISSUE THREAD

**Issue by piyushcse29** [databricks/koalas#2030]
FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…
Collecting koalas
  Downloading https://files.pythonhosted.org/packages/1d/91/58c88fc3221d7c21d854d7d9c0fe081bf1ac244c1e4496bb2b56e1f31e25/koalas-1.6.0-py3-none-any.whl (668kB)
Requirement already satisfied: numpy>=1.14 in /usr/local/lib64/python3.7/site-packages (from koalas)
Collecting pyarrow>=0.10 (from koalas)
  Downloading https://files.pythonhosted.org/packages/62/d3/a482d8a4039bf931ed6388308f0cc0541d0cab46f0bbff7c897a74f1c576/pyarrow-3.0.0.tar.gz (682kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-build-if6ktjjx/pyarrow/setup.py", line 37, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /mnt/tmp/pip-build-if6ktjjx/pyarrow/

**Comment by ueshin** [comment]
Seems like it's failing to install pyarrow 3.0.0. Could you try with pyarrow 2.0.0? Thanks!

**Comment by piyushcse29** [comment]
Yes, working with pyarrow 2.0.0. Hope you can make it compatible. Thanks.

**Comment by ueshin** [comment]
Actually Koalas does work with pyarrow 3.0.0 as you can see in #2031.
The problem is the pyarrow installation which is out of our control.
I'm afraid you should ask the pyarrow community.
Thanks.
