### ISSUE TITLE
Problem with Loc / Index

### ISSUE THREAD

**Issue by FJLD** [databricks/koalas#2043]
I'm trying to use this code from Jupyter Lab to Databricks:

`df=df[df.columns.drop(df.loc[:,df.columns.str.contains("cod|DES|rut|razon", regex=True)])]`

 but it doesn't work raising this Error:
/databricks/python/lib/python3.7/site-packages/databricks/koalas/indexing.py:1166: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if label == key or label[0] == key:

KeyError: "['False'] not in index"

Then I tried running the code by parts and discover that the follow segment of the code generate a numpy.ndarray
`type(df.columns.str.contains("cod|DES|rut|razon", regex=True))` 
instead to get a ks Data frame...

So I tried to recast this numpy.ndarray to a ks.dataframe but still doesn't work...
`df=df[df.columns.drop(df.loc[:,(ks.DataFrame(df.columns.where.contains("cod|DES|rut|razon", regex=True)))])]`

I got this keyerror  KeyError: "['0'] not in index".

Please help me to figure out how to solve this issue or tell me another way to drop columns that contain some conditions.

**Comment by ueshin** [comment]
I guess `df[df.columns[~df.columns.str.contains("cod|DES|rut|razon", regex=True)]]` should work?

**Comment by ueshin** [comment]
Btw, we should support bool list-like object for `loc` indexer.

```py
>>> df
     a    b
0  1.0  NaN
1  2.0  1.0
2  NaN  NaN
>>> df.columns.str.contains("a", regex=True)
array([ True, False])
>>> df.loc[:, df.columns.str.contains("a", regex=True)]
Traceback (most recent call last):
...
KeyError: "['True'] not in index"
```

whereas:

```py
>>> pdf.loc[:, pdf.columns.str.contains("a", regex=True)]
     a
0  1.0
1  2.0
2  NaN
```

Then, we can

```py
>>> pdf.loc[:, ~pdf.columns.str.contains("a", regex=True)]
     b
0  NaN
1  1.0
2  NaN
```

Thanks for the report, @FJLD!

**Comment by FJLD** [comment]
> ~df.columns.str.contains("cod|DES|rut|razon", regex=True)]]

Ty @ueshin the cade that you give work perfectly :)
