### ISSUE TITLE
High level question about Koalas

### ISSUE THREAD

**Issue by icexelloss** [databricks/koalas#205]
Hi folks!

I just learned about Koalas and it looks very cool!

I have some high level questions about Koalas and wondering what's your guys thoughts on these:

- Is Koalas eagerly evaluation or lazy evaluation or mixture? I currently found some operations, like `df['x']` being eager and `df.head()` being lazy, so curious about what is the design philosophy here.

- When certain behavior is inconsistent between Spark and Pandas, does Koalas match Spark or Pandas behavior? For example, `groupby('x').sum()` behavior:

```
>>> pdf = pd.DataFrame({'x':range(3), 'y':['a', 'b', 'b'], 'z':['a', 'b' ,'b']} )
>>> df = ks.from_pandas(pdf)

>>> df.groupby('x').sum().show()
+---+----------------------+------+
|  x|sum(__index_level_0__)|sum(x)|
+---+----------------------+------+
|  0|                     0|     0|
|  1|                     1|     1|
|  2|                     2|     2|
+---+----------------------+------+

>>> df.toPandas().groupby('x').sum()
   y  z
x      
0  a  a
1  b  b
2  b  b
```

**Comment by rxin** [comment]
1. It is currently lazy, but when a variable's repl_html or repr_string is called, it eagerly evaluates that to more closely match what users see with pandas output. I'm thinking it might make sense to have a config so users can turn that behavior off (be completely lazy) in production, so they don't trigger too many big data operations. Any thoughts here?

2. It should match pandas. GroupBy is one exception because we are still updating it. Once https://github.com/databricks/koalas/pull/194 is done, groupby will match pandas.

**Comment by HyukjinKwon** [comment]
I think it already works moderately. At the core, it's lazy but if we use notebook or interpreter, it can work like it's eager No strong opinion on adding a configuration but I suspect the configuration isn't very much useful.

**Comment by icexelloss** [comment]
Got it. My thoughts are it should probably be lazy as well. Eager computation is nice when Demoing or playing with trivial data but breaks pretty fast when user start to play with non trivial data. I am also skeptical about the config because that config changes the fundamental behavior and user would have to learn to use the library in two fundamentally different ways.

I do like the fact that when I type `df['x']` I can immediately see the result but also realize it probably won't work very well if shuffle is involved.

**Comment by HyukjinKwon** [comment]
There is a tradeoff, yes. The current direction of this project is to stick to lazy evaluation :-). I am resolving this ticket.
