### ISSUE TITLE
datetime support for min and max functions

### ISSUE THREAD

**Issue by franperezlopez** [databricks/koalas#2068]
It looks to me I'm doing something wrong, but I can't find the reason.

![image](https://user-images.githubusercontent.com/1222398/109346947-b1d40880-7872-11eb-91c2-d3b3a0c4943d.png)

It seems that when I select the row using min / max functions, an additional hour is added to the date. The same example using pandas works fine. Could you please help me?

**Comment by ueshin** [comment]
Hi @franperezlopez, Thanks for the report!

Actually I couldn't reproduce the behavior in my local, but I had something in mind and submitted a PR #2077.
Could you help test the PR in your end?

**Comment by franperezlopez** [comment]
Hi, I'm sorry but I had no time for testing your branch ... did you try updating the local time of your machine? I live in UTC+1 so I presumed the difference was because that

**Comment by ueshin** [comment]
Hi @francopatano, I merged the PR. Could you try with the latest master? Thanks!

**Comment by franperezlopez** [comment]
works on my machine 👍 

thanks for the fix. keep up the good work!!

**Comment by ueshin** [comment]
Thanks again for the report and confirming!
