### ISSUE TITLE
groupby and compute.max_rows ?

### ISSUE THREAD

**Issue by lfdversluis** [databricks/koalas#2072]
When using `groupby` and then `apply` will the pandas dataframe supplied to the function to be applied have at most `compute.max_rows` rows? I cannot reliably tell from [the documentation](https://koalas.readthedocs.io/en/latest/user_guide/options.html) if this also applies to groupby. 

I am applying a function per group, where a group may very well exceed the 100k rows. Will the function then get chunks (and thus lead to incorrect results for me) or will in such a case a Pandas dataframe with all the rows be passed to my function?

**Comment by ueshin** [comment]
Hi @lfdversluis,

No, `groupby-apply` doesn't check `compute.max_rows` and the whole data in each group will be passed to the function.

Could you share the reproducible example that seems incorrect?

Thanks.

**Comment by lfdversluis** [comment]
Thanks for your answer. It was just a question as I am struggling with Memory issues, and I was checking the documentation on how to manage this. Knowing the groupby does provide the full group the my function is good to know. May I suggest that this is emphasized in the documentation, just in case anyone else has this question :)
