### ISSUE TITLE
Series.isin() throws exception when fed numpy array

### ISSUE THREAD

**Issue by lfdversluis** [databricks/koalas#2098]
Running Spark 3.1.1 with Pyspark 3.1.1. and Koalas 1.7.0
```
df = pd.DataFrame({'a': [1, 2, 3], 'b': [2, 3, 4]})
numpy_arr = np.array([3, 4, 5])
df['a'].isin(numpy_arr)
```
works

```
kdf = ks.from_pandas(df)
kdf[kdf['a'].isin(numpy_arr)]
```

throws `AttributeError: 'numpy.int64' object has no attribute '_get_object_id'`

using `numpy_arr.tolist()` fixes it. Is this deviation from the Pandas API intended?

**Comment by itholic** [comment]
Thanks for the report, @lfdversluis :)
It seems like bug in Koalas.
Just submitted PR at #2103
