### ISSUE TITLE
Self-merge result is unlike PySpark or Pandas

### ISSUE THREAD

**Issue by TempestVanSchaik** [databricks/koalas#2115]
When I do a self-merge in Koalas, I get a result that is inconsistent with both PySpark and Pandas. 

Example small dataframe:

``` 
user_colname = 'UserID'
course_colname = 'CourseID'
data_dict = {user_colname: [1, 1, 1, 2, 2],
              course_colname: ['a', 'b', 'c', 'a', 'c']}
df = pd.DataFrame(data_dict)
```

A self join in Pandas 
`merge_df = df.merge(df, on='UserID', how='inner')`
results in the expected
![image](https://user-images.githubusercontent.com/9007411/112083487-85539980-8b5d-11eb-95c0-0733444341be.png)

A self join in PySpark
```
sdf = spark.createDataFrame(df) 
merge_df = sdf.join(sdf, on='UserID', how='inner')
```

results in the same
![image](https://user-images.githubusercontent.com/9007411/112083971-699cc300-8b5e-11eb-8672-1f4dbe58a112.png)

However, when converting to Koalas and then doing the merge, the result doesn't make sense:
```
kdf = sdf.to_koalas()
merge_kdf = kdf.merge(kdf, on='UserID', how='inner')
```
And here is the output. Not as expected because we have duplicate rows:
![image](https://user-images.githubusercontent.com/9007411/112149761-b495f500-8bb5-11eb-9a16-3b8cc9c075f5.png)

**Comment by ueshin** [comment]
Hi @TempestVanSchaik, Thanks for the report!

Which version of Koalas are you using?
I guess this is the same issue as #2055, which was fixed at ##2060 and included in Koalas 1.7.0.

With Koalas 1.7.0:

```py
>>> ks.__version__
'1.7.0'
>>> kdf = ks.from_pandas(df)
>>> kdf.merge(kdf, on='UserID', how='inner')
    UserID CourseID_x CourseID_y
0        1          a          a
1        1          a          b
2        1          a          c
3        1          b          a
4        1          b          b
5        1          b          c
6        1          c          a
7        1          c          b
8        1          c          c
9        2          a          a
10       2          a          c
11       2          c          a
12       2          c          c
```
