### ISSUE TITLE
why kdf.head() is much lower than sdf.show()?

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#2139]
```python
sdf = read_csv('backflow.csv')
kdf = sdf.to_koalas()

# run time 75ms
sdf.show(5)

# run time 53s
kdf.head()
```

![image](https://user-images.githubusercontent.com/23121539/113799929-a08eed80-9788-11eb-8e6e-7b8e60787f30.png)

![image](https://user-images.githubusercontent.com/23121539/113800186-185d1800-9789-11eb-9f12-bff0d2ed1e75.png)

kdf.head() is much lower than sdf.show().Is there any way to speed it up in koalas?

**Comment by HyukjinKwon** [comment]
Very likely because of the default index: https://koalas.readthedocs.io/en/latest/user_guide/options.html#default-index-type . Can you try with `ks.set_option('compute.default_index_type', 'distributed')`?

**Comment by RainFung** [comment]
It's much faster now. Can we set it to `distributed` by default.  The speed gap is too big.

**Comment by HyukjinKwon** [comment]
`distributed` disables the operations between other DataFrames. It's something we should discuss. Let me close this ticket for now though.
