### ISSUE TITLE
Support Series.str.len()

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#2140]
```python
df['col_sum'] = df['col'].str.slice(2, 2+7).replace('0', '').len()
AttributeError: 'Series' object has no attribute 'len'
```

**Comment by LSturtew** [comment]
Series.str.len() is already implemented: https://github.com/databricks/koalas/blob/0fd088e9f142177ef2a80b41d095a49c40320b2a/databricks/koalas/strings.py#L1244-L1276

**Comment by RainFung** [comment]
Thanks.
