### ISSUE TITLE
How to run Koalas script as a normal python program

### ISSUE THREAD

**Issue by priyankadas87** [databricks/koalas#2153]
my code is having koalas dataframes and few operations on koalas dataframes. I am able to run the script with spark submit , but not able to run as a normal pyhton code.
RUn Command:
python3 test.py 

It is asking for Spark.
    "Unable to import pyspark - consider doing a pip install with [spark] "
ImportError: Unable to import pyspark - consider doing a pip install with [spark] extra to install pyspark with pip

**Comment by itholic** [comment]
Could you try to refer the [Installation guide](https://koalas.readthedocs.io/en/latest/getting_started/install.html) on official documents ??

**Comment by priyankadas87** [comment]
I have installed koalas using pip as described in that official doc. I am able to run the program using spark . But I was assuming that same koalas code would be running in normal python (without spark) - python3 main.py .
But when I am running using python , it is asking for Spark.
Is there any provision to run koalas code as a python code or it needs to be executed with Spark?

**Comment by HyukjinKwon** [comment]
You'll probably need to set `PYTHON_PATH` properly, see https://spark.apache.org/docs/latest/api/python/getting_started/install.html?highlight=pythonpath#manually-downloading
