### ISSUE TITLE
Having PyArrow issues while reading excel file using koalas.read_excel()

### ISSUE THREAD

**Issue by Akashdesarda** [databricks/koalas#2159]
I am trying to read an excel file using koalas. I am getting `ArrowTypeError: Expected bytes, got a 'int' object` error, which I believe is related to Pyarrow. But it works without any issue in pandas

Koalas version
---
```python
from pyspark.sql import SparkSession
import pandas as pd
import databricks.koalas as ks

kdf = ks.read_excel('100717_ChromaCon_AG_PPA_Template_v9.xlsx')
```
```python
# Compete tracback
---------------------------------------------------------------------------
ArrowTypeError                            Traceback (most recent call last)
<ipython-input-7-7a1270f26d17> in <module>
----> 1 kdf = ks.read_excel('100717_ChromaCon_AG_PPA_Template_v9.xlsx')

~/anaconda3/lib/python3.8/site-packages/databricks/koalas/namespace.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, **kwds)
   1094             )
   1095         else:
-> 1096             return cast(Union[DataFrame, Series], from_pandas(pdf_or_psers))
   1097     else:
   1098 

~/anaconda3/lib/python3.8/site-packages/databricks/koalas/namespace.py in from_pandas(pobj)
    123         return Series(pobj)
    124     elif isinstance(pobj, pd.DataFrame):
--> 125         return DataFrame(pobj)
    126     elif isinstance(pobj, pd.Index):
    127         return DataFrame(pd.DataFrame(index=pobj)).index

~/anaconda3/lib/python3.8/site-packages/databricks/koalas/frame.py in __init__(self, data, index, columns, dtype, copy)
    508             else:
    509                 pdf = pd.DataFrame(data=data, index=index, columns=columns, dtype=dtype, copy=copy)
--> 510             internal = InternalFrame.from_pandas(pdf)
    511 
    512         object.__setattr__(self, "_internal_frame", internal)

~/anaconda3/lib/python3.8/site-packages/databricks/koalas/internal.py in from_pandas(pdf)
   1353 
   1354         schema = StructType(
-> 1355             [
   1356                 StructField(
   1357                     name, infer_pd_series_spark_type(col, dtype), nullable=bool(col.isnull().any()),

~/anaconda3/lib/python3.8/site-packages/databricks/koalas/internal.py in <listcomp>(.0)
   1355             [
   1356                 StructField(
-> 1357                     name, infer_pd_series_spark_type(col, dtype), nullable=bool(col.isnull().any()),
   1358                 )
   1359                 for (name, col), dtype in zip(pdf.iteritems(), index_dtypes + data_dtypes)

~/anaconda3/lib/python3.8/site-packages/databricks/koalas/typedef/typehints.py in infer_pd_series_spark_type(pser, dtype)
    318             return pser.iloc[0].__UDT__
    319         else:
--> 320             return from_arrow_type(pa.Array.from_pandas(pser).type)
    321     elif isinstance(dtype, CategoricalDtype):
    322         # `pser` must already be converted to codes.

~/anaconda3/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib.Array.from_pandas()

~/anaconda3/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

~/anaconda3/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib._ndarray_to_array()

~/anaconda3/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowTypeError: Expected bytes, got a 'int' object
```

Pandas Version
---
```python
from pyspark.sql import SparkSession
import pandas as pd
import databricks.koalas as ks

pdf = pd.read_excel('100717_ChromaCon_AG_PPA_Template_v9.xlsx')
```
## Output
![image](https://user-images.githubusercontent.com/26931751/118584508-b1ce0f80-b7b4-11eb-8819-c3250fb44020.png)

Package version
---
I followed the Installation guide using conda from the official guide [here](https://koalas.readthedocs.io/en/latest/getting_started/install.html).

```
# Name                    Version                   Build         Channel
koalas                    1.8.0              pyhd8ed1ab_0    conda-forge
pandas                    1.2.4            py38h1abd341_0    conda-forge
pyspark                   3.1.1              pyh44b312d_0    conda-forge
pyarrow                   4.0.0           py38hc9229eb_4_cpu    conda-forge
py4j                      0.10.9             pyh9f0ad1d_0    conda-forge
numpy                     1.19.5           py38h18fd61f_1    conda-forge
```

**Comment by HyukjinKwon** [comment]
Can you try lower versions of pyarrow? I think the latest pyarrow has not been tested thoroughly with Koalas.

**Comment by Akashdesarda** [comment]
I have tried multiple version- 4.0.0, 3.00, 2.0.0, but all this are giving same error as shown above.

**Comment by itholic** [comment]
Now it's working fine with all version of `PyArrow` in the latest Koalas.

**Comment by patchatarch** [comment]
Hello, I've been experiencing the same issue with koalas.read_excel in databricks

```python
import databricks.koalas as ks
from kenv import filepath

df = ks.read_excel(filepath, engine='openpyxl')
```

Traceback:
```python
---------------------------------------------------------------------------
ArrowTypeError                            Traceback (most recent call last)
<[command-4445833489352705]()> in <module>
----> 1 df = ks.read_excel(filepath, engine='openpyxl')

/databricks/python/lib/python3.8/site-packages/databricks/koalas/usage_logging/__init__.py in wrapper(*args, **kwargs)
    193             start = time.perf_counter()
    194             try:
--> 195                 res = func(*args, **kwargs)
    196                 logger.log_success(
    197                     class_name, function_name, time.perf_counter() - start, signature

/databricks/python/lib/python3.8/site-packages/databricks/koalas/namespace.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, **kwds)
   1094             )
   1095         else:
-> 1096             return cast(Union[DataFrame, Series], from_pandas(pdf_or_psers))
   1097     else:
   1098 

/databricks/python/lib/python3.8/site-packages/databricks/koalas/usage_logging/__init__.py in wrapper(*args, **kwargs)
    188         if hasattr(_local, "logging") and _local.logging:
    189             # no need to log since this should be internal call.
--> 190             return func(*args, **kwargs)
    191         _local.logging = True
    192         try:

/databricks/python/lib/python3.8/site-packages/databricks/koalas/namespace.py in from_pandas(pobj)
    123         return Series(pobj)
    124     elif isinstance(pobj, pd.DataFrame):
--> 125         return DataFrame(pobj)
    126     elif isinstance(pobj, pd.Index):
    127         return DataFrame(pd.DataFrame(index=pobj)).index

/databricks/python/lib/python3.8/site-packages/databricks/koalas/usage_logging/__init__.py in wrapper(*args, **kwargs)
    188         if hasattr(_local, "logging") and _local.logging:
    189             # no need to log since this should be internal call.
--> 190             return func(*args, **kwargs)
    191         _local.logging = True
    192         try:

/databricks/python/lib/python3.8/site-packages/databricks/koalas/frame.py in __init__(self, data, index, columns, dtype, copy)
    508             else:
    509                 pdf = pd.DataFrame(data=data, index=index, columns=columns, dtype=dtype, copy=copy)
--> 510             internal = InternalFrame.from_pandas(pdf)
    511 
    512         object.__setattr__(self, "_internal_frame", internal)

/databricks/python/lib/python3.8/site-packages/databricks/koalas/internal.py in from_pandas(pdf)
   1354 
   1355         schema = StructType(
-> 1356             [
   1357                 StructField(
   1358                     name, infer_pd_series_spark_type(col, dtype), nullable=bool(col.isnull().any()),

/databricks/python/lib/python3.8/site-packages/databricks/koalas/internal.py in <listcomp>(.0)
   1356             [
   1357                 StructField(
-> 1358                     name, infer_pd_series_spark_type(col, dtype), nullable=bool(col.isnull().any()),
   1359                 )
   1360                 for (name, col), dtype in zip(pdf.iteritems(), index_dtypes + data_dtypes)

/databricks/python/lib/python3.8/site-packages/databricks/koalas/typedef/typehints.py in infer_pd_series_spark_type(pser, dtype)
    325             return pser.iloc[0].__UDT__
    326         else:
--> 327             return from_arrow_type(pa.Array.from_pandas(pser).type)
    328     elif isinstance(dtype, CategoricalDtype):
    329         # `pser` must already be converted to codes.

/databricks/python/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib.Array.from_pandas()

/databricks/python/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

/databricks/python/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib._ndarray_to_array()

/databricks/python/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowTypeError: Expected bytes, got a 'int' object
```

Im using versions:
koalas=1.8.1
pyarrow=4.0.0

I quite don't understand what I'm doing wrong.
Can anyone point me to the right direction please.
Appreciate your help in advance.

**Comment by itholic** [comment]
Can you show how the excel data looks like you try to read ??

Btw, can you try to use pandas API on Spark instead of Koalas ??

```python
import pyspark.pandas as ps
from kenv import filepath

df = ps.read_excel(filepath, engine='openpyxl')
```

Koalas is ported into PySpark, under the name of [pandas API on Spark](https://spark.apache.org/docs/latest/api/python/user_guide/pandas_on_spark/index.html), and Koalas now is only in maintenance mode.

**Comment by patchatarch** [comment]
`pyspark.pandas` is not working for me

```python
import pyspark.pandas as ps
```
```python
ModuleNotFoundError: No module named 'pyspark.pandas'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<[command-4445833489352706]()> in <module>
----> 1 import pyspark.pandas as ps
      2 filepath = '/mnt/axeria/SFAM Claims 08-2021.xlsx'

/databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py in import_patch(name, globals, locals, fromlist, level)
    156             # Import the desired module. If you’re seeing this while debugging a failed import,
    157             # look at preceding stack frames for relevant error information.
--> 158             original_result = python_builtin_import(name, globals, locals, fromlist, level)
    159 
    160             is_root_import = thread_local._nest_level == 1

ModuleNotFoundError: No module named 'pyspark.pandas'
```

I'm using `databricks runtime` version `9.1 LTS` and `pyspark` version `3.2.1`
yet its giving me an `ModuleNotFoundError` upon import.

And for the excel data. This is the sample format of the data I was trying to read.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BILLIO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BILLIO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



CONTRAT | DATE_CONTRAT | TYPE_SINISTRE | DATE_DECLARATION | ID_SINISTRE | FORMULE_DETAILLEE | REGROUPEMENT_FORMULE | IMEI | MARQUE/MODELE | DATE_DE_LA_DECISION | REPARATEUR | DATE_SURVENANCE | DATE_DOSSIER_COMPLET | AGENCE | AGENCE_TETE_GROUPE | ID_SINISTRE_ORIGINE | FAMILLE_PRODUIT_SINISTRE | STATUT_SINISTRE | GESTE_CO_DATE | PAYS | MONTANT_FRANCHISE | MONTANT_TOTAL_SINISTRE | TYPOLOGIE_INDEMNISATION | DATE_REGLEMENT_MAX | MOTIF_REFUS | SOUS_MOTIF_REFUS | PROVISION | SAV
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BE100148 | 4/15/2016 | casse | 4/29/2016 | SIN87622 | INTEGRALE | INTEGRALE | 0 | ONEPLUS ONE SANDSTONE | 5/24/2016 |   | 4/28/2016 | 5/24/2016 | FNAC LOUVAIN LA NEUVE | FNAC BELGIQUE |   | telephony | clos echange |   | BELGIQUE | 0 | 299 | INDEMNISATION | 5/24/2016 |   |   | 0 |  
BE100385 | 4/27/2016 | casse | 5/11/2016 | SIN88895 | INFINITY | INFINITY | 357329073793665 | SAMSUNG GALAXY S7 EDGE 32G | 6/2/2016 |   | 5/7/2016 | 6/2/2016 | FNAC LOUVAIN LA NEUVE | FNAC BELGIQUE |   | telephony | clos repare |   | BELGIQUE | 0 | 295 | INDEMNISATION | 6/2/2016 |   |   | 0 |  
BE100379 | 4/27/2016 | casse | 5/12/2016 | SIN89170 | INTEGRALE | INTEGRALE | SDMPLWGURF4YH | APPLE IPAD 2 | 7/5/2016 |   | 4/27/2016 | 7/5/2016 | FNAC LIEGE | FNAC BELGIQUE |   | multimedia | clos repare |   | BELGIQUE | 0 | 329 | INDEMNISATION | 7/5/2016 |   |   | 0 |  
BE100239 | 4/18/2016 | vol | 5/18/2016 | SIN89821 | INFINITY | INFINITY | 355691072593616 | APPLE IPHONE 6S 16 G | 6/2/2016 |   | 5/14/2016 | 6/2/2016 | FNAC LIEGE | FNAC BELGIQUE |   | telephony | clos echange |   | BELGIQUE | 0 | 749 | INDEMNISATION | 6/2/2016 |   |   | 0 |  
BE100416 | 4/29/2016 | casse | 5/19/2016 | SIN89866 | INFINITY | INFINITY | 0000000000 | APPLE IPHONE SE 16 GO | 5/24/2016 |   | 5/18/2016 | 5/24/2016 | FNAC LIEGE | FNAC BELGIQUE |   | telephony | clos echange |   | BELGIQUE | 0 | 24.99 | INDEMNISATION | 5/24/2016 |   |   | 0 |  
BE100250 | 4/19/2016 | vol | 5/31/2016 | SIN91353 | INFINITY | INFINITY | 353609071309711 | SAMSUNG GALAXY S6 | 6/16/2016 |   | 5/30/2016 | 6/16/2016 | FNAC LOUVAIN LA NEUVE | FNAC BELGIQUE |   | telephony | clos echange |   | BELGIQUE | 0 | 498.95 | INDEMNISATION | 6/16/2016 |   |   | 0 |  
BE100602 | 5/13/2016 | casse | 6/10/2016 | SIN92735 | INTEGRALE | INTEGRALE | 0. | SAMSUNG GALAXY S7 EDGE 32G | 6/16/2016 |   | 6/9/2016 | 6/16/2016 | FNAC LOUVAIN LA NEUVE | FNAC BELGIQUE |   | telephony | clos echange | 6/16/2016 | BELGIQUE | 0 | 90 | INDEMNISATION | 6/16/2016 |   |   | 0 |  
BE101315 | 6/2/2016 | perte | 6/13/2016 | SIN92921 | INFINITY | INFINITY | 355417075157138 | APPLE IPHONE 6S 64G | 6/20/2016 |   | 6/11/2016 | 6/20/2016 | FNAC TOISON D'OR | FNAC BELGIQUE |   | telephony | clos echange |   | BELGIQUE | 0 | 859 | INDEMNISATION | 6/20/2016 |   |   | 0 |  
BE100908 | 5/25/2016 | casse | 6/15/2016 | SIN93461 | INFINITY | INFINITY | 864324027984490 | HUAWEI ASCEND G7 | 7/7/2016 |   | 6/11/2016 | 7/7/2016 | FNAC LIEGE | FNAC BELGIQUE |   | telephony | clos echange |   | BELGIQUE | 0 | 279.99 | INDEMNISATION | 7/7/2016 |   |   | 0 |  



</body>

</html>

**Comment by itholic** [comment]
Thanks for the information.

pandas API on Spark has been supported from PySpark 3.2, so would you mind upgrading PySpark version and retry?

If you're using Databricks Notebook, you can install the PySpark 3.2 with `%pip install pyspark==3.2`, FYI.

**Comment by itholic** [comment]
Would you mind using upper version of LTS that supports PySpark 3.2 or above, since pandas API on Spark is supported from PySpark 3.2 ??

Or maybe can you try with `ks.from_pandas(pd.read_excel(filepath, engine='openpyxl'))` as workaround for now??

**Comment by Trodenn** [comment]
@Akashdesarda have you being able to solve this issue? I am also experiencing the same error at the moment while trying to read an xlsx file with koalas on databricks. The proposed work around does not seem to be working for me. It produces the same error
