### ISSUE TITLE
databricks.koalas.info() doesn't show memory usage

### ISSUE THREAD

**Issue by AliWaheed** [databricks/koalas#2163]
The documentation states that _databricks.koalas.info()_ shows memory usage too but it doesn't in practice. 
It doesn't show memory usage in the examples given in the documentation either.

**Comment by itholic** [comment]
Thanks for the report, @AliWaheed :)
Koalas doesn't show the memory usage.
Seems like it was mistakenly added when copy the pandas' one.
I think we should fix the documents.

**Comment by AliWaheed** [comment]
Got it, thanks for the reply
