### ISSUE TITLE
import koalas return cannot import name 'ignore_unicode_prefix' from 'pyspark.rdd'

### ISSUE THREAD

**Issue by nadanasser** [databricks/koalas#2165]
I installed Spark, Koalas on miniconda3, then when I do 

`import databricks.koalas as ks`

it return error as attached

![image](https://user-images.githubusercontent.com/13717494/120177164-6716b380-c208-11eb-8fbb-31d25f84dcc4.png)

one more thing when I type pyspark in terminal I got

`/home/user/miniconda3/bin/pyspark: line 24: /root/spark/bin/load-spark-env.sh: Permission denied
/home/user/miniconda3/bin/pyspark: line 77: /root/spark/bin/spark-submit: Permission denied
/home/user/miniconda3/bin/pyspark: line 77: exec: /root/spark/bin/spark-submit: cannot execute: Permission denied
`

I do not know what I missed, appreciate your support

I am using Ubuntu 18.04.4
python 3.7.7
conda 4.10.1

**Comment by HyukjinKwon** [comment]
Looks like pyspark is not properly in the Python path. do you have other pyspark installed?

**Comment by itholic** [comment]
Close because the reporter has not responded for a while.

Please reopen at any time if there is any something to discuss!
