### ISSUE TITLE
when using df.astype(str), the null value change to 'nan'?

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#2169]
when using df.astype(str), the null value change to 'nan'?

**Comment by RainFung** [comment]
Is there a way to keep null value ?

**Comment by itholic** [comment]
Could you give some more detail about the issue??

For me, the null values are changed to `None`, not `nan` from my side??

```python
>>> ks.DataFrame({"A": [1, 2, None], "B": ["a", "b", None], "C": [False, True, None]}).astype(str)
      A     B      C
0   1.0     a  false
1   2.0     b   true
2  None  None   None
```

**Comment by RainFung** [comment]
When I write the dataframe to database table,  it raise `nan` .
