### ISSUE TITLE
Using read_csv within Databricks to open a local file

### ISSUE THREAD

**Issue by ChuckConnell** [databricks/koalas#2178]
### Discussed in https://github.com/databricks/koalas/discussions/2177

<div type='discussions-op-text'>

<sup>Originally posted by **ChuckConnell** June 29, 2021</sup>
I have imported some code from pandas to Databricks/Koalas. My read_csv statement does not work because the file is local to my computer, not within the Databricks file system (DBFS). I feel like I am missing something obvious. I want my pandas code to work on Databricks/Koalas with minor changes.

I know I can use the Databricks GUI point-and-click to create a DBFS table, then make a DataFrame from the table, but that is not programmatic and is a poor solution if I have hundreds of local files.
 
`import databricks.koalas as ks
myDF = ks.read_csv("C:/Users/chuck/Desktop/County.csv")

java.io.IOException: No FileSystem for scheme: C`
</div>

**Comment by itholic** [comment]
Seems like you cannot read directly from local file path, without uploading your local data into Databricks workspace.

Could you refer to similar discussion at https://forums.databricks.com/questions/22008/how-to-read-local-files-into-dataframe-or-temp-tab.html ?

I'm not sure, but it's worth to checkout S3 or Blob storage if you want to automatically upload your local data into Databricks workspace (also known as DBFS).

**Comment by ChuckConnell** [comment]
This is a big problem. Many pandas programs start with read_csv() of a local file on that computer, not in cloud storage somewhere. 

The lack of this feature in Koalas is a significant barrier to its adoption by pandas users. 

Yes, if there are only a few files, you can manually add them as Databricks tables using the point-and-click GUI method. And yes, you can put the files into S3 or Azure blob and programmatically access them from Databricks. But those are awkward non-intuitive solutions for programmers who are accustomed to opening local files with read_csv().

**Comment by itholic** [comment]
Yeah, I agree that it's pretty annoying process if you have to upload your data into Databricks file system one by one.

But I think maybe you can upload the bunch of files at once via Databricks GUI as following steps ??

1. Click "Data" on your Databricks GUI

![Screen Shot 2021-07-30 at 11 54 38 AM](https://user-images.githubusercontent.com/44108233/127592913-b24bb7a8-b826-4130-851f-15da39599be6.png)

2. Click "DBFS", not "Database Tables", and click "Upload"

![Screen Shot 2021-07-30 at 11 56 27 AM](https://user-images.githubusercontent.com/44108233/127593048-d7ce9a1e-1dad-49db-bac7-00a6402325de.png)

3. Drag & drop your folder that includes bunch of files, not click to browse. You don't need to upload the every single file one by one.

![Screen Shot 2021-07-30 at 11 57 55 AM](https://user-images.githubusercontent.com/44108233/127593163-17915343-097e-498d-97c8-6192807dd680.png)

**Comment by ChuckConnell** [comment]
Ah! Thank you. I will try this. So one point-and-click would be required, to get all the files into DBFS. Then you could programmatically create tables from the DBFS files. That is definitely an improvement. 

It does not help the case where there are new files every day (or hour). But it is a nice feature. 

Will test it. Thank you.

**Comment by ChuckConnell** [comment]
@itholic What version of Databricks are you using on what platform? I just tested on the Community edition and do not see the DBFS option you showed.

**Comment by itholic** [comment]
@ChuckConnell Oh, yeah. Seems like the community version doesn't support the DBFS upload just same as mine.

But you can still upload the local file with one point-and-click in community edition.

1. Click "Data" and "Create Table"

![Screen Shot 2021-08-02 at 1 23 48 PM](https://user-images.githubusercontent.com/44108233/127804104-fc5a825f-4f9e-4954-9e86-37dd32d69840.png)

2. Just drag & drop multiple files on the browser.

![Screen Shot 2021-08-02 at 1 17 31 PM](https://user-images.githubusercontent.com/44108233/127804167-d71022b8-d118-4c11-b703-46cc8e5afa81.png)


3. Check the file paths below.

![Screen Shot 2021-08-02 at 1 17 38 PM](https://user-images.githubusercontent.com/44108233/127804189-5a7786a6-b597-4e92-8a5c-e004c7f967cc.png)


4. Use the given paths in the notebook to load the data with `read_csv`

![Screen Shot 2021-08-02 at 1 21 57 PM](https://user-images.githubusercontent.com/44108233/127804224-100e16c3-ae94-4a62-91c6-736706054469.png)

**Comment by ChuckConnell** [comment]
@itholic Thank you again. I will test it.

**Comment by itholic** [comment]
Thanks for the report, @ChuckConnell !

Close this for now, since it's more actually the limitation of Databricks solution itself rather than Koalas.
