### ISSUE TITLE
[Databricks CE] Koalas df.head() should also print records, similar to Pandas

### ISSUE THREAD

**Issue by sadikovi** [databricks/koalas#220]
It would be great if calling `df.head()` on koalas DataFrame would result in printing records, similar to Pandas. I found that it does not work on Databricks Community Edition.

It would be extremely useful, since there is no other easy way to sample koalas DataFrame now, and people generally use this command for that exact purpose - to get some ideas of what data looks like, and normally they request a fairly small number of records to inspect.

For example,

```python
df = ks.read_parquet("/mnt/ivan/sample2.parquet").toPandas()
df.head()

# Out[40]: 
#    id    a    b  c
# 0   0  abc  def  +
``` 

Koalas right now returns this:
```python
df = ks.read_parquet("/mnt/ivan/sample2.parquet")
df.head()

# Out[42]: <databricks.koalas.frame.DataFrame at 0x7fe134749dd8>
```

**Comment by thunterdb** [comment]
@sadikovi what is your environment? It should work in jupyter, a fix is on the way for databricks.

**Comment by sadikovi** [comment]
Thanks Tim. I am experiencing this issue on Databricks Community Edition, also updated the issue title and description.

**Comment by rxin** [comment]
I think this is fixed in the latest version, which will be released today or tomorrow. The version released last week didn't have the proper string form.

**Comment by rxin** [comment]
@sadikovi I'm going to close this because I think it is fixed in master. When we release 0.2 and if you still see that issue, reopen the ticket.
