### ISSUE TITLE
missing function `koalas.series.apply`

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#2218]
https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html

**Comment by HyukjinKwon** [comment]
@RainFung Koalas project has been migrated to PySpark. Let;s file an issue at Apache Spark JIRA:

BTW, I believe this is already implemented at https://github.com/databricks/koalas/blob/master/databricks/koalas/series.py#L3010-L3141
