### ISSUE TITLE
koalas.DataFrame()

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#23]
based on a conversation with Brooke, we should have a function called `pyspark.DataFrame` that takes the same arguments as `pandas.DataFrame` https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L378 but returns a Spark dataframe. It should be a simple wrapper that calls pyspark.createDataFrame

**Comment by thunterdb** [comment]
The documentation for the function to wrap:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame

**Comment by rxin** [comment]
I renamed this to koalas.DataFrame.

**Comment by brookewenig** [comment]
@thunterdb @rxin Could we do somethings similar for pd.Series too? Tony and I are trying to port over some example pandas documentation code to Koalas, and this is a blocker.

**Comment by HyukjinKwon** [comment]
It works fine against refactoring branch.

```python
>>> from databricks import koalas
>>> import pandas as pd
>>> koalas.Series(pd.Series([1, 2, 3]))
0    1
1    2
2    3
Name: 0, dtype: int64
```

```python
>>> from databricks import koalas
>>>
>>> df = koalas.DataFrame({'x': [1, 2], 'y': [3, 4], 'z': [5, 6]}) # A Spark dataframe
>>>
>>>
>>> # Rename columns
... df.columns = ['x', 'y', 'z1']
>>>
>>> # Do some operations in place
... df['x2'] = df.x * df.x
>>>
>>> df.toPandas()
   x  y  z1  x2
0  1  3   5   1
1  2  4   6   4
```

```python
>>> import pandas as pd
>>>
>>> df = pd.DataFrame({'x': [1, 2], 'y': [3, 4], 'z': [5, 6]}) # A Pandas dataframe
>>>
>>>
>>> # Rename columns
... df.columns = ['x', 'y', 'z1']
>>>
>>> # Do some operations in place
... df['x2'] = df.x * df.x
>>>
>>> df
   x  y  z1  x2
0  1  3   5   1
1  2  4   6   4
```

These tickets will be closed once https://github.com/databricks/koalas/pull/134 is merged.
