### ISSUE TITLE
koalas.concat

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#231]
Similar to https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html#pandas.concat

This is basically a unionAll in Spark.

**Comment by pyMixin** [comment]
This implementation is very different than unionAll of spark. unionAll in spark requires columns to be the same number in both dataframes. pandas.concat doesn't have that requirement. Here some reference: https://stackoverflow.com/questions/37332434/concatenate-two-pyspark-dataframes

**Comment by rxin** [comment]
@pyMixin would you be interested in working on this?

**Comment by tdliu** [comment]
Is someone working on this? This is a super helpful function. 

Example:
`test["target"] = train["target"].mean()`
`all_df = pd.concat([train[["ID", "target"] + cols], test[["ID", "target"]+ cols]]).reset_index(drop=True)`

**Comment by HyukjinKwon** [comment]
I'm gonna take a look
