### ISSUE TITLE
Add Python 2 Support

### ISSUE THREAD

**Issue by ashkan-leo** [databricks/koalas#243]
Does koalas support python 2?
I tried to install it via pip (python2 -m pip install koalas) with no luck.

**Comment by rxin** [comment]
It only supports Python 3. If there are enough demand we would reconsider that.

**Comment by HyukjinKwon** [comment]
I agree. Python 2 is EOL soon.

**Comment by HyukjinKwon** [comment]
See https://python3statement.org/ (Pandas is there) and https://pythonclock.org/ .I would rather follow this mainstream. I am closing this.
