### ISSUE TITLE
mean/kurt/var/std/skew should apply on numeric columns by default

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#280]
See screenshot:

![Screen Shot 2019-05-08 at 11 08 37 PM](https://user-images.githubusercontent.com/323388/57431000-3a893c80-71e6-11e9-8c9b-eec113e1c7ac.png)

**Comment by nitlev** [comment]
Is someone working on this one ?

**Comment by HyukjinKwon** [comment]
Please go ahead.

**Comment by nitlev** [comment]
Submitted PR #422

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/koalas/issues/280
