### ISSUE TITLE
String handling functions (Series.str)

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#281]
The set of Series.str functions are super useful for manipulating text data: http://pandas.pydata.org/pandas-docs/stable/reference/series.html#string-handling

We can probably start with building a simple framework that can wrap around pandas' Series.str functions using pandas UDF. Then for the functions that have native Spark ones, change the implementation to use the Spark native ones instead for higher performance.

**Comment by icexelloss** [comment]
I am taking a look a this

**Comment by HyukjinKwon** [comment]
Nice! @icexelloss!

**Comment by icexelloss** [comment]
I am working with Hyoojee @hjoo. She will work on this instead :). I am going to take a stab at dt functions.

**Comment by hjoo** [comment]
I'm working on this.

**Comment by hjoo** [comment]
Opting not to implement `Series.str.encode()` and `Series.str.decode()` for now because Spark 2.3 doesn't support BinaryType. Issue should be addressed separately from #429.

**Comment by hjoo** [comment]
#429 implements the following `Series.str` functions:

- `capitalize()`, `upper()`, `lower()`, `swapcase()`
- `get()`
- `startswith()`, `endswith()`
- `strip()`, `lstrip()`, `rstrip()`
- `isalnum()`, `isalpha()`, `isdigit()`, `isspace()`, `islower()`, `isupper()`, `istitle()`, `isnumeric()`, `isdecimal()`

Functions that still need to be implemented are the remaining functions listed here: https://pandas.pydata.org/pandas-docs/stable/reference/series.html#api-series-str.

**Comment by hjoo** [comment]
Implementing the remaining functions.

**Comment by HyukjinKwon** [comment]
Fixed in #496
