### ISSUE TITLE
Plot functions (Series.plot)

### ISSUE THREAD

**Issue by dvgodoy** [databricks/koalas#293]
Similar to #281 and #282, but for plotting methods (`bar`, `hist`, `boxplot` and `scatter` - `line` probably doesn't make much sense).
The ability to plot and visualize data is fundamental for the exploratory data analysis step in a ML pipeline.

**Comment by dvgodoy** [comment]
I have worked on this in the past and I will be porting the implementations for these 4 kinds of plots to Koalas.

**Comment by HyukjinKwon** [comment]
All other plots except:

- [`DataFrame.plot.hexbin`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.hexbin.html#pandas.DataFrame.plot.hexbin)
- [`DataFrame.plot.scatter`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.scatter.html#pandas.DataFrame.plot.scatter)
- [`DataFrame.boxplot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.boxplot.html#pandas.DataFrame.boxplot)

are implemented. @dvgodoy would you be interested in continuing the efforts?

**Comment by itholic** [comment]
i think we have `DataFrame.plot.scatter` ??

https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.frame.DataFrame.plot.scatter.html#databricks-koalas-frame-dataframe-plot-scatter

**Comment by HyukjinKwon** [comment]
Ah, sure. Seems that's not in the documentation. I will add it in https://github.com/databricks/koalas/pull/1337

**Comment by HyukjinKwon** [comment]
Ah, sure. I edited the comment.

**Comment by HyukjinKwon** [comment]
Actually all plots in Series are implemented. We should implement two plots in DataFrame. We will track it in #666
