### ISSUE TITLE
nunique

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#303]
Both DataFrame / Series should have nunique method. This should be pretty easy to implement by using the count_distinct expression in Spark.

dropna would require little bit of extra handling (perhaps by adding a filter?).

We might want to introduce a flag that does approximate unique, using HyperLogLog, which would be much faster.

pandas docs:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.nunique.html

**Comment by floscha** [comment]
I'm happy to implement this method as I use it a lot in pandas.

**Comment by HyukjinKwon** [comment]
Please go ahead.
