### ISSUE TITLE
sort_index

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#304]
Should be available on both DataFrame and Series.

For backward compatibility, we might want to keep the "kind" option but state that its value is ignored.

pandas doc:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sort_index.html

**Comment by rxin** [comment]
cc @floscha I added a bunch of tickets to add some functions. Would love more of your contributions :)

**Comment by floscha** [comment]
Sure @rxin, I'll see what I can do :)
