### ISSUE TITLE
Support more than one index for the index property

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#306]
Both DataFrame and Series have this limitation:

```python
    @property
    def index(self):
        """The index (row labels) Column of the DataFrame.

        Currently supported only when the DataFrame has a single index.
        """
        from databricks.koalas.series import Series
        if len(self._metadata.index_map) != 1:
            raise KeyError('Currently supported only when the DataFrame has a single index.')
        return Series(self._index_columns[0], anchor=self, index=[])
```

We should just support more than 1 here ... (and also 0).

**Comment by rxin** [comment]
When we fix this, we should also update the docs for reset_index to leverage `.index` to show Koalas doesn't add a sequential index by default.

**Comment by ueshin** [comment]
I'll take this.

**Comment by ueshin** [comment]
We might need to add `Index` and `MultiIndex` instead of `Series` as pandas' `Index` and `MultiIndex`.
