### ISSUE TITLE
Series.fillna

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#308]
We implemented DataFrame.fillna but not Series.fillna.

pandas doc: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.fillna.html#pandas.Series.fillna

It seems like the doc can just reuse DataFrame's, as long as we change the Returns section and add an example doctest to verify Series.fillna behavior.

**Comment by rxin** [comment]
cc @garawalid want to add this? You added DataFrame.fillna.

**Comment by garawalid** [comment]
@rxin I'll take care of it.
