### ISSUE TITLE
Suggestion for improvement use koalas instead of databricks.koalas

### ISSUE THREAD

**Issue by ezwiefel** [databricks/koalas#312]
The current naming / import of the package feels inconsistent and not what I expect as a Python developer - especially if we're trying to reduce the barrier of entry from Pandas to Spark. It's not a big deal, but changing this could reduce friction.

I'd recommend being consistent (and shadowing Pandas) for both the pip install and import statements:

_Pandas style:_
`pip install pandas`
`import pandas as pd`

_Current Koalas style:_
`pip install koalas`
`import databricks.koalas as ks`

_Recommended Koalas style:_
`pip install koalas`
`import koalas as ks`

**Comment by rxin** [comment]
Thanks. I'm going to leave this ticket open here so others can chime in. We can consider it if there's enough request.

**Comment by athena15** [comment]
My .02...I'd lean towards `import koalas as ks`. Everyone working with pandas is used to `import pandas as pd`, and our goal should be to make the transition as seamless as possible.

**Comment by HyukjinKwon** [comment]
actually I personally like this way too.

**Comment by Cheffress** [comment]
Agree with all of the above.

**Comment by icexelloss** [comment]
I am +1 to the package `koalas`

**Comment by josiemundi** [comment]
+1 on this

**Comment by mjwestcott** [comment]
Also, using `koalas as kl` would be more consistent with `pandas as pd` and `numpy as np`.

**Comment by HyukjinKwon** [comment]
Actually, let's don't change it for now unless there's technical reasons. It's troublesome to change it at the current status because we should move the packages around and users have to change their import style ...

**Comment by itholic** [comment]
I think now we can close this since there have been no requests for this issue in the past two years.

Also now there are many Koalas users, and this change rather can break existing users' code.
