### ISSUE TITLE
clip_lower/clip_upper deprecated

### ISSUE THREAD

**Issue by floscha** [databricks/koalas#318]
Both the *missing/frame.py* and *missing/series.py* files contain entries for the `clip_lower()` and `clip_upper()` methods. According to the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_upper.html), both methods are deprecated now. While it would be trivial to add those to Koalas once #313 is merged, I'm wondering if makes sense to still add them or otherwise add a note that they're deprecated and shouldn't be used.

**Comment by rxin** [comment]
I wouldn't add them. Maybe we can create a section in missing to indicate these methods are deprecated and we wouldn't implement them.

**Comment by rxin** [comment]
@floscha want to submit a patch to resolve this?

**Comment by floscha** [comment]
Sure. What do you think about extending the `PandasNotImplementedError` class with an additional `is_deprecated` argument which defaults to `False`? This would give users (and potentially developers) a hint that this method/property is not only not implemented but also should not be implemented in the future.

**Comment by rxin** [comment]
Sounds great!
