### ISSUE TITLE
Remove DataFrame.__iter__

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#319]
The current implementation is too error-prone in big data:

```
    def __iter__(self):
        return self.toPandas().__iter__()
```

It will just blow up with large amount of data.

**Comment by rxin** [comment]
cc @thunterdb since you added this one ...

**Comment by rxin** [comment]
For now I think we should just remove it. We can add it back when we have a better way to do this. One way to do this is through toLocalIterator, but it's still a bad practice in general.

**Comment by thunterdb** [comment]
Yes, merging that attempt was a mistake. Thanks for removing it.
