### ISSUE TITLE
internal refactoring: create an immutable internal dataframe structure

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#322]
Right now DataFrame wraps around two data structures: _metadata and _sdf (a Spark DataFrame). Series wraps around three data structures: _scol (a Spark Column), _kdf (the Koalas DataFrame), and _index_map.

I think it will be easier to reason about if we create a single internal data structure that's immutable (say InternalFrame). The user facing DataFrame and Series are still mutable, but they simply wrap around one immutable data structure. They can point to a new immutable data structure if any inplace change is required.

Aside from just being a cleaner design, I had one motivating use case for this: I wanted to cache the result of a to_pandas() call (so repeatedly calling a DataFrame's `__repr__` won't trigger more than one computation), but given the current mutable structure it is very difficult to reason about correctness. If we have an internal, immutable frame, we can just put the cache in that frame. The cache will always be correct (and does not need to be invalidated) for that frame since the frame is immutable.

**Comment by rxin** [comment]
BTW if Metadata is already immutable, we could also just move _sdf and _scol into the Metadata class, and then rename the class to InternalFrame ...

**Comment by garawalid** [comment]
I agree with you. Especially, caching the result of to_panads() will save computation because we use it in many methods like to_numpy()

**Comment by thunterdb** [comment]
Having a separate immutable and internal data structure sounds good to me.
We will need an option to disable it though because these arrays can be
very large and should not always be kept in memory.

Series and DataFrame are pretty different both in behaviour and API, so
these should be kept separate in my opinion (shape, indexing, slicing, ...
all have different behaviour).

**Comment by HyukjinKwon** [comment]
I am going to retarget this to 0.6.0

**Comment by rxin** [comment]
@HyukjinKwon or @ueshin will one of you have time to work on this?

**Comment by ueshin** [comment]
@rxin I'll take this.

**Comment by HyukjinKwon** [comment]
Actually this is fixed.

**Comment by rxin** [comment]
Is this completely done?

**Comment by HyukjinKwon** [comment]
I think this is completely done now. We could fix followups if there are some bugs. Let me track it in separate tickets.
