### ISSUE TITLE
DataFrame/Series.describe()

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#334]
pandas version: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html

This is a very useful function for understanding the dataset. Note that Spark already has a describe that does similar things. A simple version of Koalas' describe can just delegate to Spark's. A fancier version should construct the descriptive stats and then match more pandas'.

**Comment by tdliu** [comment]
Is someone looking into this? We have a webinar coming up and it would be great to be able to use this method (cc @HyukjinKwon, @ueshin).

**Comment by rxin** [comment]
Yes please. We should use approximate quantile in Spark automatically.

**Comment by garawalid** [comment]
@tdliu I'll try to finish it ASAP.
