### ISSUE TITLE
Java gateway process exited before sending its port number error

### ISSUE THREAD

**Issue by devender-yadav** [databricks/koalas#345]
Using koala: 0.4.0

Trying to run the sample program given in the README in the jupyter notebook:

    import pandas as pd
    pdf = pd.DataFrame({'x':range(3), 'y':['a','b','b'], 'z':['a','b','b']})

    # Create a Koalas DataFrame from pandas DataFrame
    df = ks.from_pandas(pdf)

    # Rename the columnsa
    df.columns = ['x', 'y', 'z1']

    # Do some operations in place:
    df['x2'] = df.x * df.x

**Error:**

Exception                                 Traceback (most recent call last)
<ipython-input-58-2f0b9ca2ba1b> in <module>
      3 
      4 # Create a Koalas DataFrame from pandas DataFrame
----> 5 df = ks.from_pandas(pdf)
      6 
      7 # Rename the columns

/usr/local/lib/python3.7/site-packages/databricks/koalas/namespace.py in from_pandas(pobj)
     54         return Series(pobj)
     55     elif isinstance(pobj, pd.DataFrame):
---> 56         return DataFrame(pobj)
     57     else:
     58         raise ValueError("Unknown data type: {}".format(type(pobj)))

/usr/local/lib/python3.7/site-packages/databricks/koalas/frame.py in __init__(self, data, index, columns, dtype, copy)
    130             assert dtype is None
    131             assert not copy
--> 132             self._init_from_pandas(data)
    133         elif isinstance(data, spark.DataFrame):
    134             assert columns is None

/usr/local/lib/python3.7/site-packages/databricks/koalas/frame.py in _init_from_pandas(self, pdf)
    152                 continue
    153             reset_index[name] = col.replace({np.nan: None})
--> 154         self._init_from_spark(default_session().createDataFrame(reset_index, schema=schema),
    155                               metadata)
    156 

/usr/local/lib/python3.7/site-packages/databricks/koalas/utils.py in default_session()
     25 
     26 def default_session():
---> 27     return spark.SparkSession.builder.getOrCreate()
     28 
     29 

/usr/local/lib/python3.7/site-packages/pyspark/sql/session.py in getOrCreate(self)
    171                     for key, value in self._options.items():
    172                         sparkConf.set(key, value)
--> 173                     sc = SparkContext.getOrCreate(sparkConf)
    174                     # This SparkContext may be an existing one.
    175                     for key, value in self._options.items():

/usr/local/lib/python3.7/site-packages/pyspark/context.py in getOrCreate(cls, conf)
    365         with SparkContext._lock:
    366             if SparkContext._active_spark_context is None:
--> 367                 SparkContext(conf=conf or SparkConf())
    368             return SparkContext._active_spark_context
    369 

/usr/local/lib/python3.7/site-packages/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    131                     " note this option will be removed in Spark 3.0")
    132 
--> 133         SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    134         try:
    135             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

/usr/local/lib/python3.7/site-packages/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
    314         with SparkContext._lock:
    315             if not SparkContext._gateway:
--> 316                 SparkContext._gateway = gateway or launch_gateway(conf)
    317                 SparkContext._jvm = SparkContext._gateway.jvm
    318 

/usr/local/lib/python3.7/site-packages/pyspark/java_gateway.py in launch_gateway(conf)
     44     :return: a JVM gateway
     45     """
---> 46     return _launch_gateway(conf)
     47 
     48 

/usr/local/lib/python3.7/site-packages/pyspark/java_gateway.py in _launch_gateway(conf, insecure)
    106 
    107             if not os.path.isfile(conn_info_file):
--> 108                 raise Exception("Java gateway process exited before sending its port number")
    109 
    110             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number

**Comment by HyukjinKwon** [comment]
Seems like there was an error between JVM and Py4J. Are you able to run any Spark job? Looks it's not an issue in Koalas

**Comment by HyukjinKwon** [comment]
Let me leave this resolved. I am pretty certain that it's not an issue in Koalas.
