### ISSUE TITLE
Package Documentation

### ISSUE THREAD

**Issue by saibhargav8379** [databricks/koalas#370]
Please provide any updated documentation that contains pandas functions, spark functions, what are the pandas functions that are implemented in koalas, what pandas functions yet to be implemented and also same with spark and what are the functions that are exclusive to koalas.

**Comment by thunterdb** [comment]
@saibhargav8379 this is covered in the public documentation: http://koalas.readthedocs.io

Feel free to make some contributions if you see something missing.
