### ISSUE TITLE
Can't convert object type column to datetime64 with to_datetime

### ISSUE THREAD

**Issue by tdliu** [databricks/koalas#371]
In my data frame, I have a column of object type that I want to convert to datetime. In pandas, I call `pd.to_datetime(data["Received DtTm"])` on a pandas data frame, which returns the column in datetime64 format. After I execute `ks.to_datetime(data["Received` DtTm"])` on a Koalas data frame and call head on the column, I run into an error. 
![Screen Shot 2019-05-21 at 2 30 02 PM](https://user-images.githubusercontent.com/4130267/58131982-faa65a00-7bd4-11e9-9331-83eccba23885.png)

**Comment by thunterdb** [comment]
What is the outcome of trying `pd.to_datetime(...)`? It might be a
limitation of the underlying pandas implementation.

**Comment by tdliu** [comment]
It properly converts it to datetime64. 
![Screen Shot 2019-05-21 at 4 22 02 PM](https://user-images.githubusercontent.com/4130267/58136877-97242880-7be4-11e9-8ad8-d727dcf35d95.png)

**Comment by HyukjinKwon** [comment]
I think object type isn't supported via Pandas <> Arrow optimization. It would be helpful to diagnose further if the current input and output are clarified. Can you show `data_pd` and the full error messages?

**Comment by tdliu** [comment]
Shared notebook with @HyukjinKwon

**Comment by thunterdb** [comment]
It turns out this was an issue with databricks. I am going to close this issue.

**Comment by kumarvc** [comment]
I am also facing similar issue. What was the fix to resolve this issue?

**Comment by HyukjinKwon** [comment]
This looks like an issue that you're using low Spark version (2.4) but high Arrow version. Can you try to set `ARROW_PRE_0_15_IPC_FORMAT` environment variable?

**Comment by rguillome** [comment]
@HyukjinKwon  :-1: 
`Arrow legacy IPC format is not supported in PySpark, please unset ARROW_PRE_0_15_IPC_FORMAT`
