### ISSUE TITLE
.loc behavior for scalar values

### ISSUE THREAD

**Issue by floscha** [databricks/koalas#383]
Assuming a simple DataFrame `kdf = ks.DataFrame({'A': [1,2,3]})`, running `kdf.loc[1]` results in the following exception:
```SparkPandasNotImplementedError: Cannot use a scalar value for row selection with Spark. You are trying to use pandas function .loc[..., ...], use spark function select, where```

However, `kdf.loc[1:1]` behaves the same as in pandas and returns the wanted column but as a DataFrame while `.loc[1]` would return a Series.

The `LocIndexer` docs state the following:
```
Allowed inputs are:
    - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
      interpreted as a *label* of the index, and **never** as an
      integer position along the index) for column selection.
```

Can someone point out the rationale behind this behavior? My only guess would be that the exception tries to keep users from using the label as an integer position, which is not even the point of `.loc` but rather `.iloc`, right?

**Comment by garawalid** [comment]
The notion of order in Spark's DataFrame doesn't exist. If we read a DataFrame from the disk, we perform some transformations and then we save it. We won't find the same order as the first. 
I think this due to the fact that Spark divides the output into chunks.

**Comment by floscha** [comment]
What you say is true for regular Spark DataFrames. However, Koalas stores pandas indices as a dedicated *\_\_index_level_n\_\_* column. Given an example DataFrame `kdf = ks.DataFrame({'A': list('abc')})`, it is for example easily possible to get the second column (containing `b`) using `kdf._sdf.where(F.col('__index_level_0__') == 1)`. This what the `.loc` method is made for. I'm aware that getting the same row with `.iloc[1]` is not feasible with PySpark for the reasons you've explained.

**Comment by ueshin** [comment]
Here is the previous discussion: https://github.com/databricks/koalas/pull/324#discussion_r283658407

If we want to strictly follow pandas' behavior, we need to count the matched row to change the return value if the matched row is only one or not.
I was not sure whether we want to run the extra `count` job for this.
Also I was not sure what the return value should be, Koalas DataFrame/Series or pandas' ones for the case?
The implementation itself should be easy if we want anyway.

**Comment by thunterdb** [comment]
We can certainly add scalar addressing, but I want to hear from more users first, because it is easily an antipattern when using spark:

```py
[process_group(df.loc[x]) for x in ...]
```
