### ISSUE TITLE
How to contribute to project?

### ISSUE THREAD

**Issue by yuwillrun** [databricks/koalas#393]
Hello contributors. I'm a data enginneer who use spark hive and  pandas frequently. When I saw this project, I was very excited. Because it greatly simplifies my work. I want to contribute something to this project. Is there someone guided me how to contribute to the project? And the content of the contribution?

**Comment by floscha** [comment]
Welcome @yuwillrun.

The [Contributing Guide](https://github.com/databricks/koalas/blob/master/CONTRIBUTING.md) should answer most of your questions. If you are looking for features to work on, you can start [here](https://github.com/databricks/koalas/issues/362). If you have found something, you should open an issue for your feature where you can discuss its feasibility with other contributors before actually starting to code.

**Comment by HyukjinKwon** [comment]
Yup, closing this.

**Comment by yuwillrun** [comment]
Ok, thanks your generous reply.
