### ISSUE TITLE
DataFrame.replace

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#394]
This is a very convenient function and I have heard multiple users asking for it. This is essentially a more elaborate API on top of DataFrame.map, which is in the process of being merged in #389 . 

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html

For the time being, I recommend implementing the following options:
 - to_replace=None
 - value=None

The following options are not as useful in my experience and can be added later:
 - inplace=False
 - regex=False

The following options are more difficult to support with spark, so we can leave them aside for now:
- limit=None
- method='pad'

**Comment by HyukjinKwon** [comment]
FYI, I ended up with using CASE WHEN due to behaviour difference in Spark's replace .....

**Comment by akhilanandbv003** [comment]
Can I give it a try?

**Comment by HyukjinKwon** [comment]
Please go ahead!

**Comment by parekhaagam** [comment]
I would like to contribute @akhilanandbv003  do u need any help?

**Comment by akhilanandbv003** [comment]
@parekhaagam I have been busy with some other stuff, haven't made any progress in terms of this issue. You can go ahead and work on it.

**Comment by parekhaagam** [comment]
Thank you @akhilanandbv003.  I will work on it and will update soon

**Comment by shril** [comment]
I have opened a PR for this. @thunterdb please have a look.

**Comment by shril** [comment]
@thunterdb, you can close this issue.
