### ISSUE TITLE
Series.fillna does not anchor

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#405]
Example to reproduce:

```py
df = ks.DataFrame({"x":[1, None]})
df["x"] = df["x"].fillna(2)
df
```
leads to:
`AssertionError: Cannot combine column argument because it comes from a different dataframe`

**Comment by HyukjinKwon** [comment]
This is actually bigger problem than I thought. `fillna` requires to make another DataFrame because the corresponding API is existent in Spark DataFrame (not column).

**Comment by HyukjinKwon** [comment]
Hm .. we should maybe try to write all the series APIs only via expressions but I wonder how far it's possible. For instance, `unique` returns the different number of values.

**Comment by garawalid** [comment]
@HyukjinKwon, I agree. I've been investigating the issue, and I couldn't find a simple solution without changing the series API.

**Comment by HyukjinKwon** [comment]
Let me leave this as won't fix at this moment. There is no way to use the same DataFrame by the limitation of Spark API.
