### ISSUE TITLE
isna() is not working with UDFs

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#406]
I am experiencing the following issue with to_timestamp. Here is a reproduction:

```py
@ks.pandas_wraps
def f(x) -> ks.Col[int]:
  return 2 * x

df = ks.DataFrame({"x":[1, None]})
f(df["x"]).isna()
```

It works with pandas but triggers the following error in spark: `<repr(<databricks.koalas.series.Series at 0x7fd2d0777438>) failed: KeyError: '(CAST(clean_fun(x) AS INT) AS `f(x)` IS NULL)'>`

**Comment by HyukjinKwon** [comment]
The cause seems to be https://issues.apache.org/jira/browse/SPARK-18502. Let me try to find a workaround
