### ISSUE TITLE
DataFrame.GroupBy.apply()

### ISSUE THREAD

**Issue by patryk-oleniuk** [databricks/koalas#409]
I'm continuously missing this behavior when converting my pandas scripts to koalas:

```python
df = pd.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5],
              "car_id": ['A','A','A','B','B'], 
              "battery_charge": [100, 90, 80,100,90]
              })

print(df)

def calc_battery_usage(x):
    start_bat = x.sort_values('timestamp').iloc[0]['battery_charge']
    stop_bat = x.sort_values('timestamp').iloc[-1]['battery_charge']
    return start_bat - stop_bat

print(df.groupby('car_id').apply(calc_battery_usage))
```
That prints out:
```python
   timestamp car_id  battery_charge
0        0.0      A             100
1        0.5      A              90
2        1.0      A              80
3        0.0      B             100
4        0.5      B              90

car_id
A    20
B    10
```

On koalas I just get:
```
PandasNotImplementedError: The method `pd.groupby.GroupBy.apply()` is not implemented yet.
```

I can take over and start implementing it myself, but would probably need some general guidelines on how to do it (probably using pysparks pandas_udf).

**Comment by rxin** [comment]
Is this similar to https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html#grouped-map and https://spark.apache.org/docs/latest/sql-pyspark-pandas-with-arrow.html#grouped-aggregate ? Perhaps we can just map to that.

**Comment by patryk-oleniuk** [comment]
Yes, this is similar. In my current scripts these are the methods I'm using to "manually" make the apply on groupby's.

**Comment by icexelloss** [comment]
Hi @patryk-oleniuk! I think it'd great to have groupby apply in koalas. 

Spark's groupby apply and Pandas's groupby apply are pretty similar. However, two main difference that I can think of are:

- Spark's groupby apply need full return type specification on the udf definition
- Spark's groupby apply doesn't keep index, while Spark's groupby apply use the grouping key as index.

As a start, I'd probably try this something like:
```
@pandas_wrap(full_return_schema):
def calc_battery_usage(x):
    start_bat = x.sort_values('timestamp').iloc[0]['battery_charge']
    stop_bat = x.sort_values('timestamp').iloc[-1]['battery_charge']
    return start_bat - stop_bat

kdf.groupby('car_id').apply(calc_battery_usage)
```
And just wrap it with Spark's groupby apply + pandas_udf

Does that make sense?

**Comment by HyukjinKwon** [comment]
@icexelloss that's nice details. Let me give a shot!

**Comment by patryk-oleniuk** [comment]
Hey @HyukjinKwon , thanks for working on my issue and resolving it. 
I discovered this code bring the wrong results. The apply function behaves very weird:
1. It only accepts modifications from the same kdf, does not support just returning 0.0
2. It does not return the grouping column as index, as pandas groupby.
3. It does not keep the column names.

```python 
kdf = ks.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5],
              "car_id": ['A','A','A','B','B']
              })

def do_something(x) -> ks.DataFrame[float]:
    return ks.DataFrame({"column": 0.0})  ## also doesn't work with return 0.0

print(kdf.groupby('car_id').apply(do_something))
```
gives out the wrong, empty result:
```python
Empty DataFrame
Columns: [c0]
Index: []
```

**Comment by patryk-oleniuk** [comment]
The nasty workaround to above, returning what I'd expect :

```python
kdf = ks.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5],
              "car_id": ['A','A','A','B','B']
              })

def do_something_workaround(x) -> ks.DataFrame[str, float]:
  x['newcolumn'] = 0.0
  return x[['car_id','newcolumn']].iloc[0:1] ## workaround: return single row of grouped kdf with the grouped field inside 

result = kdf.groupby('car_id').apply(do_something_workaround)
## solution to 3. : rename the columns
result['car_id'] = result['c0']
result['something'] = result['c1']
result = result.drop(columns=['c0','c1'])
# set the grouped field as index and sort it
result = result.sort_values('car_id')
result = result.set_index('car_id')
print(result)
```

**Comment by HyukjinKwon** [comment]
Thanks, @patryk-oleniuk. Let me open new issue based upon the comments.

**Comment by HyukjinKwon** [comment]
Oh, wait. Actually the function should return a pandas DataFrame:

```python
kdf = ks.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5],
              "car_id": ['A','A','A','B','B']
              })

def do_something(x) -> ks.DataFrame[float]:
    return pd.DataFrame({"column": 0.0})  ## also doesn't work: return 0.0

print(kdf.groupby('car_id').apply(do_something))
```

as documented:

https://github.com/databricks/koalas/blob/429e26be5bbbf90f7887cfc5531ec1210a7f5f11/databricks/koalas/groupby.py#L645-L649



BTW, which pandas version do you use? Seems `pd.DataFrame({"column": 0.0}) ` is disallowed in pandas 0.24.2.

```python
>>> import pandas as pd
>>> pd.__version__
'0.24.2'
>>> pd.DataFrame({"column": 0.0})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 308, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index
```

Seems working fine in my side if I do:

```python
kdf = ks.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5],
              "car_id": ['A','A','A','B','B']
              })

def do_something(x) -> ks.DataFrame[float]:
    return pd.DataFrame({"column": [0.0]})

print(kdf.groupby('car_id').apply(do_something))
```

```
    c0
0  0.0
1  0.0
```

**Comment by HyukjinKwon** [comment]
```
def do_something(x) -> ks.DataFrame[float]:
    return pd.DataFrame({"column": 0.0})  ## also doesn't work: return 0.0
```

I just realised that this might look awkward because the type says it's Koalas but it should return pandas' .. maybe we have to come up with a better way.

**Comment by patryk-oleniuk** [comment]
About 1. (weird return behaviors): 
I was using pd version 0.23.0 to reproduce all the previously mentioned behaviors. 
(this is because pandas 0.23.0 was pre-installed on Databricks `5.5 M` runtime. )
Indeed, when using 0.24.2 I get the correct results. So I guess it's just about installing the proper version of pandas :).
I also agree, that we should think about better ways of specyfying return types - its indeed misleading .. One way would be to also allow : 
```
def do_something(x) -> ks.DataFrame[float]:
    return [0.0, ...] (each element here would be its own column)
```
Since the column names are currently anyway not propagated. 

About 2. (maintain the index key)
Couldn't we just apply the "maintain_index" flag and include the workaround from above if flag is raised ? 

About 3. (keep column names) 
Well, this is just a cosmetic change. but very inconvenient, since there is no `DataFrame.rename(columns = {"c0":"my_column_name"})' method.

I am aware these brings some performance issues, but this would simplify moving from pd to ks (otherwise you have to rewrite the whole function). Let me know what do you think.

**Comment by HyukjinKwon** [comment]
About 2. maintaining the index, yes, seems possible. Let me take a look at https://github.com/databricks/koalas/issues/628

About 3., this isn't easy. Because Spark should know the column names before it executes.
I think we should execute the given `func` locally against a small sample of Koalas DataFrame, infer the schema, and executes it. I did this in, for instance, https://github.com/databricks/koalas/pull/605. Yes, since this is just a cosmetic change in practice, I will maybe take a look a bit later. Please feel free to open an issue.

**Comment by Devarsh-UTD** [comment]
Thank you guys for the replies. I will surely check out all of the suggestions by tomorrow evening...!!

**Comment by Devarsh-UTD** [comment]
Thank you guys for the replies. I will surely check out all of the suggestions by tomorrow evening...!!
