### ISSUE TITLE
Projections loose references to the original dataframe

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#410]
Here is a problem that is is currently documented in the doc for [koalas.mlflow.predict](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.mlflow.load_model.html#databricks.koalas.mlflow.load_model): it is common to isolate a few columns of a dataframe, transform them into a column, and then add this column back into the first dataframe.

Examples:
 - featurization in this [blog post](https://tomaugspurger.github.io/method-chaining.html)
 - [applying an ML model to predict variables](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.mlflow.load_model.html#databricks.koalas.mlflow.load_model)
 - computing the mean of a few columns:

```py
df = pd.DataFrame({"x": [1], "y": [2]})
df["z"] = df[["x", "y"]].mean(axis=1)
```

- fixing NaNs for specific columns:

```py
df = pd.DataFrame({"x": [1], "y": [2]})
df[["x", "y"]] = df[["x", "y"]].fillna(-1)
```

All these issues come from the fact that `df[[...]]` returns a new ks.DataFrame that has lost reference to the original `df`. The only solution currently is making a join, which does not work in all cases when there are duplicates (see  [koalas.mlflow.predict](https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.mlflow.load_model.html#databricks.koalas.mlflow.load_model) )

I am creating this issue here mostly to trigger discussions, because this will most probably require some changes in the way we represent dataframes.

**Comment by thunterdb** [comment]
Note that the issue is not the the fact that we are adding a new column, but rather that we are unable to compare series from the original dataframe with the new dataframe. For example, this code to compute L1 error would currently fail:

```py
df = pd.DataFrame({"output": [1], "feature1": [2], "feature2": [3]})
prediction = df[["feature1", "feature2"]].mean(axis=1)
mse = (df["output"] - prediction).abs().sum()
```

**Comment by HyukjinKwon** [comment]
This was fixed by providing a workaround, option `compute.ops_on_diff_frames`. Now we support the operations on different DataFrames. We should still avoid to losing the original frame in this project in general though.
