### ISSUE TITLE
Series index order question

### ISSUE THREAD

**Issue by yuwillrun** [databricks/koalas#411]
Recently i'm creating some simple function related to  serise index.
When writing demo to see how index work, i found the series order is confusion like below. Is there something wrong?

```python
import databricks.koalas as ks
series = ks.Series([1, 2, 3])
series
2    3
1    2
0    1
Name: 0, dtype: int64

series.index
Int64Index([2, 0, 1], dtype='int64')

```

**Comment by ueshin** [comment]
Hi @yuwillrun, thanks for reporting this!
Could you let us know your environment? E.g., what version of Python, pandas, Koalas?

I tried with master head in my local, but the result seems deterministic:

```py
>>> import databricks.koalas as ks
>>> series = ks.Series([1, 2, 3])
>>> series
0    1
1    2
2    3
Name: 0, dtype: int64
>>> series.index
Int64Index([0, 1, 2], dtype='int64')
```

**Comment by yuwillrun** [comment]
Here is my details.
I'm in local jupyter model write python script. The script will run pyspark task via company cluster by docker(abount 500 instances). Is this the reason causing this due to some unknown distributed reasons.

python '3.6.4'
pyspark '2.3.0'
koalas '0.5.0'
pandas '0.22.0'

**Comment by ueshin** [comment]
hm, Spark's `sdf.limit(n)` in Koalas' `kdf.head(n)` we use to limit the number of rows to be shown seems sometimes non-deterministic in a distributed environment.

```
>>> from pyspark.sql.session import SparkSession
>>> spark = SparkSession.builder.master('local-cluster[4, 2, 1024]').getOrCreate()

>>> sdf = spark.createDataFrame([[1],[2],[3]], ['a'])
>>> sdf.show()
+---+
|  a|
+---+
|  1|
|  2|
|  3|
+---+

>>> sdf.limit(10).show()
+---+
|  a|
+---+
|  3|
|  2|
|  1|
+---+

>>> sdf.limit(10).show()
+---+
|  a|
+---+
|  1|
|  3|
|  2|
+---+
```
