### ISSUE TITLE
Panda's `from_records` missing in Koalas

### ISSUE THREAD

**Issue by benjaminbang987** [databricks/koalas#415]
The equivalent of `from_records` in Pandas is missing in Koalas (unlike the description in https://github.com/databricks/koalas/blob/0ef453b4ed1add1d3468eb3742333d06228d6e24/databricks/koalas/frame.py#L1429, which hints that it should be available along with `to_records`).

It would be a useful addition to Koalas package (or at the least, the commentary should be updated to say that `from_records` is in the works rather than "See Also").

I was using the latest Koalas version (0.6.0).

**Comment by HyukjinKwon** [comment]
This will be virtually `ks.DataFrame(pd.from_records)`. should be easy to add.

BTW, `to_records` is close to violate https://github.com/databricks/koalas#guardrails-to-prevent-users-from-shooting-themselves-in-the-foot . We might have to deprecate it in the future.

**Comment by floscha** [comment]
I can quickly add a PR for the `from_records()` implementation.

Regarding ` to_records()`: How about adding an "implementation" that raises a `NotImplementedError` which briefly informs the user about the risk of calling the method on a large dataset and hints that the desired result can be obtained by calling `.to_pandas().to_records()`(at their own risk)?

**Comment by HyukjinKwon** [comment]
Let's add from_records since we already have to_records for now. to_records has that warning in the doc .. so it might be fine for now ...

**Comment by floscha** [comment]
With #436 merged, this issue can be closed, right @HyukjinKwon?

**Comment by benjaminbang987** [comment]
Thank you @HyukjinKwon and @floscha for taking care of this
