### ISSUE TITLE
add reindex function problem

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#421]
Hello.
Now i want to add `reindex` function like pandas via PR.
[pandas reindex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reindex.html) 
My first solution is create a `spark.dataframe` for index named index_sdf.Then join index_sdf with koalas._sdf. Data result is correct. But key order is not expected after `spark.join`.

koalas._sdf
+-----------------+-----------+-------------+
|__index_level_0__|http_status|response_time|
+-----------------+-----------+-------------+
|          Firefox|        200|         0.04|
|           Chrome|        200|         0.02|
|           Safari|        404|         0.07|
|             IE10|        404|         0.08|
|        Konqueror|        301|          1.0|
+-----------------+-----------+-------------+

index_sdf
+-----------------+
|__index_level_0__|
+-----------------+
|           Safari|
|        Iceweasel|
|    Comodo Dragon|
|             IE10|
|           Chrome|
+-----------------+

E  expect answer:
E                  http_status  response_time
E   Safari               404.0           0.07
E   Iceweasel              NaN            NaN
E   Comodo Dragon          NaN            NaN
E   IE10                 404.0           0.08
E   Chrome               200.0           0.02
E   http_status      float64
E   response_time    float64
E   dtype: object
E
E   my answer:
E              http_status  response_time
E   IE10               404           0.08
E   Firefox            200           0.04
E   Konqueror          301           1.00
E   Safari             404           0.07
E   Chrome             200           0.02
E   http_status        int64
E   response_time    float64
E   dtype: object

## HERE IS MY CODE
```python
    def reindex(self, index=None, fill_value=np.nan):
        """
        Conform DataFrame to new index with optional filling logic, placing NA/NaN in locations
        having no value in the previous index. A new object is produced unless the new index is
        equivalent to the current one and `copy=False`.

        Parameters
        ----------
        labels : array-like, optional
            New labels / index to conform the axis specified by axis’to.

        index, columns : array-like, optional
            New labels / index to conform to, should be specified using keywords.
            Preferably an Index object to avoid duplicating data.

        fill_value : scalar, default np.NaN
            Value to use for missing values. Defaults to NaN, but can be any “compatible” value.

        Returns
        -------
        DataFrame
           DataFrame with changed index.

        >>> index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
        >>> df = ks.DataFrame({
        ...      'http_status': [200,200,404,404,301],
        ...      'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
        ...       columns=['http_status', 'response_time'],
        ...       index=index)
        >>> df
                   http_status  response_time
        Firefox            200           0.04
        Chrome             200           0.02
        Safari             404           0.07
        IE10               404           0.08
        Konqueror          301           1.00

        Create a new index and reindex the dataframe. By default values in the new index that do not
        have corresponding records in the dataframe are assigned `NaN`.

        >>> new_index= ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10', 'Chrome']
        >>> df.reindex(new_index)
                       http_status  response_time
        Safari               404.0           0.07
        Iceweasel              NaN            NaN
        Comodo Dragon          NaN            NaN
        IE10                 404.0           0.08
        Chrome               200.0           0.02

        We can fill in the missing values by passing a value to the keyword fill_value. Because the
        index is not monotonically increasing or decreasing, we cannot use arguments to the keyword
        `method` to fill the `NaN` values.

        >>> df.reindex(new_index, fill_value=0)
                       http_status  response_time
        Safari                 404           0.07
        Iceweasel                0           0.00
        Comodo Dragon            0           0.00
        IE10                   404           0.08
        Chrome                 200           0.02

        >>> df.reindex(new_index, fill_value='missing')
                      http_status response_time
        Safari                404          0.07
        Iceweasel         missing       missing
        Comodo Dragon     missing       missing
        IE10                  404          0.08
        Chrome                200          0.02
        """

        index_column = self._metadata.index_columns[0]
        index_pdf = pd.DataFrame(data=index, columns=self._metadata.index_columns)
        index_sdf = default_session().createDataFrame(index_pdf)
        sdf = self._sdf.join(index_sdf, how='left', on=[index_column])\
            .na.fill({index_column : fill_value})
        return DataFrame(sdf, self._metadata)
```

**Comment by yuwillrun** [comment]
@ueshin Can you give some advices?

**Comment by ueshin** [comment]
Hi @yuwillrun, thanks for tackling this issue!
We can't expect the row order after `spark.join` (to be exact, after shuffle). We have to reorder somehow, if needed.

**Comment by yuwillrun** [comment]
But order data will result shuffle. It expend too much time when sorting data.

**Comment by thunterdb** [comment]
because of how spark works, the ordering is going to be unstable anyway. the final shuffle should be optional if users really want the results ordered.

**Comment by yuwillrun** [comment]
> because of how spark works, the ordering is going to be unstable anyway. the final shuffle should be optional if users really want the results ordered.

Thanks. Can add a parameter decide whether to sort as before ？

**Comment by tdliu** [comment]
What is the status of supporting reindex? @HyukjinKwon @ueshin

**Comment by HyukjinKwon** [comment]
Seems like the order is not guaranteed in Spark but this API has a precondition that the DataFrame is ordered. So, it needs to sort the DataFrame and then somehow concatenate another column (I currently can't think of no way but `join` but It's possible that I am missing something).

Let me take another look.
