### ISSUE TITLE
Initial port of 10 minutes to Pandas

### ISSUE THREAD

**Issue by thunterdb** [databricks/koalas#43]
We should have a short tutorial that quickly explains:
 - to spark users, how they can leverage pandas features thanks to koala
 - to pandas users, what changes they should be of when they want to use spark+koala

The aim is to produce a simple tutorial based on the sections of the [10 minutes to pandas tutorial](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) that are already implemented, and mark the remainder as not implemented yet.

In particular, the tutorial should answer the following questions:
 - [x] will the index be tracked
 - [x] are the objects (context, dataframe, column) separate or are they the regular spark objects
 - [x] how does filtering nulls and NaNs is affected (dropna, value_counts)

Work has been started in this pull request, and more contributions are welcome:
https://github.com/databricks/spark-pandas/pull/34

**Comment by thunterdb** [comment]
This should also mention the functions that will alias column names.

**Comment by shril** [comment]
@thunterdb Can I take this up?

**Comment by HyukjinKwon** [comment]
Hey @thunterdb, let me leave this closed as of #843 for now!
