### ISSUE TITLE
index changed after merge

### ISSUE THREAD

**Issue by yuwillrun** [databricks/koalas#438]
```python
left_kdf = ks.DataFrame({'A': [1, 2]}, index = ['zero', 'one'])
left_kdf
         A
zero   1
one    2

right_kdf = ks.DataFrame({'B': ['x', 'y']}, index=['one', 'two'])
right_kdf
         B
one    x
two    y

left_kdf.merge(right_kdf, left_index=True, right_index=True)
       A     B
0     2     x
```

Index is changed. Expected answer is 
```python
left_kdf.merge(right_kdf, left_index=True, right_index=True)
       A     B
one     2     x

```

**Comment by yuwillrun** [comment]
@ueshin @thunterdb. Do we need fix it?

**Comment by rxin** [comment]
cc @floscha thoughts?

**Comment by floscha** [comment]
Looks like something worth fixing to me. I can create a PR for this later today.

**Comment by yuwillrun** [comment]
> Looks like something worth fixing to me. I can create a PR for this later today.
sorry, i see  a `# TODO: in some case, we can keep indexes.` just now. If you fix this, i can add some function like `join`,`reindex` based on `merge` easily.

**Comment by yuwillrun** [comment]
> Looks like something worth fixing to me. I can create a PR for this later today.

Hello floscha. How long will you take it to finish ?

**Comment by floscha** [comment]
I'm almost done with fixing it. Hopefully I can find some time in the next couple of hours to finish it up.

**Comment by yuwillrun** [comment]
> I'm almost done with fixing it. Hopefully I can find some time in the next couple of hours to finish it up.

Hello, floscha. When you are done, please tell me. Thanks~

**Comment by floscha** [comment]
I've now created a PR with the fix, @yuwillrun. Unfortunately, it took me a bit longer to cover some special corner cases.

**Comment by yuwillrun** [comment]
It seems there is still some problem with your PR.

**Comment by floscha** [comment]
There was another corner case I was missing but it should be working now.
