### ISSUE TITLE
Remove "self" from API docs

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#439]
Take a look at this page: https://koalas.readthedocs.io/en/latest/reference/series.html

Almost all methods have "self" as the first parameter. We should remove them. Perhaps take a look at how pandas does it.

**Comment by rxin** [comment]
@HyukjinKwon can you take a look at this?

**Comment by HyukjinKwon** [comment]
sure

**Comment by HyukjinKwon** [comment]
Hm .. this is a big odd because in my local it generates fine without `self`:
![Screen Shot 2019-06-10 at 5 53 26 PM](https://user-images.githubusercontent.com/6477701/59184264-b5a88e80-8ba8-11e9-8288-253187cc91b1.png)

**Comment by HyukjinKwon** [comment]
I think I have no other way but testing with readthedocs env. it might take some time.
