### ISSUE TITLE
Make patch_spark() revertable - also add Context manager for it

### ISSUE THREAD

**Issue by AbdealiJK** [databricks/koalas#45]
I notice that `patch_spark()` documentation says it cannot be reverted.
That can be a bit scary especially cause I have a bunch of codes where I'd love to use koala for parts which I am writing. But i do need to also call third party python+spark libraries I cannot control and they may break

Ideally - I'd love to be able to do something like:
```python
# Some sparky stuff - Create DF1, DF2
with init_koala():
    # Koala stuff with DF1
# More sparky stuff with DF2
```

Implementation Ideas:
I think a very simple implementation of this could be a `dict()` or all the items it is patching with the old versions of those and revert it using that dict. and reverting back. Just need a bit of book-keeping.

**Comment by thunterdb** [comment]
Because of the way the library works (injection of methods by reflection), it is very tricky to remove the changes.

At a higher level, why would you want to remove the changes? This library is specifically designed so as not to break existing Spark code (including subclassing, etc.) and to only expand the current API of Spark. If you encounter some issues where it breaks your spark code base, we would love to hear about these cases.

**Comment by AbdealiJK** [comment]
I don't think complete backward compatibility is guaranteed.
One quick example that comes to mind is the `head()` function:
<img width="674" alt="Screen Shot 2019-03-29 at 6 14 04 PM" src="https://user-images.githubusercontent.com/2200743/55233403-7d064380-524e-11e9-8646-3deab36ca284.png">

In spark its a list of pyspark.sql.Row after importing koala it is a dataframe

**Comment by AbdealiJK** [comment]
Hm, I just realized that the head is just showing the data in jupyter like that. (using repr-html i guess)
`a = sdf.head(1)` seems to be working fine.
Interesting.

I guess that solves this issue along with the issue at https://github.com/databricks/spark-pandas/issues/47
Which is that is should be spark first and make sure nothing in spark breaks.
And attempt to solve things with pandas as much as possible.

**Comment by AbdealiJK** [comment]
`sdf.columns` used to return a list - but now returns a pd.Index
Would that not count for backward incompatibility with spark ?

**Comment by AbdealiJK** [comment]
Also had some more questions related to this ... I was looking at the patching 
`Directly patching the base does not work because DataFrame inherits from object (known python limitation)`

**Comment by rxin** [comment]
I agree we should revisit the inheritance decision if we can. It'd make it more clear whether this is a SparkPandasDataFrame, or just a Spark DataFrame.

**Comment by rxin** [comment]
@AbdealiJK 

 https://github.com/databricks/spark-pandas/issues/90 should address this issue right?

**Comment by thunterdb** [comment]
I am going to close this ticket since #90 has been merged.
