### ISSUE TITLE
Codecov report issue

### ISSUE THREAD

**Issue by yuwillrun** [databricks/koalas#460]
https://github.com/databricks/koalas/pull/459
Why there is some problem with code cov about __init__.py?

**Comment by HyukjinKwon** [comment]
can you clarify the problem?

**Comment by yuwillrun** [comment]
![image](https://user-images.githubusercontent.com/23121539/59323750-91ff5880-8d0e-11e9-9d96-9422605599b1.png)
Hello HyukjinKwon. As shown in https://github.com/databricks/koalas/pull/459,I changed nothing in __init__.py and conftest.py actually during coding. Why do i see Coverage change in the script as the fig shown?

**Comment by HyukjinKwon** [comment]
I am not sure. Doesn't it look like an issue in codecov?
