### ISSUE TITLE
Koalas DataFrame constuctor should take Koalas Series

### ISSUE THREAD

**Issue by yuwillrun** [databricks/koalas#466]
![image](https://user-images.githubusercontent.com/23121539/59345021-d6581c00-8d41-11e9-9b24-1c1c378c9ca0.png)

can i add  a function which can `ks.series` convert to `ks.dataframe` directly like pandas ?

**Comment by HyukjinKwon** [comment]
I think `ks.DataFrame(pd.Series(...))` will do the same thing.

**Comment by yuwillrun** [comment]
If i want convert a ks.series to ks.dataframe, i need convert a ks.series to pd.series first?

**Comment by HyukjinKwon** [comment]
`ks.Series` has a method called `to_dataframe`. It might be good to integrate it with `ks.DataFrame`'s constructor then.

**Comment by yuwillrun** [comment]
Thanks ，i will create a pr by  using todataframe
