### ISSUE TITLE
Missing T property

### ISSUE THREAD

**Issue by floscha** [databricks/koalas#467]
As mentioned in #382, Koalas is currently missing the `DataFrame.T` property. Since I personally use that property a lot when working with pandas, I'd be happy if it was available in Koalas as well. However, because of its distributed nature, simply turning rows into columns does not easily work with Spark. After thinking about how to implement `T` with Spark for a while now, I couldn't find any solution that is feasible for large datasets. Does anyone have an idea how to actually implement this or should we just raise a `NotImplementedError` that explains why `T` isn't supported by Koalas?

**Comment by HyukjinKwon** [comment]
Actually, I have a rough idea to implement this. Let me give a try to show it

**Comment by thunterdb** [comment]
@HyukjinKwon I was about to suggest that for now we just implement it as .to_pandas().transpose(), but I see that you went the high route with your implementation. This is great, I have seen requests from databricks customers for such a functionality.

**Comment by rxin** [comment]
@floscha do you see yourself using T on big data?

**Comment by floscha** [comment]
Generally yes. Considering the computational effort though, I would probably try to at least reduce the size of the dataset before calling `T`. Also, when for example writing the results to HDFS from Spark, I find it much more convenient to be able to do this from Koalas rather than converting the DataFrame to pandas just to call `T` and then convert back.

**Comment by rxin** [comment]
Makes sense.  Looks like it's worth adding this.

The main design question is whether we should have a max row cap on this ... what do you guys think?

**Comment by HyukjinKwon** [comment]
To me +1 to add.

**Comment by garawalid** [comment]
I agree also about a max row cap.
