### ISSUE TITLE
function pandas version issue

### ISSUE THREAD

**Issue by yuwillrun** [databricks/koalas#472]
Hello. I'm adding `update` function to koalas, and i find the function has some changes between pandas `0.23` and `0.24`. I think `update` in `0.24` version is better. How do we deal with this situation ?

**Comment by yuwillrun** [comment]
@ueshin @HyukjinKwon

**Comment by ueshin** [comment]
Could you elaborate what kind of difference it is?
I think basically we should follow the newer version's behavior.

**Comment by HyukjinKwon** [comment]
Yea, what's an issue?

**Comment by yuwillrun** [comment]
`update` in `0.23`
http://pandas.pydata.org/pandas-docs/version/0.23.0/generated/pandas.DataFrame.update.html has `raise_conflict ` parameter, `update` in `0.24` has `errors` parameter instead. Them has similar function. I prefer to use `0.24 update`.
So i add function like `0.24`. When i run pytest,  i find the koalas default pandas version `0.23`. So i cant pass pytest.

**Comment by HyukjinKwon** [comment]
Can you open a PR to show the codes? I wonder why this is related with Pandas version.

**Comment by yuwillrun** [comment]
Maybe I didn’t express it clearly.It means i need run unit test under pandas `0.24` version.

**Comment by HyukjinKwon** [comment]
I am still lost ..

> It means i need run unit test under pandas 0.24 version.

If you need to run unit tests under pandas 0.24, you can install pandas 0.23 in your local. In pull requests, pandas versions of 0.23 and 0.24 are all tested.
