### ISSUE TITLE
how to use complicated type in series' apply

### ISSUE THREAD

**Issue by Genie-Liu** [databricks/koalas#489]
Hi guys, 

I'm trying to use series.apply to parse json string, but got trouble defining function return type. In spark, we can use StructType to define json schema.

After look into the code, I find that it will use as_spark_type to convert to equivalent spark type. Although it says it can accept list of pair (filename, type) or dictionary, it simply get the type from predefined spark type which are all basic type. How can I define a complicated schema?

![image](https://user-images.githubusercontent.com/34557281/59839817-d381aa80-9383-11e9-9b96-1b286ee22f8e.png)

![image](https://user-images.githubusercontent.com/34557281/59839835-dbd9e580-9383-11e9-8c1d-a5fda0e4b481.png)

**Comment by Genie-Liu** [comment]
while my json values are all string type, I find this way to extract all the key as a column. But it will parse json every time it create a new column, not a fancy way.

```python
def from_json(text: str, key: str) -> str:
    return json.loads(text).get(key, None) 

key_list = ['a', 'b']
for k in key_list:
    df[k] = df.value.apply(from_json, args=(k, ))
```

**Comment by HyukjinKwon** [comment]
Firstly, about defining this, it's being discussed at https://github.com/databricks/koalas/pull/453 cc @rxin, @thunterdb, @floscha, @ueshin 

Secondly, I think Koalas doesn't support nested type yet officially. This is failed at https://github.com/databricks/koalas/issues/420

Let me leave this resolved as a duplicate.
