### ISSUE TITLE
Support for pivot

### ISSUE THREAD

**Issue by tdliu** [databricks/koalas#492]
Customer requested that we implement pivot. They are migrating to Spark. Their legacy platform involves a lot of pandas code. They said pivot is an important method in their ETL scripts but they haven't provided a use case yet. Will push them a bit more but let me know if you need anymore context.

**Comment by HyukjinKwon** [comment]
(FYI, pivot_table is in progress at https://github.com/databricks/koalas/pull/386)

**Comment by rxin** [comment]
@HyukjinKwon should we close this ticket now #386 is merged?

**Comment by HyukjinKwon** [comment]
There's actually [`DataFrame.pivot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html?highlight=pivot#pandas.DataFrame.pivot) too. Let me take a look today.
