### ISSUE TITLE
How to apply countDistinct to DataFrameGroupBy

### ISSUE THREAD

**Issue by harupy** [databricks/koalas#506]
Is there any way to apply `countDistinct` to `DataFrameGroupBy` like the pyspark code below? I've been trying to find a workaround but no luck.

```
# pyspark example 1
sdf.groupBy('x').agg(F.countDistinct('y'))

# pyspark example 2
sdf.groupBy('x').agg(F.expr('count(distinct(y))'))
```

**Comment by HyukjinKwon** [comment]
Out of curiosity, is there such way in Pandas?

**Comment by harupy** [comment]
In Pandas, you can do:
```
df.groupby('x').agg({'y': 'nunique'})
```
or
```
df.groupby('x').agg({'y': lambda x: x.nunique()})
```
https://stackoverflow.com/questions/18554920/pandas-aggregate-count-distinct

**Comment by HyukjinKwon** [comment]
See https://github.com/databricks/koalas/pull/512

**Comment by harupy** [comment]
Cool. Thanks!
