### ISSUE TITLE
Add support for multiple aggregations on a single column

### ISSUE THREAD

**Issue by harupy** [databricks/koalas#514]
It'd be useful if we could perform multiple aggregations on a single column like pandas.

```python
df.groupby('a').agg({'b': ['min', 'max', 'mean']})
```

**Comment by harupy** [comment]
A simple example in pandas to perform multiple aggregations on a single column and flatten multi-level columns
```
>>> import pandas as pd

>>> df = pd.DataFrame({
...   'a': [0, 0, 0, 1, 1, 1],
...   'b': [1, 2, 3, 4, 5, 6]
... })

>>> df_multi_agg = df.groupby('a').agg({'b': ['min', 'max', 'mean']})
>>> df_multi_agg
    b
  min max mean
a
0   1   3    2
1   4   6    5

>>> df_multi_agg.columns
MultiIndex(levels=[['b'], ['min', 'max', 'mean']],
           labels=[[0, 0, 0], [0, 1, 2]])


>>> cols_flattened = df_multi_agg.columns.ravel()
>>> cols_flattened 
array([('b', 'min'), ('b', 'max'), ('b', 'mean')], dtype=object)


>>> df_multi_agg.columns = ['_'.join(c) for c in cols_flattened]
>>> df_multi_agg
   b_min  b_max  b_mean
a
0      1      3       2
1      4      6       5

```

**Comment by rxin** [comment]
@harupy would you be able to submit a pull request to address this?

**Comment by harupy** [comment]
What I came up with to address this was

```python
from databricks import koalas as ks

df = ks.DataFrame({
  'x': [1, 2, 2, 3, 3, 3],
  'y': [0, 0, 0, 0, 0, 0],
  'z': [1, 2, 3, 4, 5, 6]
})


agg_dict = {
  'y': 'count',
  'z': ['max', 'min'],
}

# convert to a list of expressions
agg_exprs = []
for col, funcs in agg_dict.items():
  if not isinstance(funcs, (list, tuple)):
    funcs = [funcs]

  for fn in funcs:
    agg_exprs.append(F.expr('{1}({0}) as {0}_{1}'.format(col, fn)))


df._sdf.groupBy('x').agg(*agg_exprs).orderBy('x').show()
```

This gives
```
+---+-------+-----+-----+
|  x|y_count|z_max|z_min|
+---+-------+-----+-----+
|  1|      1|    1|    1|
|  2|      2|    3|    2|
|  3|      3|    6|    4|
+---+-------+-----+-----+
```

But the result is not exactly the same as pandas because pandas supports multi-level columns.

**Comment by HyukjinKwon** [comment]
For multi-level columns, I thought we can simply add the index column into `groupBy`. For instance, as what we do here:

https://github.com/databricks/koalas/blob/0033b886598621d9f9123458d189caa6f7acdcca/databricks/koalas/groupby.py#L105-L114

**Comment by harupy** [comment]
@HyukjinKwon 
How would the output dataframe look like?

**Comment by HyukjinKwon** [comment]
Ah, gotya, you mean https://github.com/databricks/koalas/issues/301? Yes, I think we don't currently support this.

**Comment by harupy** [comment]
Yes. If the multi-index column structure was supported, we could store multiple aggregation results as a nested column.

**Comment by ueshin** [comment]
Hi @harupy,
We recently added a basic multi-index support in columns (#590).
Does that help you submit a PR?
