### ISSUE TITLE
Add an option to coalesce partitions in DataFrame.to_csv()

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#524]
`ks.DataFrame.to_csv` is too slow because it will transform to `pandas.DataFrame` first.Is there a way save to `csv` format directly?

**Comment by HyukjinKwon** [comment]
Let's switch it to spark.write.csv

**Comment by rxin** [comment]
Yea I agree - we should use Spark's native one to parallelize it.

**Comment by RainFung** [comment]
@HyukjinKwon Hello. Can i improve pyspark `spark.write.csv` function first which it can merge `part-xxxx` to a final file ?

**Comment by HyukjinKwon** [comment]
To merge part-xxx files, you can do `df.coalesce(1).write.csv`. It doesn't necessarily have to be same for now. You can just simply switch it to `spark.write.csv`. There's an example, for instance, see `to_parquet`, `to_delta`.

**Comment by HyukjinKwon** [comment]
BTW, I think we should fix `to_json` as well.

**Comment by RainFung** [comment]
`spark.write` will create a directory and a _success file.So i should do as below three steps:
1. `df.coalesce(1).write.csv`
2. remove _success and rename `part-xxxx` 
3. delete directory
I think it's too bother so i suggest to import origin pyspark function.

**Comment by HyukjinKwon** [comment]
We can just write them in a directory. It's fine. Just call df.write.csv.

**Comment by RainFung** [comment]
https://github.com/databricks/koalas/pull/557

**Comment by rxin** [comment]
If you add a coalesce, you will run into the same issue that the CSV file writing is not parallelized. 

It's probably best to have an option to indicate whether we allow multiple output files, and explain what that means in terms of tradeoffs.

**Comment by HyukjinKwon** [comment]
@itholic, are you interested in taking this over? Basically we should add an option that combines partitions when we write out the files. We should add it in `to_csv`, `to_json`, `to_parquet`, and `to_spark_io`.

**Comment by itholic** [comment]
@HyukjinKwon, Seems interesting. I'll take this over :)

**Comment by itholic** [comment]
@HyukjinKwon 
Why don't we just set the `num_files` parameter to 1 for combining output files into a single file?

**Comment by HyukjinKwon** [comment]
Yes, I think this case was fixed as of https://github.com/databricks/koalas/pull/677
