### ISSUE TITLE
 Import Error for "import databricks.koalas" -  ImportError: cannot import name 'infer_dtype_from_object'

### ISSUE THREAD

**Issue by SaurabhNeklikar** [databricks/koalas#525]
Getting Import error while importing koalas in databricks notebook. It was working fine until yesterday.

Running - 
import databricks.koalas as ks

Error -

ImportError: cannot import name 'infer_dtype_from_object'

**Comment by ueshin** [comment]
Hi @SaurabhNeklikar,
Thanks for reporting this.
Could you provide what versions you are using, pyarrow, pandas, and numpy?

**Comment by SaurabhNeklikar** [comment]
Hi,

I am running on below Databricks Runtime Version –

5.4 ML (includes Apache Spark 2.4.3, Scala 2.11)

So whichever is default versions for this cluster. Would this information help? Or need specific versions of individual packages?

Thanks & Regards,

Saurabh Neklikar
Information Technology
William Blair
The William Blair Building | 150 North Riverside Plaza, Chicago, Illinois 60606
+1 312 364 8266 direct
sneklikar@williamblair.com<mailto:sneklikar@williamblair.com> | williamblair.com<http://www.williamblair.com/>
Facebook<https://www.facebook.com/WilliamBlairCo/> | LinkedIn<https://www.linkedin.com/company/166939> | YouTube<https://www.youtube.com/channel/UC7CPnCaTlZcLxOF7WFwY0uw> | Twitter<https://twitter.com/WilliamBlairCo>

**Comment by ueshin** [comment]
Thanks, that's enough.
I guess the new release `0.10.0` which was released a few hours ago with pandas `0.23` causes such an error.
Is it possible to downgrade Koalas to `0.9.0`?

**Comment by SaurabhNeklikar** [comment]
How do I do that?

Saurabh Neklikar
Information Technology
William Blair
The William Blair Building | 150 North Riverside Plaza, Chicago, Illinois 60606
+1 312 364 8266 direct
sneklikar@williamblair.com<mailto:sneklikar@williamblair.com> | williamblair.com<http://www.williamblair.com/>
Facebook<https://www.facebook.com/WilliamBlairCo/> | LinkedIn<https://www.linkedin.com/company/166939> | YouTube<https://www.youtube.com/channel/UC7CPnCaTlZcLxOF7WFwY0uw> | Twitter<https://twitter.com/WilliamBlairCo>

**Comment by ueshin** [comment]
I think `Libraries` tab in your cluster configuration contains `koalas`, then replace the `koalas` installation with `koalas==0.9`.

**Comment by SaurabhNeklikar** [comment]
Got it. Thanks.

Sent from my iPhone

On Jul 3, 2019, at 12:29 PM, Takuya UESHIN <notifications@github.com<mailto:notifications@github.com>> wrote:


I think Libraries tab in your cluster configuration contains koalas, then replace the koalas installation with koalas==0.9.

**Comment by ueshin** [comment]
Hi @SaurabhNeklikar, we've just released `0.11.0` to fix the regression with pandas `0.23`.
We'd appreciate if you would try again with the latest release.

Thank you again for reporting this issue!

**Comment by SaurabhNeklikar** [comment]
Hi,

Yes it is working with the latest release too. Thanks for taking care.

Thanks & Regards,

Saurabh Neklikar
Information Technology
William Blair
The William Blair Building | 150 North Riverside Plaza, Chicago, Illinois 60606
+1 312 364 8266 direct
sneklikar@williamblair.com<mailto:sneklikar@williamblair.com> | williamblair.com<http://www.williamblair.com/>
Facebook<https://www.facebook.com/WilliamBlairCo/> | LinkedIn<https://www.linkedin.com/company/166939> | YouTube<https://www.youtube.com/channel/UC7CPnCaTlZcLxOF7WFwY0uw> | Twitter<https://twitter.com/WilliamBlairCo>
