### ISSUE TITLE
import databricks.koalas as ks fails in 'import matplotlib.artist as martist'

### ISSUE THREAD

**Issue by sermolin** [databricks/koalas#526]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-0376b7c81ae0> in <module>()
----> 1 import databricks.koalas as ks

~/anaconda3/envs/python3/lib/python3.6/site-packages/databricks/koalas/__init__.py in <module>()
     37 
     38 from databricks.koalas.frame import DataFrame
---> 39 from databricks.koalas.indexes import Index, MultiIndex
     40 from databricks.koalas.series import Series
     41 from databricks.koalas.typedef import pandas_wraps

~/anaconda3/envs/python3/lib/python3.6/site-packages/databricks/koalas/indexes.py in <module>()
     33 from databricks.koalas.generic import max_display_count
     34 from databricks.koalas.missing.indexes import _MissingPandasLikeIndex, _MissingPandasLikeMultiIndex
---> 35 from databricks.koalas.series import Series
     36 
     37 

~/anaconda3/envs/python3/lib/python3.6/site-packages/databricks/koalas/series.py in <module>()
     37 from databricks.koalas.internal import IndexMap, _InternalFrame
     38 from databricks.koalas.missing.series import _MissingPandasLikeSeries
---> 39 from databricks.koalas.plot import KoalasSeriesPlotMethods
     40 from databricks.koalas.utils import validate_arguments_and_invoke_function
     41 from databricks.koalas.datetimes import DatetimeMethods

~/anaconda3/envs/python3/lib/python3.6/site-packages/databricks/koalas/plot.py in <module>()
     19 import pandas as pd
     20 
---> 21 from matplotlib.axes._base import _process_plot_format
     22 from pandas.io.formats.printing import pprint_thing
     23 from pandas.plotting._core import (

~/anaconda3/envs/python3/lib/python3.6/site-packages/matplotlib/axes/__init__.py in <module>()
----> 1 from ._subplots import *
      2 from ._axes import *

~/anaconda3/envs/python3/lib/python3.6/site-packages/matplotlib/axes/_subplots.py in <module>()
      3 
      4 from matplotlib import cbook, docstring
----> 5 import matplotlib.artist as martist
      6 from matplotlib.axes._axes import Axes
      7 from matplotlib.gridspec import GridSpec, SubplotSpec

~/anaconda3/envs/python3/lib/python3.6/site-packages/matplotlib/artist.py in <module>()
     55 
     56 
---> 57 class Artist(object):
     58     """
     59     Abstract base class for objects that render into a FigureCanvas.

~/anaconda3/envs/python3/lib/python3.6/site-packages/matplotlib/artist.py in Artist()
     62     """
     63     @cbook.deprecated("3.1")
---> 64     @property
     65     def aname(self):
     66         return 'Artist'

~/anaconda3/envs/python3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py in deprecate(obj, message, name, alternative, pending, addendum)
    180                 pass
    181     """
--> 182 
    183     def deprecate(obj, message=message, name=name, alternative=alternative,
    184                   pending=pending, obj_type=obj_type, addendum=addendum):

AttributeError: 'property' object has no attribute '__name__'

--------
I am installing koalas in SageMaker Jupyter notebook environment.
Prior to calling "import databricks.koalas as ks' I did the following:
  !conda install 'pyspark>=2.4' -c conda-forge -y
  !conda install koalas -c conda-forge -y
  !pip install arrow 
  !pip install matplotlib --upgrade

I tried replacing 'conda install' with 'pip install' for pyspark and koalas - no effect, the error was still there

**Comment by leihuang** [comment]
May I ask if you solved the problem and how? I have the same problem. Thanks!

**Comment by leihuang** [comment]
So it seems it's a `matplotlib` problem, hence your closing the issue, right?
