### ISSUE TITLE
Import from pyspark.sql.dataframe.DataFrame

### ISSUE THREAD

**Issue by jonathanc42** [databricks/koalas#550]
There be a method to import from a spark dataframe.

**Comment by HyukjinKwon** [comment]
Can you clarify what it means? For instance, can you show an example code you want to do?

**Comment by HyukjinKwon** [comment]
you can convert Koalas dataframe into Spark dataframe by `to_dataframe`.

**Comment by jonathanc42** [comment]
> you can convert Koalas dataframe into Spark dataframe by `kdf.to_spark()`.

Hi HyukjinKwon, what I meant to do was vise versa to convert spark dataframe to koalas dataframe. I don't think it should be one way only especially when I am evaluating koalas and work with spark together.

**Comment by HyukjinKwon** [comment]
Which other way would you suggest?
