### ISSUE TITLE
Unexpected behavior in ks.merge how='outer'

### ISSUE THREAD

**Issue by shreyanshu** [databricks/koalas#551]
Hi,

I have been trying to perform a outer join between two koalas dataframes on basis of a column, but am getting very unexpected results. Below is an example,

`left_kdf = ks.DataFrame({'A': [1, 2]})`
`right_kdf = ks.DataFrame({'B': ['x', 'y', 'z'], 'A':[3, 4, 1]})`
`left_kdf.merge(right_kdf, on=["A"], how='outer')`

The output that I get is 

![image](https://user-images.githubusercontent.com/11263917/60987332-16bab200-a361-11e9-8566-8ae4f4e53bce.png)

However, if this is a SQL style join as said in the documentation, the output should be something like,
 
![image](https://user-images.githubusercontent.com/11263917/60987566-95175400-a361-11e9-9ee1-8fbb0d55f90e.png)

The None part (in Column B) is discussed in [#263](https://github.com/databricks/koalas/issues/263)

What concerns me are the missing values in column A.

**Comment by ueshin** [comment]
Hi @shreyanshu, Thanks for the report.
I submitted a PR to fix this issue. (#595)
Could you review the PR if you have time?
Thanks!
