### ISSUE TITLE
How to convert from Koala dataframe to Spark dataframe

### ISSUE THREAD

**Issue by shreyanshu** [databricks/koalas#553]
Is there a way to convert a Koalas DF to a Spark DF,

This is what I tried,
`import databricks.koalas as ks`
`kdf = ks.DataFrame({'B': ['x', 'y', 'z'], 'A':[3, 4, 1], 'E':[1,1,1]})`
`from pyspark.sql import SparkSession`
`spark = SparkSession.builder.getOrCreate()`
`sdf = spark.createDataFrame(kdf)`
 
But it gives the following error,
/lib/python3.5/site-packages/databricks/koalas/frame.py", line 5322, in _pd_getitem
    raise NotImplementedError(key)
NotImplementedError: 0

**Comment by HyukjinKwon** [comment]
you can do it via `kdf.to_dataframe()`
