### ISSUE TITLE
df.apply() is not implemented

### ISSUE THREAD

**Issue by hsubbaraj** [databricks/koalas#554]
This is a pretty common function used in pandas notebooks, and its functionality is a little different than `applymap()`. I can start implementing this!
```python
>>> df = pd.DataFrame([[4, 9],] * 3, columns=['A', 'B']) 
>>> df
   A  B
0  4  9
1  4  9
2  4  9

>>> df.apply(np.sum, axis=0)
A    12
B    27
dtype: int64

>>> df.apply(np.sum, axis=0)
A    12
B    27
dtype: int64
```

**Comment by HyukjinKwon** [comment]
Yea, we should implement this. Problem is that we should allow different length, which currently `pandas_udf` doesn't support.

**Comment by HyukjinKwon** [comment]
This actually requires mapPartitionsInPandas in upcoming Spark 3.0 (see https://issues.apache.org/jira/browse/SPARK-28198)

**Comment by ueshin** [comment]
I'd close this as well since duplicated. #65
