### ISSUE TITLE
next function to devlop

### ISSUE THREAD

**Issue by RainFung** [databricks/koalas#573]
Most of the remaining functions are related to index and sorting. Full sort is usually required But it can cause spark programs to run very slowly in spark. Basically, the computational class functions have been completed, and what is the focus of the next development?

**Comment by HyukjinKwon** [comment]
Usually we target to add new features to bring it to usable state by pandas users at least. Nevertheless, the target of the next release is a bit different.

1. Find out and officially don't support some APIs, for instance, `to_pickle`. See https://github.com/databricks/koalas/pull/515

2. Supporting multi-index for columns. See, for instance, https://github.com/databricks/koalas/issues/511

3. Some APIs against `IndexOpsMixIn` don't work in Index. It should be fixed.

> Most of the remaining functions are related to index and sorting. Full sort is usually required But it can cause spark programs to run very slowly in spark. 

We should implement them anyway. If sorting is necessary, it's inevitable to execute the sort across the dataset. Please focus on implementing them if you're able.

Also, from my perspective, there are still some more APIs to implement. For instance, `DataFrame.aggregate`, `DataFrame.filter`, `DataFrame eval`, etc. Also, take a look for `missing/groupby.py`.

**Comment by ueshin** [comment]
Thanks for the summary.
I'm going to work on the basic infrastructure for 2) Supporting multi-index columns, also related to #301.

**Comment by HyukjinKwon** [comment]
0.14.0 is released. I am closing this.
