### ISSUE TITLE
Support pandas 0.25.

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#578]
Seems like we don't support pandas 0.25 related to plot functions so far.
https://travis-ci.com/databricks/koalas/jobs/217695045

**Comment by ueshin** [comment]
Hi @dvgodoy,
Could you take a look at this and help us support pandas 0.25?
Thanks!

**Comment by HyukjinKwon** [comment]
I happened to take a look around this one today .. I opened a PR.
