### ISSUE TITLE
Cannot operate on 2 different ks.DataFrames

### ISSUE THREAD

**Issue by patryk-oleniuk** [databricks/koalas#624]
Example:
```python
kdf = ks.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5],
              "car_id": ['A','A','A','B','B'], 
              "battery_charge": [100, 90, 80,100,90]
              })

grouped = kdf.groupby('car_id')

print(grouped.last() - grouped.first() )
```
results in:
```python
ValueError: sub with another DataFrame or a sequence is currently not supported; however, got databricks.koalas.frame.DataFrame.
```
I ran into that error multiple times with different operations. This, together with implementing the `DataFrame.apply()`  ( https://github.com/databricks/koalas/issues/554 ) and re-implementing the `groupby.apply()` ( https://github.com/databricks/koalas/issues/409 )  is my current biggest pain in using the package.

**Comment by HyukjinKwon** [comment]
Thanks for opening issues and testing it out. Computing between different DataFrames are possible I guess (via joining based upon indexes). However, we're not doing that cus it's potentially expensive.

Maybe, we can add an env to allow this case? WDYT @rxin and @ueshin?

This ticket basically describe the case:

```python
df1 = ...
df2 = ...

df3 = df1.a + df2.b
```

**Comment by HyukjinKwon** [comment]
We might have to allow an operation between DataFrames and have a .. environment variable to control it since that's expensive ..? Maybe let me give a shot and discuss there if we need that or not.

**Comment by rxin** [comment]
Yea that makes sense. Implement it. Hide it behind a flag and have it off by default. The error message can say set x to true to turn it on, but it could be computationally expensive due to an implicit join.

**Comment by HyukjinKwon** [comment]
It actually took me a while to fix. Here's the PR - https://github.com/databricks/koalas/pull/633.

**Comment by HyukjinKwon** [comment]
@patryk-oleniuk, it took me a while to resolve all. Now all related issues were resolved. should be able to proceed further. Thanks.

**Comment by HyukjinKwon** [comment]
BTW, to enable this feature, `OPS_ON_DIFF_FRAMES` environment variable should be set to `true` for now. It will be a proper option as of https://github.com/databricks/koalas/commit/94adf06d622aaac1eb05c03407db8a1abc01632c . Will let you know when we do that.
