### ISSUE TITLE
GroupBy.nlargest and GroupBy.nsmallest

### ISSUE THREAD

**Issue by patryk-oleniuk** [databricks/koalas#631]
this method is not implemented:
Pandas reference:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.SeriesGroupBy.nlargest.html

**Comment by RainFung** [comment]
I will create pr for this function

**Comment by HyukjinKwon** [comment]
Thank you so much, @RainFung

**Comment by RainFung** [comment]
There are some problem in thess function https://github.com/pandas-dev/pandas/issues/27894. I will create PR when the pandas issue solved.

**Comment by RainFung** [comment]
https://github.com/databricks/koalas/pull/654

**Comment by RainFung** [comment]
I have finish it. Can you close this issue?

**Comment by patryk-oleniuk** [comment]
Closing, thanks so much @RainFung for your work!
