### ISSUE TITLE
Is there a way to config spark driver and executor memory in Koalas

### ISSUE THREAD

**Issue by juveseason** [databricks/koalas#632]
I was migrating a pandas code to Koalas, hoping to get speedup via Spark.
It was running ok when my input data set was small, about 1 million rows.
But when I try to use a larger data set, about 11 million rows, after running for an hour, it reported out of memory error.

I assume this is due to the spark executor and driver memory setting, maybe the default setting is not big enough?
- spark.driver.memory
- spark.executor.memory

I also checked my server memory usuage graph, total RAM is 64GB,  it had more than 40GB of free memory during the run.

**Comment by HyukjinKwon** [comment]
Currently, Koalas does not support to set Spark properties out of the box.

It should be set into Spark itself currently it should be:

1. Initialises the Spark context first in codes.

```python
from pyspark import SparkConf, SparkContext
conf = SparkConf()
conf.setAppName("...")
conf.setMaster('...')
conf.set('spark.executor.memory', '2g')
...
SparkContext(conf=conf)  # this will automatically sets the configurations into the Spark context that's used in Koalas

import databricks.koalas as ks
...
```

2. Set the configuration values under `$SPARK_HOME/conf/spark-defaults.conf`.

**Comment by juveseason** [comment]
Thank you very much for the answer.

**Comment by HyukjinKwon** [comment]
Let me leave this closed for now.
