### ISSUE TITLE
Plot APIs in DataFrame

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#666]
pandas: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#plotting

We should implement DataFrame.plot APIs.

**Comment by charlesdong1991** [comment]
May I work on it? @HyukjinKwon

**Comment by HyukjinKwon** [comment]
Of course please go ahead!

**Comment by raghavansandhya** [comment]
@charlesdong1991  Let me know If I can help with any sub modules?

**Comment by HyukjinKwon** [comment]
Please implement each plot API at https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#plotting. If anyone is working on the sub items, please leave a comment that says you're working on that to avoid to duplicate efforts.

**Comment by charlesdong1991** [comment]
@raghavansandhya sure, if you want to implement any sub module, pls go ahead! I am still preparing my PR which is not ready for review.

Just as @HyukjinKwon said, if you did any implementation, pls leave a comment so I will skip that module to avoid duplicate efforts.

**Comment by HyukjinKwon** [comment]
All other plots except:

- [`DataFrame.plot.hexbin`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.hexbin.html#pandas.DataFrame.plot.hexbin)
- [`DataFrame.boxplot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.boxplot.html#pandas.DataFrame.boxplot)

are implemented. @dvgodoy would you be interested in continuing the efforts?

**Comment by chengyineng38** [comment]
I just tried to create a boxplot using `DataFrame.boxplot` but am blocked since it's not yet implemented. Is this on the roadmap of being implemented?

**Comment by HyukjinKwon** [comment]
I'll resolve this ticket and file new issues for the two plot APIs not implemented yet, and then pin these issues

**Comment by HyukjinKwon** [comment]
Here: https://github.com/databricks/koalas/issues/1751
