### ISSUE TITLE
java.io.IOException: No FileSystem for scheme: s3

### ISSUE THREAD

**Issue by manugarri** [databricks/koalas#727]
Im trying to do a simple s3 IO (ignore the gzip argument for now):

```
df = ks.read_spark_io(
"s3://BUCKET/*.json.gz",
    format='json', compression="gzip")
```

However I get the classic spark error:

```
: java.io.IOException: No FileSystem for scheme: s3
```

Which in spark is usually fixed by adding the aws jar. 

How do we fix this in koalas?

**Comment by HyukjinKwon** [comment]
Seems like you need to specify hadoop-aws package (for instance, `org.apache.hadoop:hadoop-aws:2.7.2`). 

Currently, Koalas does not support to set Spark properties out of the box.

It should be set into Spark itself currently. There are two ways I can think of for now:

1. Initialises the Spark context first in codes.

```python
from pyspark import SparkConf, SparkContext
conf = SparkConf()
conf.setAppName("...")
conf.setMaster('...')
conf.set('spark.jars.packages', 'org.apache.hadoop:hadoop-aws:2.7.2')
...
SparkContext(conf=conf)  # this will automatically sets the configurations into the Spark context that's used in Koalas

import databricks.koalas as ks
...
```

2. Set the configuration values under `$SPARK_HOME/conf/spark-defaults.conf`.

**Comment by manugarri** [comment]
I see, that makes sense, thanks!
