### ISSUE TITLE
Can't predict from model with more than 256 features

### ISSUE THREAD

**Issue by jimfulton** [databricks/koalas#745]
When running a model to generate predictions, koalas+mlflow create PySpark UDFs that take an argument per feature column.

PySpark currently has a limitation of 256 arguments per UDF.  This limitation seems shallow and easy to hack around. See https://issues.apache.org/jira/browse/SPARK-28978.

Of course, I tried koalas with a model with 500+ features. :)

Unless I'm mistaken (quite possible), this is an easy fix to PySpark.  I'm creating the issue here because of the impact on potential koalas users and hoping y'all can encourage the PySpark fix.

**Comment by HyukjinKwon** [comment]
This is fixed at SPARK-28978.
