### ISSUE TITLE
Filtering rows throws error when result is empty

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#772]
In Pandas, if I filter for rows and there are none that satisfy the condition, it returns an empty DataFrame.

With Koalas, it throws an error. I think it should return an empty dataframe, like Pandas.

Note: data is a koalas dataframe in the screenshot below
![Screen Shot 2019-09-11 at 4 11 21 PM](https://user-images.githubusercontent.com/6416014/64741906-19e03480-d4af-11e9-9a4e-5d8bfbd4f260.png)

**Comment by itholic** [comment]
Thank you for your issue reporting!

Sorry, but if you don't mind, could you show me the python code you used to make Koalas DataFrame if it possible?

I just tested it with the example you uploaded. In my case, both results are returning an Empty DataFrame like below:

![스크린샷 2019-09-12 오전 10 14 01](https://user-images.githubusercontent.com/44108233/64746452-89553300-d546-11e9-8bc2-4a2f29757b8c.png)

Thanks for your reporting again, Have a nice day :)

**Comment by itholic** [comment]
Thank you for your issue reporting!

Sorry, but if you don't mind, could you show me the python code you used to make Koalas DataFrame if it possible?

I just tested it with the example you uploaded.

In my case, both results are returning an Empty DataFrame like below:

![스크린샷 2019-09-12 오전 10 14 01](https://user-images.githubusercontent.com/44108233/64746452-89553300-d546-11e9-8bc2-4a2f29757b8c.png)

Thanks for your reporting again, Have a nice day :)

**Comment by itholic** [comment]
Thanks for your issue reporting!

Sorry, but if you don't mind, could you show me the python code you used to make Koalas DataFrame if it possible?

I just tested it with the example you uploaded.

In my case, both results are returning an Empty DataFrame like below:

![스크린샷 2019-09-12 오전 10 14 01](https://user-images.githubusercontent.com/44108233/64746452-89553300-d546-11e9-8bc2-4a2f29757b8c.png)

Thanks for your reporting again, Have a nice day :)

**Comment by brookewenig** [comment]
When going from a Pandas DF to Koalas DF, I agree, there are no issues. However, this issue seems to come up when reading directly from a CSV file. I can reproduce this issue with two different CSV sources. Take a look at the notebook linked here and you can see the error: https://databricks-prod-cloudfront.cloud.databricks.com/public/793177bc53e528530b06c78a4fa0e086/0/15446625/100107/latest.html

**Comment by itholic** [comment]
Thanks! i've just reproduced your situation and try to find why this issue happens.

If you look at `/databricks-datasets/bikeSharing/data-001/day.csv`, you can see a line like below:

<img width="922" alt="스크린샷 2019-09-14 오후 4 04 34" src="https://user-images.githubusercontent.com/44108233/64904767-72ab0980-d709-11e9-96ea-fc08856d3a0c.png">

with above `*** WARNING` line, i can see the same issue you faced.

but remove this line and reproduce it, have worked well like below:

```python
>>> bike_df = ks.read_csv("day.csv")
>>> bike_df[bike_df["season"] == 6]
Empty DataFrame
Columns: [instant, dteday, season, yr, mnth, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed, casual, registered, cnt]
Index: []
>>>
```

Right now maybe this looks just a data problem,

But maybe we should block internally `csv_read` from Inappropriate source file.

@HyukjinKwon , @ueshin Maybe could you check this If you available where am i handling this issue properly or not?

**Comment by ueshin** [comment]
Hmm, that's interesting. Let me check, too. Thanks for sharing the notebook!

**Comment by harupy** [comment]
I created a simple notebook to investigate this issue.

https://github.com/harupy/temp/blob/master/koalas_filter_issue.ipynb

It seems the error occurs when pyarrow converts a datetime column.

**Comment by HyukjinKwon** [comment]
Thanks @harupy for analysis and the codes!
