### ISSUE TITLE
Clear Plots

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#773]
When I plot a DataFrame, then in a separate cell plot again, the first plot is not cleared.

I think the plots should be auto-cleared (e.g. plt.clf()). 
![Screen Shot 2019-09-11 at 2 37 58 PM](https://user-images.githubusercontent.com/6416014/64742099-ddf99f00-d4af-11e9-9ffa-da8a3c1141c4.png)

**Comment by harupy** [comment]
@brookewenig 

I faild to reproduce this issue. Did I miss something?

## Environment

- Databricks Community Edition
- Runtime version: 6.0 beta
- koalas version: 0.17.0
- notebook: [click here](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/7872419575180801/3144542009007501/4764411236566651/latest.html)

<img width="501" alt="Screen Shot 2019-09-14 at 16 02 30" src="https://user-images.githubusercontent.com/17039389/64904740-1cd66180-d709-11e9-9fb0-8a99c386109b.png">

**Comment by harupy** [comment]
I digged into how `display` works with the code below.

```
import inspect
lines = inspect.getsource(display)
print(lines)
```

The output says:

```
...
elif type(input).__module__ == 'matplotlib.figure' and type(input).__name__ == 'Figure':
    _format = 'png'
    extension = '.' + _format
    figureFile = NamedTemporaryFile(delete=False, suffix = extension)
    input.savefig(figureFile, format = _format, transparent = True)
    figureFile.close()
    # for pandasDF.plot to work well, need to close the figure, otherwise the same figure
    # will continued to be use across calls to pandasDF.plot.
    mpl.pyplot.close(input)
    self.figures.append(figureFile.name)
...
```
The full output is included in [this notebook](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/7872419575180801/3144542009007501/4764411236566651/latest.html).

**Comment by harupy** [comment]
I also checked 5.5 LTS.

```
...
elif type(input).__module__ == 'matplotlib.figure' and type(input).__name__ == 'Figure':
    _format = 'png'
    extension = '.' + _format
    figureFile = NamedTemporaryFile(delete=False, suffix = extension)
    input.savefig(figureFile, format = _format, transparent = True)
    self.figure = figureFile.name
    figureFile.close()
...
```

**Comment by harupy** [comment]
I can reproduce almost the same result as @brookewenig on `5.5 conda beta`.
<img width="498" alt="Screen Shot 2019-09-14 at 19 26 34" src="https://user-images.githubusercontent.com/17039389/64906806-adbb3600-d725-11e9-9997-f8fffa3d49d2.png">

**Comment by harupy** [comment]
This issue doesn't happen on Jupyter ([notebook](https://github.com/harupy/temp/blob/master/koalas_plot_issue.ipynb)).

![Screenshot from 2019-09-14 20-04-16](https://user-images.githubusercontent.com/17039389/64907300-6cc62000-d72b-11e9-9db3-e6d0073e0403.png)

**Comment by ueshin** [comment]
@harupy Thanks for the investigation!
Sounds like it's related to how the `display` function handles `matplotlib`.
Does that mean it happens even with pandas DataFrame?

**Comment by harupy** [comment]
Yes, pandas DF behaves the same.

**Comment by harupy** [comment]
Found out why multple plots on different cells don't interfere **on Juypter**.

https://github.com/ipython/ipython/blob/5bcd244b377b0c3dd626eba08b5a1776552039ca/IPython/core/display.py#L1466-L1490

> By default, the inline backend used in the IPython Notebook will **close all
    matplotlib figures automatically after each cell is run**. This means that
    plots in different cells won't interfere. Sometimes, you may want to make
    a plot in one cell and then refine it in later cells.

**Comment by harupy** [comment]
Quick (but dirty) workaround on Databricks runtime older than `6.0` is

```python
import matplotlib.pyplot as plt

get_ipython().events.register('post_run_cell', lambda: plt.close('all'))
```

### Ref.
https://ipython.readthedocs.io/en/stable/config/callbacks.html#ipython-events

### Notebook
https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/7872419575180801/3144542009007501/4764411236566651/latest.html

**Comment by HyukjinKwon** [comment]
Perfect analysis @harupy! Thank you so much.

**Comment by HyukjinKwon** [comment]
@brookewenig, I think workaround was provided properly and seems not an issue in koalas. Please let me know if you think further action is required for this ticket.
