### ISSUE TITLE
When using drop on koalas dataframe and then merge, dropped columns persist

### ISSUE THREAD

**Issue by kermany** [databricks/koalas#782]
It seems that after dropping a col from a kdf, if we merge it with another one and create a new dataframe, the dropped column persists. 
This is in databricks environment
e.g:
```
ks.__version__
'0.17.0'
df1=ks.DataFrame({'c1':[1,2,3],'c2':['a','b','c'],'c3':[0,1,2]})
df2=ks.DataFrame({'c1':[1,2,3],'c4':['x','y','z']})
df1=df1.drop('c2')
df3 = df1.merge(df2,on=['c1'])
print(df1.columns,df3.columns)
Index(['c1', 'c3'], dtype='object') Index(['c1', 'c2', 'c3', 'c4'], dtype='object')
```

**Comment by itholic** [comment]
Hi kermany :)

Maybe if you can, Could you give some detail environment your code are running at?
(maybe OS, python version, etc?)

because In my case, i failed to reproduce situation what you faced, 

and there're no problem in jupyter notebook, python interpreter, python script either like below:

<img width="847" alt="스크린샷 2019-09-17 오후 3 20 26" src="https://user-images.githubusercontent.com/44108233/65016252-c2364300-d95e-11e9-88ac-d6781d4266d0.png">

```python
>>> df1=ks.DataFrame({'c1':[1,2,3],'c2':['a','b','c'],'c3':[0,1,2]})
>>> df2=ks.DataFrame({'c1':[1,2,3],'c4':['x','y','z']})
>>> df1=df1.drop('c2')
>>> df3 = df1.merge(df2,on=['c1'])
>>> print(df1.columns,df3.columns)
Index(['c1', 'c3'], dtype='object') Index(['c1', 'c3', 'c4'], dtype='object')
```

```python
# issue782.py
import databricks.koalas as ks

df1=ks.DataFrame({'c1':[1,2,3],'c2':['a','b','c'],'c3':[0,1,2]})
df2=ks.DataFrame({'c1':[1,2,3],'c4':['x','y','z']})
df1=df1.drop('c2')
df3 = df1.merge(df2,on=['c1'])
print(df1.columns,df3.columns)
```

```shell
$ python issue782.py
Index(['c1', 'c3'], dtype='object') Index(['c1', 'c3', 'c4'], dtype='object')
```

Thanks for reporting, Have a nice day :)

**Comment by HyukjinKwon** [comment]
hey @kermany thanks for reporting and @itholic thanks for trying it out.

Which koalas version did you use @kermany?

**Comment by kermany** [comment]
Thanks @itholic! This is using Databricks notebooks with koalas 0.17.0

**Comment by harupy** [comment]
The internal dataframe still has `c2` even after dropping it.

```
df1 = ks.DataFrame({'c1': [1, 2, 3], 'c2': ['a','b','c'], 'c3': [0, 1, 2]})
df1 = df1.drop('c2')
df1._internal.sdf.show()

+-----------------+---+---+---+
|__index_level_0__| c1| c2| c3|
+-----------------+---+---+---+
|                0|  1|  a|  0|
|                1|  2|  b|  1|
|                2|  3|  c|  2|
+-----------------+---+---+---+
```

https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/7872419575180801/138200887632135/4764411236566651/latest.html

**Comment by harupy** [comment]
I think I found why this issue is happening for 0.17.0 (which me and @kermany use).

- `drop` doesn't mutate `DataFrame._internal.sdf` but `data_columns` and `column_index`.
- For 0.17.0, `merge` uses `Dataframe._sdf` which is `Dataframe._internal.sdf`.

**Comment by harupy** [comment]
But, from the commit below, `merge` starts using `DataFrame._internal.spark_internal_df` which selects columns with `data_columns` ([code](https://github.com/databricks/koalas/blob/468a757b658872c5379ac65ee9bcc8b1147bd3c9/databricks/koalas/internal.py#L570)).

https://github.com/databricks/koalas/commit/468a757b658872c5379ac65ee9bcc8b1147bd3c9#diff-5ba644c40e914732959b9b4867f30c53L4991

I think @itholic uses the latest version which includes this commit and fails to reproduce this issue.

**Comment by HyukjinKwon** [comment]
Seems like `drop` should actually drop the column in Spark DataFrame; otherwise, it might cause such issues somewhere else.

Yes, I used the latest branch too to reproduce.

**Comment by HyukjinKwon** [comment]
@harupy since you debugged most of it, are you interested in fixing it? in `drop()`, I think `self._sdf` should drop the given column as well, not only in its metadata.

**Comment by ueshin** [comment]
IMO, we should manage the columns only in metadata in such a case to avoid creating Spark DataFrame, but I have to admit I don't make it to handle all the cases yet.

**Comment by HyukjinKwon** [comment]
Maybe we can drop the column for now ..? and we find a better way to clean up the unnecessary DataFrame creations.

**Comment by HyukjinKwon** [comment]
Since the issue itself is now resolved, let me anyway resolve this issue.
