### ISSUE TITLE
Implement DataFrame.pop

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#788]
Select one Series and drop it in the DataFrame in-place (see https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pop.html?highlight=pop#pandas.DataFrame.pop)

Related to https://github.com/databricks/koalas/issues/362

**Comment by HyukjinKwon** [comment]
cc @harupy and @itholic, are you interested in this?

**Comment by itholic** [comment]
i'm working on it

**Comment by harupy** [comment]
@itholic thanks!

**Comment by harupy** [comment]
[The pandas doc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pop.html) says `pop` takes `str`, but it also can take a tuple of `str` when a dataframe has multi-index columns.

@HyukjinKwon 
Do you think this should be covered in docstring and tests?

**Comment by HyukjinKwon** [comment]
That would be so nice if they are covered.

**Comment by itholic** [comment]
@harupy It sounds such a nice suggestion 😃 
I just added DataFrame.pop with basic example at #791 ,
And will try to support with tuple for multi-index also as you commented.

**Comment by ueshin** [comment]
Thanks for considering the multi-index columns support.
I believe now that we have a basic infrastructure to support multi-index columns and tuple names for Series and Index using `column_index`. Actually managing Spark column names with `data_columns` is less useful now. We should rather first handle `column_index` properly.
I'm still working on fixing existing APIs. Hopefully we can think of multi-index columns from the beginning when we add new APIs.
