### ISSUE TITLE
pivot_table function with renaming columns

### ISSUE THREAD

**Issue by thoo** [databricks/koalas#804]
Here is the example from the documentation. 

```python
df = ks.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                          "bar", "bar", "bar", "bar"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]},
                   columns=['A',  'C',  'E'])
df.pivot_table(values='E', index=['A'],
                        columns='C', aggfunc='sum')
```

The above code works as expected.  Then I rename the columns like 

```python
df.columns =['New_A','New_C','New_E']
print(df.columns)
```
This works fine with `applymap` and other functions like `to_datetime` but as soon as I use `pivot_table` , I got an error. 

```python
df.pivot_table(values='New_E', index=['New_A'],
                        columns='New_C', aggfunc='sum')
```
The above code will give the following error:

```python

KeyError: 'No StructField named New_E'

```

Is it not allowed to change the column name right now??  Thanks.

**Comment by harupy** [comment]
Seems like `df.columns = new_columns` doesn't change the internal dataframe columns.

```
>>> df._sdf.show()
+-----------------+---+-----+---+
|__index_level_0__|  A|    C|  E|
+-----------------+---+-----+---+
|                0|foo|small|  2|
|                1|foo|large|  4|
|                2|foo|large|  5|
|                3|foo|small|  5|
|                4|foo|small|  6|
|                5|bar|large|  6|
|                6|bar|small|  8|
|                7|bar|small|  9|
|                8|bar|large|  9|
+-----------------+---+-----+---+

```

**Comment by ueshin** [comment]
@harupy Actually the root cause is the `pivot_table` doesn't handle metadata (`_InternalFrame`) properly. This is the same as `merge` case at #782. So far fixing `columns` is easier way, though, but it doesn't fix the case multi-index columns are used.

**Comment by HyukjinKwon** [comment]
BTW, thanks for reporting this @thoo. the issue looks very easy to understand and reproduce.

**Comment by ueshin** [comment]
Shall we fix the `columns` setter to rename the Spark columns?
@itholic @harupy Do you want to fix it?

I'll handle `merge` and `pivot_table` soon.

**Comment by harupy** [comment]
I'll work on this.

**Comment by ueshin** [comment]
@harupy Great, thanks!

**Comment by itholic** [comment]
oh It seems pretty interesting, 
thanks for suggestion @ueshin ,
and go for it @harupy ! 😃
