### ISSUE TITLE
Feature request: pd.CategoricalDtype

### ISSUE THREAD

**Issue by thoo** [databricks/koalas#827]
It would be nice to have categoricalDtype like [pandas.CategoricalDtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.CategoricalDtype.html#pandas.CategoricalDtype).

**Comment by HyukjinKwon** [comment]
I think we should rather explicitly don't support this for now due to missing type and implementation in PySpark

**Comment by rxin** [comment]
This is like dictionary encoding right? One way to do it (rather complicated) is to have a translation layer in Koalas ourselves.

**Comment by thoo** [comment]
@rxin That's is correct. 
Currently, with pandas, we usually set the categorical columns for the training data as `X[cols] = X[cols].astype('category')` and then save the categorical dictionary. Then, we remap the dictionary to the test data.  It is similar to labelencoder from scikit-learn but can handle the unknown values in test dataset out of the box.

**Comment by amueller** [comment]
@thoo You can use OneHotEncoder in recent versions of sklearn to do that :)

@rxin The ``.astype('category')`` pattern to replace by integers and have a mapping to string categories is pretty common, it would be great to have something like that.

**Comment by HyukjinKwon** [comment]
This is under discussion and we're investigating the feasibility.

**Comment by itholic** [comment]
Now Koalas start to support the CategoricalDtype.

```python
>>> kdf = ks.DataFrame({"A": ["a", "b", "c", "a"]})
>>> kdf["A"].astype("category")
0    a
1    b
2    c
3    a
Name: A, dtype: category
Categories (3, object): ['a', 'b', 'c']
```
