### ISSUE TITLE
GroupBy.head

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#879]
Implement `GroupBy.head`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.head.html

**Comment by arrayslayer** [comment]
Hi,
I looked into how one could implement this.
I think that combining the existing standalone head logic with the groupby logic should be enough. That is, after doing group by as usual, we use sdf_limit(n) on the result.

If this makes sense, should I go ahead with this implementation?

Thanks!

**Comment by ueshin** [comment]
@arrayslayer Thanks for the comment!
I'm afraid I don't think the logic works, but I might miss something.
Please go ahead and feel free to submit the PR with your logic.

**Comment by itholic** [comment]
@arrayslayer hi mate, 😸 Are you planning to work on this??

**Comment by HyukjinKwon** [comment]
@itholic please go ahead to work on this. Seems inactive.

**Comment by itholic** [comment]
@HyukjinKwon Thanks for the comment :)
okay then i'm going to work on this from now on.
