### ISSUE TITLE
Series.reindex

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#881]
Implement `Series.reindex`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.reindex.html

**Comment by Patil2099** [comment]
@ueshin Can you explain a little bit about the issue?

**Comment by HyukjinKwon** [comment]
This is same as https://github.com/databricks/koalas/issues/882#issuecomment-538287853

**Comment by manesioz** [comment]
Hey, if no one is working on this I would like to give it a try. Seems like `reset_index()` is already implemented (https://github.com/databricks/koalas/blob/master/databricks/koalas/series.py#L997) but it doesnt provide the same functionality as Panda's `reindex`. Are you looking for `reset_index()` to be extended? Or an entirely new function? Let me know what you have in mind, thanks

**Comment by manesioz** [comment]
Is anyone working on this, or could I start a PR?

**Comment by HyukjinKwon** [comment]
Please go ahead!

**Comment by ktksq** [comment]
@manesioz hi, Are you planning to work on this??

**Comment by manesioz** [comment]
hi @ktksq I was planning on it but I have been busy lately with other things, please feel free to make a PR instead, sorry about that!

**Comment by raghavansandhya** [comment]
Hi @ktksq  are you working on this ?

**Comment by HyukjinKwon** [comment]
Seems not. @raghavansandhya, if you're interested in, please go ahead!

**Comment by venkateshdatta1993** [comment]
Hi @raghavansandhya are you working on this?

**Comment by raghavansandhya** [comment]
No I am working on the other group by unique issue as of now.. Please go ahead and start

**Comment by tahervali** [comment]
Hi @venkateshdatta1993 are you still working on this?

**Comment by venkateshdatta1993** [comment]
Hey @tahervali
No I'm working on another. Please go ahead and pick up.
Thanks.

**Comment by tyrinwu** [comment]
@tahervali are you working on it :P?

**Comment by hvardhan20** [comment]
Hey, I'd like to work on this.

**Comment by ueshin** [comment]
@hvardhan20 Please go ahead, thanks!

**Comment by itholic** [comment]
@hvardhan20  😺 👍

**Comment by LucasG0** [comment]
Hi, I may need this functionnality for #1007 so I started working on this. 
While testing, I saw that `assertPandasEqual` compares pandas series using `(left == right).all()`, which fails to compare two identical series containing NaNs. Is this intended ? I noticed pandas dataframes are compared using `equals()`.

**Comment by ueshin** [comment]
Sure, please go ahead!
For the testing, that's a good point. Let me try to change it to use `equals()`.

**Comment by LucasG0** [comment]
Just saw the edit, `almost=True` is fine, thanks !
