### ISSUE TITLE
SeriesGroupBy.nlargest/nsmallest

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#883]
Implement `SeriesGroupBy.nlargest` and `SeriesGroupBy.nsmallest`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.SeriesGroupBy.nlargest.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.SeriesGroupBy.nsmallest.html

**Comment by itholic** [comment]
I'm working on it

**Comment by HyukjinKwon** [comment]
Yea, seems it's already implemented.

**Comment by ueshin** [comment]
oops, sorry, I missed it.
