### ISSUE TITLE
DataFrame.unstack

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#886]
Implement `DataFrame.unstack`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unstack.html

**Comment by ag-og** [comment]
Any update on this issue?

**Comment by HyukjinKwon** [comment]
I investigated this for whole day, and seems we shouldn't implement this API. It creates rows * index columns:

```python
>>> df = pd.DataFrame({'A': ['a', 'b', 'c', 'd'], 'B': [1, 3, 5, 7], 'C': [2, 4, 6, 7]}, index=pd.MultiIndex.from_tuples([('X', 'A'), ('X', 'B'), ('Y', 'C'), ('Y', 'D')]))
>>> df
     A  B  C
X A  a  1  2
  B  b  3  4
Y C  c  5  6
  D  d  7  7
>>> df.unstack()
     A                   B                   C
     A    B    C    D    A    B    C    D    A    B    C    D
X    a    b  NaN  NaN  1.0  3.0  NaN  NaN  2.0  4.0  NaN  NaN
Y  NaN  NaN    c    d  NaN  NaN  5.0  7.0  NaN  NaN  6.0  7.0
```

I don't think this practically works since Spark partitions it row based. This is much worse than `transpose` we had to think multiple times. Let's don't do this for now.

**Comment by ueshin** [comment]
Makes sense. Shall we move it to "won't support" list?

**Comment by HyukjinKwon** [comment]
Sure, will do.
