### ISSUE TITLE
DataFrame.itertuples

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#887]
Implement `DataFrame.itertuples`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html

**Comment by ueshin** [comment]
I don't think we will support this kind of APIs. cc @HyukjinKwon

**Comment by dmitrypol** [comment]
are you planning to implement it?

**Comment by HyukjinKwon** [comment]
Sorry I missed the cc, @ueshin. Yeah, I don't think so too in general. One possibility I was thinking of was `toLocalIterator`, though ..

**Comment by HyukjinKwon** [comment]
@dmitrypol not yet sure. maybe we could map it to `toLocalIterator` but this kind of API is discouraged by design in general in Koalas. Needs some discussion.

**Comment by itholic** [comment]
Let me close this since we added this API at https://github.com/databricks/koalas/pull/1960

cc @dmitrypol FYI
