### ISSUE TITLE
Loc: Setting value for an entire row

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#894]
Could you please implement this functionality?

df.loc[['viper', 'sidewinder'], ['shield']] = 50

A Databricks' customer uses this style of programming a lot, and on the docs, I see it isn't supported: https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.loc.html

**Comment by itholic** [comment]
i'm working on it.

**Comment by itholic** [comment]
created PR #905  to solve this.
