### ISSUE TITLE
Some parameters in plot.py are surrounded by backticks

### ISSUE THREAD

**Issue by harupy** [databricks/koalas#897]
Some parameters in `plot.py` are surrounded by backticks. Should they be removed?

<img width="760" alt="Screen Shot 2019-10-05 at 15 33 03" src="https://user-images.githubusercontent.com/17039389/66251007-8df7ba80-e785-11e9-8563-ee3575d9a1f2.png">

---

The code corresponding to the fig above

```
    def bar(self, **kwds):
        """
        Vertical bar plot.
        Parameters
        ----------
        `**kwds` : optional
            Additional keyword arguments are documented in
            :meth:`Koalas.Series.plot`.
```

**Comment by HyukjinKwon** [comment]
@harupy, are you interested in submitting a PR?

**Comment by harupy** [comment]
Created a PR↑
