### ISSUE TITLE
Specifying types or changing a column's type

### ISSUE THREAD

**Issue by zHaytam** [databricks/koalas#915]
Hello,

Is it possible to specify the columns types when loading data (e.g. csv) or changing a column's type after creating a dataframe?

Thanks!

**Comment by HyukjinKwon** [comment]
Can you try this -https://github.com/databricks/koalas/pull/604?

**Comment by zHaytam** [comment]
It seems to work, although users would need to specify all columns since it uses `selectExpr`. I guess this does the job for now, but an implementation of `dtype={‘a’: np.float64, ‘b’: np.int32, ‘c’: ‘Int64’}` and `to_numeric` or `as_type` would be great!

**Comment by zHaytam** [comment]
I don't know why sometimes, the result is full of None

**Comment by HyukjinKwon** [comment]
Do you mind if I ask your codes to reproduce and investigate further?

**Comment by ueshin** [comment]
Btw, I'm working on adding `dtype` argument as well as other options for `read_csv`.
