### ISSUE TITLE
Dataframe nlargest is very slow

### ISSUE THREAD

**Issue by jimfulton** [databricks/koalas#917]
The existing implementation is naive, just sorting and picking the N largest.  This is O(R * ln(R)) where R is the number of rows.  Users expect O(R * ln(N)), where N is the number passed to `nlargest`.  I get this is complicated in a distributed setting. :)

Googling I found advice to use the RDD `top` method.

This is much faster for me:

```
def nlargest(spark, df, n, col):
    return ks.DataFrame(
        spark.sparkContext.parallelize(
            df.to_spark().rdd.top(n, operator.attrgetter(col))
            ).toDF()
        )
```

I tested with a df of length 17 million and an N of 9999.

**Comment by HyukjinKwon** [comment]
thanks for a headup. Can you roughly show the perf difference between them? DataFrame APIs are supposed to be more optimal and I would get surprised in RDD one is faster in general. However, such things happen in our real life :-).

**Comment by HyukjinKwon** [comment]
Closing this, no feedback. Performance issue might be related to https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html.
