### ISSUE TITLE
Include Dask license again

### ISSUE THREAD

**Issue by kokes** [databricks/koalas#940]
The Dask license was removed in #284, where the user-facing Dask code got deleted, but there are still bits of Dask in the codebase, at least in tests. As noted in #12:

> The license allows us to copy the code, if we put the proper attribution in the README

And since these tests are still in place, I suggest the license gets included again.

(I'm not a licensing expert, I'm not sure what the implications of code copying are, I'm just following the quote from the issue above.)

**Comment by HyukjinKwon** [comment]
No, the tests are completely different if you refer this file:

https://github.com/dask/dask/blob/master/dask/dataframe/tests/test_dataframe.py
vs
https://github.com/databricks/koalas/blob/master/databricks/koalas/tests/test_dataframe.py

and we now have anything copied from Dask.

**Comment by kokes** [comment]
Look at the issue I linked, where the author talks explicitly about adapting Dask code. And the code is still live in your test suite, see e.g.:

https://github.com/dask/dask/blob/e734544ef74aa0b1db1144d3f0a193b8f313d9d1/dask/dataframe/tests/test_dataframe.py#L156
https://github.com/databricks/koalas/blob/465861cbb70dbe98ba8b5ac5477ed7c99b184b2d/databricks/koalas/tests/test_dataframe.py#L307

**Comment by HyukjinKwon** [comment]
Here's the test you pointed out:
![Screen Shot 2019-10-21 at 4 18 14 AM](https://user-images.githubusercontent.com/6477701/67171983-d46e2b80-f3b9-11e9-9240-2393cde6d934.png)
![Screen Shot 2019-10-21 at 4 18 18 AM](https://user-images.githubusercontent.com/6477701/67171985-d506c200-f3b9-11e9-84af-42bc3fec6c20.png)

I don't think we should add a license when it borrows an idea.
