### ISSUE TITLE
create index by using list

### ISSUE THREAD

**Issue by itholic** [databricks/koalas#948]
are we planning to support create index by using list like pandas?

```python
>>> idx = pd.Index(['lama', 'cow', 'lama', 'beetle', 'lama', 'hippo'])
>>> idx
Index(['lama', 'cow', 'lama', 'beetle', 'lama', 'hippo'], dtype='object')
```

if so, maybe i could be going to work on it.

**Comment by HyukjinKwon** [comment]
+1. cc @ueshin

**Comment by charlesdong1991** [comment]
i'd love to have this!!

**Comment by itholic** [comment]
@charlesdong1991 sure, you can fell free to work on this. let's get started! 😸
