### ISSUE TITLE
Top-level Pandas functions - merge

### ISSUE THREAD

**Issue by gatorsmile** [databricks/koalas#961]
https://pandas.pydata.org/pandas-docs/stable/reference/general_functions.html

```Python
ks.merge(kdf, kdf)

AttributeError: module 'databricks.koalas' has no attribute 'merge'
```

**Comment by itholic** [comment]
Thanks for posting issue. i'm going to work on this.

**Comment by HyukjinKwon** [comment]
Please go ahead!!

**Comment by itholic** [comment]
@HyukjinKwon i just finished. could you check related PR when you available?
